In [1]:
#Following document is for preprocessing.

Following document is for preprocessing


!pip uninstall -y edgar edgartools
!pip install -U edgartools
from edgar import *

In [2]:
!pip install lxml_html_clean
!pip install newspaper
!pip install newspaper3k
!pip install lxml_html_clean
!pip install dataclasses
!pip install spacy

Requirement already satisfied: lxml_html_clean in /opt/anaconda3/lib/python3.12/site-packages (0.4.4)
Requirement already satisfied: lxml in /opt/anaconda3/lib/python3.12/site-packages (from lxml_html_clean) (5.2.1)
Collecting newspaper
  Using cached newspaper-0.1.0.7.tar.gz (176 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      WARNING! You are attempting to install newspaper's python2 repository on python3. PLEASE RUN `$ pip3 install newspaper3k` for python3 or `$ pip install newspaper` for python2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Requirement already satisfied: newspaper3k in /opt/anaconda3/lib/python3.12/site-packages (0.2.8)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /opt/anaconda3/lib/python3.12/site-packages (from newspaper3k) (4.12.3)
Requirement already satisfied: Pillow>=3.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from newspaper3k) (10.4.0)
Requirement already satisfied: PyYAML>=3.11 in /opt/anaconda3/lib/python3.12/site-packages (from newspaper3k) (6.0.1)
Requirement already satisfied: cssselect>=0.9.2 in /opt/anaconda3/lib/python3.12/site-packages (from newspaper3k) (1.2.0)
Requirement already satisfied: lxml>=3.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from newspaper3k) (5.2.1)
Requirement already satisfied: nltk>=3.2.1 in /opt/anaconda3/lib/python3.12/site-packages (from newspaper3k) (3.9.1)
Requirement already satisfied: requests>=2.10.0 in /opt/anaconda3/lib/python3.12/site-packages (from newspaper3k) (2.32.3)
Requirement already satisfied: feedparser>=5.2.1 in /opt/anaconda3/lib/python3.12/site-packages (from newspaper3k) (6.0.12)
Requirement already satisfied: tldextract>=2.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from newspaper3k) (5.1.2)
Requirement already satisfied: feedfinder2>=0.0.4 in /opt/anaconda3/lib/python3.12/site-packages (from newspaper3k) (0.0.4)
Requirement already satisfied: jieba3k>=0.35.1 in /opt/anaconda3/lib/python3.12/site-packages (from newspaper3k) (0.35.1)
Requirement already satisfied: python-dateutil>=2.5.3 in /opt/anaconda3/lib/python3.12/site-packages (from newspaper3k) (2.9.0.post0)
Requirement already satisfied: tinysegmenter==0.3 in /opt/anaconda3/lib/python3.12/site-packages (from newspaper3k) (0.3)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.12/site-packages (from beautifulsoup4>=4.4.1->newspaper3k) (2.5)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.12/site-packages (from feedfinder2>=0.0.4->newspaper3k) (1.16.0)
Requirement already satisfied: sgmllib3k in /opt/anaconda3/lib/python3.12/site-packages (from feedparser>=5.2.1->newspaper3k) (1.0.0)
Requirement already satisfied: click in /opt/anaconda3/lib/python3.12/site-packages (from nltk>=3.2.1->newspaper3k) (8.1.7)
Requirement already satisfied: joblib in /opt/anaconda3/lib/python3.12/site-packages (from nltk>=3.2.1->newspaper3k) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /opt/anaconda3/lib/python3.12/site-packages (from nltk>=3.2.1->newspaper3k) (2026.4.4)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.12/site-packages (from nltk>=3.2.1->newspaper3k) (4.66.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.10.0->newspaper3k) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.10.0->newspaper3k) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.10.0->newspaper3k) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.10.0->newspaper3k) (2026.1.4)
Requirement already satisfied: requests-file>=1.4 in /opt/anaconda3/lib/python3.12/site-packages (from tldextract>=2.0.1->newspaper3k) (1.5.1)
Requirement already satisfied: filelock>=3.0.8 in /opt/anaconda3/lib/python3.12/site-packages (from tldextract>=2.0.1->newspaper3k) (3.29.0)
Requirement already satisfied: lxml_html_clean in /opt/anaconda3/lib/python3.12/site-packages (0.4.4)
Requirement already satisfied: lxml in /opt/anaconda3/lib/python3.12/site-packages (from lxml_html_clean) (5.2.1)
Requirement already satisfied: dataclasses in /opt/anaconda3/lib/python3.12/site-packages (0.6)
Requirement already satisfied: spacy in /opt/anaconda3/lib/python3.12/site-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (0.20.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (4.66.5)
Requirement already satisfied: numpy>=1.19.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (2.8.2)
Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (3.1.4)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (75.1.0)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.12/site-packages (from spacy) (24.1)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: click>=8.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /opt/anaconda3/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /opt/anaconda3/lib/python3.12/site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: cloudpathlib>=0.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in /opt/anaconda3/lib/python3.12/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (5.2.1)
Requirement already satisfied: httpx>=0.24.0 in /opt/anaconda3/lib/python3.12/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2->spacy) (2.1.3)
Requirement already satisfied: anyio in /opt/anaconda3/lib/python3.12/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.2.0)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/lib/python3.12/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.2)
Requirement already satisfied: h11<0.15,>=0.13 in /opt/anaconda3/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.14.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.0)
Requirement already satisfied: sniffio>=1.1 in /opt/anaconda3/lib/python3.12/site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.3.0)

In [3]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 12.3 MB/s eta 0:00:0000:0100:01
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

#need News api below

#Step for getting the newsAPI

In [ ]:
#code for getting the news api
#next one
# ============================================================
# Hybrid News Retrieval Pipeline — Google Colab
# v8 — Interactive inputs · Expanded free sources
#      3-stage scraper · Subject-aware filtering
#      Boilerplate-aware first paragraph cleaning
# ============================================================
# Cell 1 — install dependencies (run once):
#
#   !pip install newspaper3k feedparser requests python-dateutil spacy -q
#   !python -m spacy download en_core_web_sm -q
#
# Cell 2 — paste and run this entire cell
# ============================================================

import re
import logging
from collections import Counter, defaultdict
from datetime import datetime, timedelta, timezone
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass

import requests
import feedparser
import spacy
from dateutil import parser as dateutil_parser
from newspaper import Article

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# ============================================================
# ★  YOUR NEWSAPI KEY
# ============================================================
NEWSAPI_KEY    = ""    # paste your key here
MAX_PER_SOURCE = 7
# ============================================================

# ── Interactive inputs ───────────────────────────────────────────
print("=" * 60)
print("  HYBRID NEWS RETRIEVAL PIPELINE")
print("=" * 60)
company_name = input("\n  Enter company name (e.g. Meta, Google, Apple): ").strip()
days_input   = input("  Enter days to look back — max 25 (press Enter for 25): ").strip()
DAYS_BACK    = int(days_input) if days_input.isdigit() else 25
DAYS_BACK    = min(DAYS_BACK, 25)  # enforce free tier limit
QUESTION     = f"What is happening with {company_name} lately?"
print(f"\n  Company  : {company_name}")
print(f"  Days back: {DAYS_BACK}")
print(f"  Question : {QUESTION}")
print("=" * 60 + "\n")

NEWSAPI_URL  = "https://newsapi.org/v2/everything"
MAX_WORKERS  = 10
MIN_TEXT_LEN = 150
PAGE_SIZE    = 100

# ── Browser-like headers to avoid scraping blocks ───────────────
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    ),
    "Accept":          "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Accept-Encoding": "gzip, deflate",
    "Connection":      "keep-alive",
}

# ── Free sources only ────────────────────────────────────────────
NEWSAPI_DOMAINS = ",".join([
    "reuters.com",
    "apnews.com",
    "cnbc.com",
    "marketwatch.com",
    "finance.yahoo.com",
    "thestreet.com",
    "nasdaq.com",
    "fortune.com",
    "fool.com",
    "businesswire.com",
    "prnewswire.com",
    "techcrunch.com",
    "venturebeat.com",
    "wired.com",
    "arstechnica.com",
    "zdnet.com",
    "theguardian.com",
])

# ── Source priority ──────────────────────────────────────────────
SOURCE_PRIORITY = {
    "reuters":          10,
    "associated press": 10,
    "ap news":          10,
    "cnbc":             9,
    "marketwatch":      9,
    "yahoo finance":    8,
    "nasdaq":           8,
    "fortune":          8,
    "the street":       7,
    "thestreet":        7,
    "the guardian":     7,
    "business wire":    7,
    "businesswire":     7,
    "pr newswire":      7,
    "prnewswire":       7,
    "techcrunch":       6,
    "venturebeat":      6,
    "wired":            6,
    "ars technica":     6,
    "arstechnica":      6,
    "zdnet":            5,
    "motley fool":      5,
}

# ── RSS feeds ────────────────────────────────────────────────────
RSS_FEEDS = [
    ("Reuters Business",      "https://feeds.reuters.com/reuters/businessNews"),
    ("Reuters Technology",    "https://feeds.reuters.com/reuters/technologyNews"),
    ("AP News Business",      "https://feeds.apnews.com/rss/apf-business"),
    ("CNBC Top News",         "https://feeds.content.dowjones.io/public/rss/mktgNewsHeadlines"),
    ("CNBC Technology",       "https://feeds.content.dowjones.io/public/rss/mktgTechNewsHeadlines"),
    ("MarketWatch",           "https://feeds.marketwatch.com/marketwatch/topstories"),
    ("The Motley Fool",       "https://www.fool.com/feeds/index.aspx"),
    ("The Street",            "https://www.thestreet.com/rss/index.xml"),
    ("TechCrunch",            "https://techcrunch.com/category/startups/feed/"),
    ("VentureBeat",           "https://venturebeat.com/feed/"),
    ("Wired Business",        "https://www.wired.com/feed/category/business/latest/rss"),
    ("Ars Technica",          "https://feeds.arstechnica.com/arstechnica/index"),
 #   ("ZDNet",                 "https://www.zdnet.com/news/rss.xml"),
    ("PR Newswire Tech",      "https://www.prnewswire.com/rss/news-releases-list.rss"),
    ("Business Wire",         "https://feed.businesswire.com/rss/home/?rss=G1&_gl=1"),
    ("The Guardian Business", "https://www.theguardian.com/business/rss"),
    ("The Guardian Tech",     "https://www.theguardian.com/technology/rss"),
    ("BBC Business",          "https://feeds.bbci.co.uk/news/business/rss.xml"),
    ("Fortune",               "https://fortune.com/feed"),
]

# ── Company aliases ──────────────────────────────────────────────
ALIAS_MAP = {
    "meta":       {"meta platforms", "facebook"},
    "apple":      {"aapl"},
    "google":     {"alphabet", "googl"},
    "amazon":     {"amzn"},
    "tesla":      {"tsla"},
    "nvidia":     {"nvda"},
    "microsoft":  {"msft"},
    "netflix":    {"nflx"},
    "uber":       {"uber technologies"},
    "twitter":    {"x corp", "x.com"},
    "snapchat":   {"snap inc", "snap"},
    "spotify":    {"spot"},
    "airbnb":     {"abnb"},
    "lyft":       {"lyft inc"},
    "samsung":    {"samsung electronics"},
    "intel":      {"intc"},
    "amd":        {"advanced micro devices"},
    "salesforce": {"crm"},
    "oracle":     {"orcl"},
    "ibm":        {"international business machines"},
}

# ── Boilerplate patterns for body text filter ────────────────────
BOILERPLATE_PATTERNS = [
    r"subscribe to our newsletter",
    r"sign up for",
    r"enable javascript",
    r"cookies? to improve",
    r"please enable",
    r"advertisement",
]

# ── Navigation/promo lines to strip before subject check ─────────
HEADER_NOISE_PATTERNS = [
    r"add .+ as your preferred",
    r"^share$",
    r"^read more$",
    r"^advertisement$",
    r"^skip to",
    r"^sign in$",
    r"^subscribe$",
    r"^follow us",
    r"^newsletter$",
]

# ─── data model ─────────────────────────────────────────────────
@dataclass
class CandidateArticle:
    title:        str
    source:       str
    published_at: datetime
    url:          str
    raw_text:     str = ""
    drop_reason:  str = ""

# ─── 1. NER — detect company ────────────────────────────────────
def detect_company(question: str) -> str:
    nlp  = spacy.load("en_core_web_sm")
    doc  = nlp(question)
    orgs = [ent.text for ent in doc.ents if ent.label_ == "ORG"]
    if orgs:
        log.info(f"NER detected company: {orgs[0]}")
        return orgs[0]
    skip = {"what","who","how","when","where","why","is","are","the","a","an"}
    for token in doc:
        if token.text[0].isupper() and token.text.lower() not in skip:
            log.info(f"NER fallback company: {token.text}")
            return token.text
    return ""

# ─── 2. Temporal NER ────────────────────────────────────────────
def detect_days_back(question: str) -> int:
    q = question.lower()
    patterns = [
        (r"\btoday\b|\bright now\b|\bcurrently\b",  1),
        (r"\bthis week\b|\blately\b|\brecently\b",  7),
        (r"\blast week\b",                           7),
        (r"\bthis month\b|\blast month\b",          30),
        (r"\bthis year\b|\blast year\b",            365),
        (r"\blast (\d+) days?\b",                   "days"),
        (r"\blast (\d+) weeks?\b",                  "weeks"),
        (r"\blast (\d+) months?\b",                 "months"),
    ]
    for pattern, unit in patterns:
        m = re.search(pattern, q)
        if m:
            if isinstance(unit, int):
                log.info(f"Temporal NER: '{m.group()}' → {unit} days")
                return unit
            n      = int(m.group(1))
            result = n * (7 if unit=="weeks" else 30 if unit=="months" else 1)
            log.info(f"Temporal NER: '{m.group()}' → {result} days")
            return result
    log.info("Temporal NER: no match, defaulting to 7 days")
    return 7

# ─── 3a. NewsAPI retrieval ───────────────────────────────────────
def fetch_newsapi(company: str, days_back: int) -> list:
    if not NEWSAPI_KEY or NEWSAPI_KEY == "YOUR_NEWSAPI_KEY_HERE":
        log.warning("NewsAPI key not set — skipping NewsAPI. Only RSS will be used.")
        return []

    from_date = (
        datetime.now(timezone.utc) - timedelta(days=days_back)
    ).strftime("%Y-%m-%d")

    all_articles = []
    seen_urls    = set()

    # ── Call 1: main domain list ─────────────────────────────────
    params_main = {
        "q":        f'"{company}"',
        "from":     from_date,
        "sortBy":   "relevancy",
        "pageSize": PAGE_SIZE,
        "language": "en",
        "domains":  NEWSAPI_DOMAINS,
        "apiKey":   NEWSAPI_KEY,
    }
    try:
        resp = requests.get(NEWSAPI_URL, params=params_main, timeout=10)
        resp.raise_for_status()
        data = resp.json()
        if data.get("status") == "ok":
            for item in data.get("articles", []):
                url = item.get("url", "")
                if url and url not in seen_urls:
                    seen_urls.add(url)
                    try:
                        pub = dateutil_parser.parse(
                            item["publishedAt"]
                        ).replace(tzinfo=timezone.utc)
                    except Exception:
                        pub = datetime.now(timezone.utc)
                    all_articles.append(CandidateArticle(
                        title=item.get("title", ""),
                        source=item.get("source", {}).get("name", "NewsAPI"),
                        published_at=pub,
                        url=url,
                    ))
            log.info(
                f"NewsAPI main: {len(all_articles)} candidates "
                f"(total available: {data.get('totalResults','?')})"
            )
        else:
            log.error(f"NewsAPI main error: {data.get('message', 'unknown')}")
    except requests.RequestException as e:
        log.error(f"NewsAPI main request failed: {e}")

    # ── Call 2: Yahoo Finance specifically ───────────────────────
    params_yahoo = {
        "q":        f'"{company}" site:finance.yahoo.com',
        "from":     from_date,
        "sortBy":   "relevancy",
        "pageSize": 20,
        "language": "en",
        "apiKey":   NEWSAPI_KEY,
    }
    try:
        resp_yf = requests.get(NEWSAPI_URL, params=params_yahoo, timeout=10)
        resp_yf.raise_for_status()
        data_yf = resp_yf.json()
        yf_count = 0
        if data_yf.get("status") == "ok":
            for item in data_yf.get("articles", []):
                url = item.get("url", "")
                if url and url not in seen_urls and "yahoo" in url.lower():
                    seen_urls.add(url)
                    yf_count += 1
                    try:
                        pub = dateutil_parser.parse(
                            item["publishedAt"]
                        ).replace(tzinfo=timezone.utc)
                    except Exception:
                        pub = datetime.now(timezone.utc)
                    all_articles.append(CandidateArticle(
                        title=item.get("title", ""),
                        source="Yahoo Finance",
                        published_at=pub,
                        url=url,
                    ))
            log.info(f"NewsAPI Yahoo Finance: {yf_count} additional candidates")
        else:
            log.warning(
                f"NewsAPI Yahoo Finance: {data_yf.get('message', 'unknown')}"
            )
    except requests.RequestException as e:
        log.error(f"NewsAPI Yahoo Finance request failed: {e}")

    log.info(f"NewsAPI total: {len(all_articles)} candidates")
    return all_articles

# ─── 3b. RSS retrieval ───────────────────────────────────────────
def fetch_rss_feed(
    feed_name: str, feed_url: str, company: str, days_back: int
) -> list:
    cutoff        = datetime.now(timezone.utc) - timedelta(days=days_back)
    company_lower = company.lower()
    articles      = []
    try:
        feed = feedparser.parse(feed_url)
    except Exception as e:
        log.warning(f"RSS fetch failed for {feed_name}: {e}")
        return []

    for entry in feed.entries:
        try:
            pub_struct = (
                entry.get("published_parsed") or entry.get("updated_parsed")
            )
            pub = (
                datetime(*pub_struct[:6], tzinfo=timezone.utc)
                if pub_struct
                else datetime.now(timezone.utc)
            )
        except Exception:
            pub = datetime.now(timezone.utc)

        if pub < cutoff:
            continue

        title   = entry.get("title", "")
        summary = entry.get("summary", "")
        url     = entry.get("link", "")

        if company_lower not in (title + " " + summary).lower():
            continue

        articles.append(CandidateArticle(
            title=title, source=feed_name,
            published_at=pub, url=url,
        ))

    log.info(f"RSS '{feed_name}': {len(articles)} matches for '{company}'")
    return articles

def fetch_all_rss(company: str, days_back: int) -> list:
    all_articles = []
    with ThreadPoolExecutor(max_workers=len(RSS_FEEDS)) as executor:
        futures = {
            executor.submit(fetch_rss_feed, name, url, company, days_back): name
            for name, url in RSS_FEEDS
        }
        for future in as_completed(futures):
            try:
                all_articles.extend(future.result())
            except Exception as e:
                log.warning(f"RSS future error: {e}")
    return all_articles

# ─── 4. Merge · deduplicate · prioritise · cap ──────────────────
def get_source_priority(source: str) -> int:
    source_lower = source.lower()
    return max(
        (v for k, v in SOURCE_PRIORITY.items() if k in source_lower),
        default=3
    )

def merge_and_deduplicate(newsapi_articles: list, rss_articles: list) -> list:
    seen_urls = set()
    merged    = []

    for art in newsapi_articles:
        if art.url and art.url not in seen_urls:
            seen_urls.add(art.url)
            merged.append(art)
    for art in rss_articles:
        if art.url and art.url not in seen_urls:
            seen_urls.add(art.url)
            merged.append(art)

    merged.sort(
        key=lambda a: (get_source_priority(a.source), a.published_at),
        reverse=True
    )

    source_counts = defaultdict(int)
    capped        = []
    for art in merged:
        if source_counts[art.source] < MAX_PER_SOURCE:
            capped.append(art)
            source_counts[art.source] += 1

    log.info(
        f"Merged: {len(newsapi_articles)} NewsAPI + {len(rss_articles)} RSS "
        f"→ {len(merged)} unique → {len(capped)} after source cap"
    )
    counts = Counter(art.source for art in capped)
    for src, n in counts.most_common():
        log.info(f"  {src:<35} : {n} articles")
    return capped

# ─── 5. Improved 3-stage scraper ────────────────────────────────
def scrape_article(art: CandidateArticle) -> CandidateArticle:
    """
    Stage 1: newspaper3k default downloader
    Stage 2: requests with browser User-Agent → re-parse with newspaper3k
    Stage 3: raw <p> tag extraction as final fallback
    """
    try:
        # Stage 1
        a = Article(art.url)
        a.download()
        a.parse()
        art.raw_text = a.text.strip()

        # Stage 2
        if not art.raw_text or len(art.raw_text) < MIN_TEXT_LEN:
            resp = requests.get(art.url, headers=HEADERS, timeout=12)
            if resp.status_code == 200:
                a2 = Article(art.url)
                a2.set_html(resp.text)
                a2.parse()
                candidate = a2.text.strip()
                if len(candidate) > len(art.raw_text):
                    art.raw_text = candidate

        # Stage 3
        if not art.raw_text or len(art.raw_text) < MIN_TEXT_LEN:
            try:
                resp = requests.get(art.url, headers=HEADERS, timeout=12)
                if resp.status_code == 200:
                    paragraphs  = re.findall(
                        r'<p[^>]*>(.*?)</p>', resp.text,
                        re.DOTALL | re.IGNORECASE
                    )
                    clean_paras = [
                        re.sub(r'<[^>]+>', '', p).strip()
                        for p in paragraphs
                    ]
                    body = "\n\n".join(p for p in clean_paras if len(p) > 40)
                    if len(body) > len(art.raw_text):
                        art.raw_text = body
            except Exception:
                pass

    except Exception as e:
        if not art.raw_text:
            art.drop_reason = f"scrape_error: {e}"

    return art

def parallel_scrape(candidates: list) -> list:
    results = []
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {
            executor.submit(scrape_article, art): art for art in candidates
        }
        for future in as_completed(futures):
            try:
                results.append(future.result())
            except Exception as e:
                log.warning(f"Scrape future error: {e}")
    return results

# ─── 6. First paragraph cleaner ─────────────────────────────────
def clean_first_para(text: str) -> str:
    """
    Strip navigation and promotional lines from the top of
    article text before subject check. This prevents boilerplate
    like 'Add AP News on Google' from being treated as a
    subject mention of Google.
    """
    lines = text.split('\n')
    clean = [
        line for line in lines
        if not any(
            re.search(pattern, line.strip().lower())
            for pattern in HEADER_NOISE_PATTERNS
        )
    ]
    return '\n'.join(clean)[:500].lower()

# ─── 7. Heuristic + subject-aware filtering ─────────────────────
def apply_filters(articles: list, company: str):
    company_lower = company.lower()
    aliases       = {company_lower} | ALIAS_MAP.get(company_lower, set())
    kept, dropped = [], []

    for art in articles:

        # ── already flagged by scraper ───────────────────────────
        if art.drop_reason:
            dropped.append(art); continue

        # ── empty text ───────────────────────────────────────────
        if not art.raw_text.strip():
            art.drop_reason = "empty_text"
            dropped.append(art); continue

        # ── too short ────────────────────────────────────────────
        if len(art.raw_text) < MIN_TEXT_LEN:
            art.drop_reason = f"too_short ({len(art.raw_text)} chars)"
            dropped.append(art); continue

        # ── boilerplate body ─────────────────────────────────────
        if any(re.search(p, art.raw_text.lower()) for p in BOILERPLATE_PATTERNS):
            art.drop_reason = "boilerplate"
            dropped.append(art); continue

        # ── subject check ────────────────────────────────────────
        # company must appear in title OR cleaned first paragraph.
        # clean_first_para() strips nav/promo lines first so that
        # boilerplate like "Add AP News on Google" does not count
        # as a subject match for Google.
        title_lower   = art.title.lower()
        first_para    = clean_first_para(art.raw_text)
        in_title      = any(alias in title_lower  for alias in aliases)
        in_first_para = any(alias in first_para   for alias in aliases)

        if not (in_title or in_first_para):
            art.drop_reason = "not_subject (not in title or first para)"
            dropped.append(art); continue

        kept.append(art)

    log.info(f"Filtering: {len(kept)} kept, {len(dropped)} dropped")
    return kept, dropped

# ─── 8. Content verification ────────────────────────────────────
def verify_content(df: list, df_articles: list):
    print(f"\n{'='*60}")
    print(f"  CONTENT VERIFICATION")
    print(f"{'='*60}")

    if not df:
        print("  No kept articles to verify.")
        return

    total_chars = sum(len(a.raw_text) for a in df)
    avg_chars   = total_chars // len(df)
    print(f"  Kept articles      : {len(df)}")
    print(f"  Total content      : {total_chars:,} chars")
    print(f"  Average per article: {avg_chars:,} chars")

    counts = Counter(a.source for a in df)
    print(f"\n  Source breakdown:")
    for src, n in counts.most_common():
        print(f"    {src:<35} : {n} articles")
    print(f"{'='*60}\n")

    for i, art in enumerate(df, 1):
        char_count = len(art.raw_text)
        print(f"  ── Article {i} {'─'*44}")
        print(f"  Title  : {art.title}")
        print(f"  Source : {art.source}")
        print(f"  Date   : {art.published_at.strftime('%Y-%m-%d %H:%M')}")
        print(f"  URL    : {art.url[:70]}...")
        print(f"  Length : {char_count:,} chars")
        print(f"\n  First 500 chars of raw_text:")
        print(f"  {'-'*50}")
        preview = art.raw_text[:500].replace('\n', '\n  ')
        print(f"  {preview}")
        if char_count > 500:
            print(f"  ... [{char_count - 500:,} more chars]")
        print()

    if df_articles:
        print(f"\n{'='*60}")
        print(f"  DROPPED — REASON BREAKDOWN")
        print(f"{'='*60}")
        reasons = Counter(
            a.drop_reason.split("(")[0].strip()
            for a in df_articles if a.drop_reason
        )
        for reason, count in reasons.most_common():
            print(f"  {reason:<40} : {count} articles")
        print()

# ─── 9. Main pipeline ────────────────────────────────────────────
def run_pipeline(question: str):
    print(f"\n{'='*60}")
    print(f"  QUESTION : {question}")
    print(f"{'='*60}\n")

    company = detect_company(question)
    if not company:
        print("ERROR: Could not extract company name from question.")
        return None, None

    days_back = DAYS_BACK if DAYS_BACK else detect_days_back(question)

    print(f"  Company       : {company}")
    print(f"  Days back     : {days_back}")
    print(f"  Max per source: {MAX_PER_SOURCE}")
    print(f"  NewsAPI domains: {len(NEWSAPI_DOMAINS.split(','))}")
    print(f"  RSS feeds     : {len(RSS_FEEDS)}\n")

    with ThreadPoolExecutor(max_workers=2) as executor:
        f_newsapi        = executor.submit(fetch_newsapi, company, days_back)
        f_rss            = executor.submit(fetch_all_rss,  company, days_back)
        newsapi_articles = f_newsapi.result()
        rss_articles     = f_rss.result()

    candidates = merge_and_deduplicate(newsapi_articles, rss_articles)
    if not candidates:
        print("No candidate articles found.")
        return [], []

    print(f"\n  Scraping {len(candidates)} URLs (3-stage scraper)...\n")
    scraped       = parallel_scrape(candidates)
    kept, dropped = apply_filters(scraped, company)

    print(f"\n{'='*60}")
    print(f"  PIPELINE RESULTS — '{company}' ({days_back} days)")
    print(f"{'='*60}")
    print(f"  NewsAPI candidates  : {len(newsapi_articles)}")
    print(f"  RSS candidates      : {len(rss_articles)}")
    print(f"  After dedup + cap   : {len(candidates)}")
    print(f"  Kept after filtering: {len(kept)}")
    print(f"  Dropped             : {len(dropped)}")
    print(f"{'='*60}")

    if kept:
        print("\n  KEPT ARTICLES:")
        for i, art in enumerate(kept, 1):
            priority = get_source_priority(art.source)
            print(f"  {i}. [P{priority}] [{art.source}] {art.title[:55]}...")
            print(f"     {art.published_at.strftime('%Y-%m-%d')} | {len(art.raw_text):,} chars")
            print()

    if dropped:
        print("\n  DROPPED (debug):")
        for art in dropped:
            print(f"  - [{art.drop_reason:<40}] {art.title[:40]}...")

    print()
    verify_content(kept, dropped)
    return kept, dropped

# ─── 10. Convert to dataframe ────────────────────────────────────
def to_dataframe(kept: list, dropped: list):
    import pandas as pd

    df_final = pd.DataFrame([{
        "company":      company_name,
        "title":        art.title,
        "source":       art.source,
        "published_at": art.published_at,
        "url":          art.url,
        "raw_text":     art.raw_text,
        "char_count":   len(art.raw_text),
        "priority":     get_source_priority(art.source),
    } for art in kept])

    df_debug = pd.DataFrame([{
        "company":      company_name,
        "title":        art.title,
        "source":       art.source,
        "published_at": art.published_at,
        "url":          art.url,
        "drop_reason":  art.drop_reason,
    } for art in dropped])

    print(f"\n  df_final : {len(df_final)} rows × {len(df_final.columns)} cols")
    print(f"  df_debug : {len(df_debug)} rows × {len(df_debug.columns)} cols\n")
    return df_final, df_debug

# ─── 11. Multi-query runner (optional) ───────────────────────────
def run_multi_query(base_company: str, extra_terms: list = None):
    """
    Run pipeline for multiple related queries and combine results.
    Useful for getting more training data volume.

    Example:
        df_combined, _ = run_multi_query("Meta", ["Meta Platforms", "Mark Zuckerberg"])
    """
    queries     = [base_company] + (extra_terms or [])
    all_kept    = []
    all_dropped = []

    for term in queries:
        print(f"\n{'─'*60}")
        print(f"  Running query for: {term}")
        print(f"{'─'*60}")
        k, d = run_pipeline(f"What is happening with {term} lately?")
        if k: all_kept.extend(k)
        if d: all_dropped.extend(d)

    seen        = set()
    unique_kept = []
    for art in all_kept:
        if art.url not in seen:
            seen.add(art.url)
            unique_kept.append(art)

    print(f"\n{'='*60}")
    print(f"  MULTI-QUERY SUMMARY")
    print(f"{'='*60}")
    print(f"  Queries run     : {len(queries)}")
    print(f"  Total kept      : {len(all_kept)}")
    print(f"  After URL dedup : {len(unique_kept)}")
    print(f"{'='*60}\n")

    return to_dataframe(unique_kept, all_dropped)

# ─── RUN ─────────────────────────────────────────────────────────
kept, dropped      = run_pipeline(QUESTION)
df_final, df_debug = to_dataframe(kept, dropped)
from IPython.display import display

print("  df_final preview:")
print(df_final[["company", "title", "source", "published_at", "char_count", "priority"]].to_string())

# ── Optional: run multiple related queries for more volume ───────
# Uncomment to use:
#
# df_combined, df_debug_combined = run_multi_query(
#     company_name,
#     extra_terms=[f"{company_name} stock", f"{company_name} earnings"]
# )
# display(df_combined[["company", "title", "source", "published_at", "char_count"]])

============================================================
  HYBRID NEWS RETRIEVAL PIPELINE
============================================================

  Company  : Meta
  Days back: 25
  Question : What is happening with Meta lately?
============================================================


============================================================
  QUESTION : What is happening with Meta lately?
============================================================

22:11:56  INFO      NER fallback company: Meta

  Company       : Meta
  Days back     : 25
  Max per source: 7
  NewsAPI domains: 17
  RSS feeds     : 18

22:11:57  INFO      NewsAPI main: 100 candidates (total available: 190)
22:11:57  INFO      NewsAPI Yahoo Finance: 0 additional candidates
22:11:57  INFO      NewsAPI total: 100 candidates
22:11:58  INFO      RSS 'AP News Business': 0 matches for 'Meta'
22:11:58  INFO      RSS 'Reuters Business': 0 matches for 'Meta'
22:11:58  INFO      RSS 'Reuters Technology': 0 matches for 'Meta'
22:11:58  INFO      RSS 'The Street': 0 matches for 'Meta'
22:11:58  INFO      RSS 'TechCrunch': 0 matches for 'Meta'
22:11:58  INFO      RSS 'Ars Technica': 1 matches for 'Meta'
22:11:58  INFO      RSS 'Wired Business': 1 matches for 'Meta'
22:11:58  INFO      RSS 'CNBC Technology': 0 matches for 'Meta'
22:11:58  INFO      RSS 'Fortune': 0 matches for 'Meta'
22:11:58  INFO      RSS 'PR Newswire Tech': 0 matches for 'Meta'
22:11:58  INFO      RSS 'MarketWatch': 1 matches for 'Meta'
22:11:58  INFO      RSS 'BBC Business': 1 matches for 'Meta'
22:11:58  INFO      RSS 'The Guardian Business': 1 matches for 'Meta'
22:11:58  INFO      RSS 'The Guardian Tech': 0 matches for 'Meta'
22:11:58  INFO      RSS 'VentureBeat': 0 matches for 'Meta'
22:11:58  INFO      RSS 'CNBC Top News': 0 matches for 'Meta'
22:11:58  INFO      RSS 'The Motley Fool': 0 matches for 'Meta'
22:11:58  INFO      RSS 'Business Wire': 0 matches for 'Meta'
22:11:58  INFO      Merged: 100 NewsAPI + 5 RSS → 104 unique → 41 after source cap
22:11:58  INFO        CNBC                                : 7 articles
22:11:58  INFO        Fortune                             : 7 articles
22:11:58  INFO        Wired                               : 7 articles
22:11:58  INFO        ZDNet                               : 7 articles
22:11:58  INFO        TheStreet                           : 6 articles
22:11:58  INFO        MarketWatch                         : 3 articles
22:11:58  INFO        Associated Press                    : 1 articles
22:11:58  INFO        The Guardian Business               : 1 articles
22:11:58  INFO        Ars Technica                        : 1 articles
22:11:58  INFO        BBC Business                        : 1 articles

  Scraping 41 URLs (3-stage scraper)...

22:12:02  INFO      Filtering: 13 kept, 28 dropped

============================================================
  PIPELINE RESULTS — 'Meta' (25 days)
============================================================
  NewsAPI candidates  : 100
  RSS candidates      : 5
  After dedup + cap   : 41
  Kept after filtering: 13
  Dropped             : 28
============================================================

  KEPT ARTICLES:
  1. [P8] [Fortune] David’s Bridal exec has a warning for every CEO obsesse...
     2026-04-22 | 4,031 chars

  2. [P9] [CNBC] Meta is tracking employee keystrokes on Google, LinkedI...
     2026-04-23 | 3,853 chars

  3. [P7] [The Guardian Business] Kenyan firm sacks more than 1,000 workers after losing ...
     2026-04-17 | 2,686 chars

  4. [P8] [Fortune] Meta will start tracking employees’ screens and keystro...
     2026-04-21 | 2,311 chars

  5. [P6] [Wired] New Gas-Powered Data Centers Could Emit More Greenhouse...
     2026-04-22 | 3,297 chars

  6. [P6] [Ars Technica] Greenhouse gases from data center boom could outpace en...
     2026-04-23 | 14,909 chars

  7. [P6] [Wired] Meta’s New AI Asked for My Raw Health Data—and Gave Me ...
     2026-04-10 | 2,976 chars

  8. [P6] [Wired] Meta Is Warned That Facial Recognition Glasses Will Arm...
     2026-04-13 | 4,366 chars

  9. [P6] [Wired] Best Meta Glasses (2026): Ray-Ban, Oakley, AR...
     2026-04-19 | 2,817 chars

  10. [P3] [BBC Business] Meta says it will cut 8,000 jobs as AI spending soars...
     2026-04-23 | 289 chars

  11. [P5] [ZDNet] Get a free pair of Meta Ray-Bans with this Verizon Fios...
     2026-04-17 | 1,401 chars

  12. [P5] [ZDNet] How Flipboard's new Surf app lets you merge social feed...
     2026-04-03 | 4,106 chars

  13. [P5] [ZDNet] Meta is selling refurbished Ray-Bans for as low as $197...
     2026-04-14 | 1,401 chars


  DROPPED (debug):
  - [scrape_error: Article `download()` failed with 401 Client Error: HTTP Forbidden for url: https://www.marketwatch.com/story/cheap-options-suggest-a-big-post-earnings-swing-next-week-for-these-tech-titans-d9b56126?mod=mw_rss_topstories on URL https://www.marketwatch.com/story/cheap-options-suggest-a-big-post-earnings-swing-next-week-for-these-tech-titans-d9b56126?mod=mw_rss_topstories] Cheap stock options suggest a big post-e...
  - [scrape_error: Article `download()` failed with 401 Client Error: HTTP Forbidden for url: https://www.marketwatch.com/story/nasdaq-heads-toward-its-longest-winning-streak-since-1992-as-historic-stock-market-comeback-continues-e84c2c59 on URL https://www.marketwatch.com/story/nasdaq-heads-toward-its-longest-winning-streak-since-1992-as-historic-stock-market-comeback-continues-e84c2c59] Nasdaq scores longest winning streak sin...
  - [scrape_error: Article `download()` failed with 401 Client Error: HTTP Forbidden for url: https://www.marketwatch.com/story/were-aiming-for-a-monthly-income-of-11-500-im-64-ive-1-5-million-in-a-401-k-how-do-i-time-my-withdrawals-ae3e6f40 on URL https://www.marketwatch.com/story/were-aiming-for-a-monthly-income-of-11-500-im-64-ive-1-5-million-in-a-401-k-how-do-i-time-my-withdrawals-ae3e6f40] ‘We’re aiming for a monthly income of $1...
  - [not_subject (not in title or first para)] Top Wall Street analysts are bullish on ...
  - [not_subject (not in title or first para)] Europe has the talent and dunding to win...
  - [not_subject (not in title or first para)] The AI economy runs on helium. The Iran ...
  - [not_subject (not in title or first para)] Trump recounts Tim Cook call to 'kiss my...
  - [scrape_error: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.thestreet.com/investing/stocks/bank-of-america-revamps-amd-stock-price-target on URL https://www.thestreet.com/investing/stocks/bank-of-america-revamps-amd-stock-price-target] Bank of America revamps AMD stock price ...
  - [scrape_error: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.thestreet.com/employment/e-commerce-giant-ebay-shuts-down-office-as-layoffs-rise on URL https://www.thestreet.com/employment/e-commerce-giant-ebay-shuts-down-office-as-layoffs-rise] E-commerce giant shuts down office as la...
  - [not_subject (not in title or first para)] Boards say the C-suite owns the AI strat...
  - [not_subject (not in title or first para)] Marvell pops on report it will help Goog...
  - [not_subject (not in title or first para)] Anthropic unveils plans for major UK exp...
  - [not_subject (not in title or first para)] New study says AI is giving bad advice t...
  - [scrape_error: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.thestreet.com/investing/goldman-sachs-spots-a-buying-opportunity-in-bruised-big-tech on URL https://www.thestreet.com/investing/goldman-sachs-spots-a-buying-opportunity-in-bruised-big-tech] Goldman Sachs spots a buying opportunity...
  - [scrape_error: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.thestreet.com/investing/stocks/big-short-michael-burry-sends-signal-on-nvidia-stock on URL https://www.thestreet.com/investing/stocks/big-short-michael-burry-sends-signal-on-nvidia-stock] ‘Big Short’ Michael Burry sends signal o...
  - [not_subject (not in title or first para)] 'You're an idiot': Apollo's Marc Rowan h...
  - [not_subject (not in title or first para)] Feud between AI power startup Fermi and ...
  - [scrape_error: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.thestreet.com/investing/stocks/bank-of-america-resets-apple-stock-forecast on URL https://www.thestreet.com/investing/stocks/bank-of-america-resets-apple-stock-forecast] Bank of America resets Apple stock forec...
  - [boilerplate                             ] Bank of America earnings, Kalshi's DC ch...
  - [not_subject (not in title or first para)] Google Cloud’s next big moment—and what ...
  - [scrape_error: Article `download()` failed with 403 Client Error: Forbidden for url: https://www.thestreet.com/retail/t-mobile-quietly-makes-abrupt-decision-as-customers-depart on URL https://www.thestreet.com/retail/t-mobile-quietly-makes-abrupt-decision-as-customers-depart] T-Mobile quietly makes abrupt move as cu...
  - [boilerplate                             ] Meta Is Sued Over Scam Ads on Facebook a...
  - [not_subject (not in title or first para)] You Need to Be More Freaked Out by Shing...
  - [not_subject (not in title or first para)] AI Could Democratize One of Tech's Most ...
  - [not_subject (not in title or first para)] This Linux distro offers an easy DNS swi...
  - [not_subject (not in title or first para)] FTC reports a surge in $220M job fraud -...
  - [not_subject (not in title or first para)] New MIT jobs report: Why AI's work impac...
  - [not_subject (not in title or first para)] Local vs. Microsoft account in Windows 1...


============================================================
  CONTENT VERIFICATION
============================================================
  Kept articles      : 13
  Total content      : 48,443 chars
  Average per article: 3,726 chars

  Source breakdown:
    Wired                               : 4 articles
    ZDNet                               : 3 articles
    Fortune                             : 2 articles
    CNBC                                : 1 articles
    The Guardian Business               : 1 articles
    Ars Technica                        : 1 articles
    BBC Business                        : 1 articles
============================================================

  ── Article 1 ────────────────────────────────────────────
  Title  : David’s Bridal exec has a warning for every CEO obsessed with AI’s return-on-investment
  Source : Fortune
  Date   : 2026-04-22 19:10
  URL    : https://fortune.com/2026/04/22/davids-bridal-elina-vilk-ai-return-on-i...
  Length : 4,031 chars

  First 500 chars of raw_text:
  --------------------------------------------------
  After years working in marketing positions at tech companies such as PayPal, Hootsuite, and Meta, Elina Vilk admits she wasn’t the most traditional hire for David’s Bridal. But when she came on as chief business officer in 2024, the 76-year-old dress seller was at the precipice of a major strategic shift that would require someone with Vilk’s expertise.

  In 2025, the company launched its “Aisle to Algorithm” program with the goal of turning David’s Bridal into an “asset-light, AI-powered busines
  ... [3,531 more chars]

  ── Article 2 ────────────────────────────────────────────
  Title  : Meta is tracking employee keystrokes on Google, LinkedIn, Wikipedia as part of AI training initiative
  Source : CNBC
  Date   : 2026-04-23 00:18
  URL    : https://www.cnbc.com/2026/04/22/meta-tracks-employee-usage-on-google-l...
  Length : 3,853 chars

  First 500 chars of raw_text:
  --------------------------------------------------
  Mark Zuckerberg, chief executive officer of Meta Platforms Inc., exits Los Angeles Superior Court in Los Angeles, California, US, on Wednesday, Feb. 18, 2026.

  Google , LinkedIn and Wikipedia are among hundreds of websites and apps where Meta plans to capture employee keystrokes and mouse clicks as part of a project to train its artificial intelligence models, according to internal messages viewed by CNBC.

  A new employee tracking tool, dubbed Model Capability Initiative (MCI), allows Meta to ob
  ... [3,353 more chars]

  ── Article 3 ────────────────────────────────────────────
  Title  : Kenyan firm sacks more than 1,000 workers after losing Meta contract
  Source : The Guardian Business
  Date   : 2026-04-17 16:59
  URL    : https://www.theguardian.com/technology/2026/apr/17/kenyan-outsourcing-...
  Length : 2,686 chars

  First 500 chars of raw_text:
  --------------------------------------------------
  More than 1,000 low-paid workers in Kenya have been abruptly sacked by an outsourcing company contracted by Meta, in what activists said was a shocking move exposing the precariousness of tech jobs in the global south.

  Sama, a company based in Nairobi to which Meta outsourced content moderation and AI training work, announced on Thursday that the workers were being laid off after Meta terminated a contract.

  Last month reports said some Kenyan workers involved in data annotation were asked to v
  ... [2,186 more chars]

  ── Article 4 ────────────────────────────────────────────
  Title  : Meta will start tracking employees’ screens and keystrokes to train AI tools
  Source : Fortune
  Date   : 2026-04-21 18:53
  URL    : https://fortune.com/2026/04/21/meta-will-start-tracking-employees-scre...
  Length : 2,311 chars

  First 500 chars of raw_text:
  --------------------------------------------------
  Meta is installing tracking software on U.S. employees’ work computers that will capture mouse movements, clicks, and keystrokes, along with some screenshots to feed the data into its AI training pipeline, according to Reuters.

  The tool, disclosed in a memo to staff this week in a channel belonging to the Meta Superintelligence Labs team, which Reuters saw, will run on a designated list of work apps and websites.

  Per Reuters, the memo framed the effort as a way for rank-and-file employees to i
  ... [1,811 more chars]

  ── Article 5 ────────────────────────────────────────────
  Title  : New Gas-Powered Data Centers Could Emit More Greenhouse Gases Than Entire Nations
  Source : Wired
  Date   : 2026-04-22 10:30
  URL    : https://www.wired.com/story/new-gas-powered-data-centers-could-emit-mo...
  Length : 3,297 chars

  First 500 chars of raw_text:
  --------------------------------------------------
  New gas projects linked to just 11 data center campuses around the US have the potential to create more greenhouse gases than the country of Morocco emitted in 2024. Emissions estimates from air permit documents examined by WIRED show that these natural gas projects—which are being built to power data centers to serve some of the US’s most powerful AI companies, including OpenAI, Meta, Microsoft, and xAI—have the potential to emit more than 129 million tons of greenhouse gases per year.

  As tech
  ... [2,797 more chars]

  ── Article 6 ────────────────────────────────────────────
  Title  : Greenhouse gases from data center boom could outpace entire nations
  Source : Ars Technica
  Date   : 2026-04-23 14:51
  URL    : https://arstechnica.com/ai/2026/04/greenhouse-gases-from-data-center-b...
  Length : 14,909 chars

  First 500 chars of raw_text:
  --------------------------------------------------
  New gas projects linked to just 11 data center campuses around the US have the potential to create more greenhouse gases than the country of Morocco emitted in 2024. Emissions estimates from air permit documents examined by WIRED show that these natural gas projects—which are being built to power data centers to serve some of the US’s most powerful AI companies, including OpenAI, Meta, Microsoft, and xAI—have the potential to emit more than 129 million tons of greenhouse gases per year.

  As tech
  ... [14,409 more chars]

  ── Article 7 ────────────────────────────────────────────
  Title  : Meta’s New AI Asked for My Raw Health Data—and Gave Me Terrible Advice
  Source : Wired
  Date   : 2026-04-10 09:30
  URL    : https://www.wired.com/story/metas-new-ai-asked-for-my-raw-health-data-...
  Length : 2,976 chars

  First 500 chars of raw_text:
  --------------------------------------------------
  Meta’s Superintelligence Labs launched its first generative AI model, called Muse Spark, earlier this week. It is currently available through the Meta AI app, but the company plans to integrate Muse Spark across all of its platforms—including Facebook, Instagram, and WhatsApp—in the coming weeks.

  Meta claims that Muse Spark was designed, in part, to be better at answering questions people have about their health. The company even worked with “over 1,000 physicians to curate training data that e
  ... [2,476 more chars]

  ── Article 8 ────────────────────────────────────────────
  Title  : Meta Is Warned That Facial Recognition Glasses Will Arm Sexual Predators
  Source : Wired
  Date   : 2026-04-13 16:01
  URL    : https://www.wired.com/story/meta-ray-ban-oakley-smart-glasses-no-face-...
  Length : 4,366 chars

  First 500 chars of raw_text:
  --------------------------------------------------
  More than 70 civil liberties, domestic violence, reproductive rights, LGBTQ+, labor, and immigrant advocacy organizations are demanding that Meta abandon plans to deploy face recognition on its Ray-Ban and Oakley smart glasses, warning that the feature—reportedly known inside the company as “Name Tag”—would hand stalkers, abusers, and federal agents the ability to silently identify strangers in public.

  The coalition, which includes the ACLU, the Electronic Privacy Information Center, Fight for
  ... [3,866 more chars]

  ── Article 9 ────────────────────────────────────────────
  Title  : Best Meta Glasses (2026): Ray-Ban, Oakley, AR
  Source : Wired
  Date   : 2026-04-19 11:00
  URL    : https://www.wired.com/story/best-meta-glasses/...
  Length : 2,817 chars

  First 500 chars of raw_text:
  --------------------------------------------------
  Every time I’ve written about Meta’s AI-enabled glasses, I invariably get asked these questions: Why do you even want these? Why do you want smart glasses that can play music or misidentify native flora in a weirdly cheery voice? I am a lifelong Ray-Ban Wayfarer wearer, and I’m also WIRED’s resident Meta wearer. I grab a pair of Meta glasses whenever I leave the house because I like being able to use one device instead of two or three on a walk. With Meta glasses, I can wear sunglasses and worko
  ... [2,317 more chars]

  ── Article 10 ────────────────────────────────────────────
  Title  : Meta says it will cut 8,000 jobs as AI spending soars
  Source : BBC Business
  Date   : 2026-04-23 22:56
  URL    : https://www.bbc.com/news/articles/crm1y89vek8o?at_medium=RSS&at_campai...
  Length : 289 chars

  First 500 chars of raw_text:
  --------------------------------------------------
  A key reason for the layoffs is Meta's increased spending in other areas of the company, including AI, for which it will this year spend $135bn (£100bn). This is roughly equal to the amount it has spent on AI in the previous three years combined, according to a person who viewed the memo.

  ── Article 11 ────────────────────────────────────────────
  Title  : Get a free pair of Meta Ray-Bans with this Verizon Fios Home internet deal - how to redeem it
  Source : ZDNet
  Date   : 2026-04-17 00:30
  URL    : https://www.zdnet.com/home-and-office/networking/meta-ray-bans-smart-g...
  Length : 1,401 chars

  First 500 chars of raw_text:
  --------------------------------------------------
  'ZDNET Recommends': What exactly does it mean?

  ZDNET's recommendations are based on many hours of testing, research, and comparison shopping. We gather data from the best available sources, including vendor and retailer listings as well as other relevant and independent reviews sites. And we pore over customer reviews to find out what matters to real people who already own and use the products and services we’re assessing.

  When you click through from our site to a retailer and buy a product or
  ... [901 more chars]

  ── Article 12 ────────────────────────────────────────────
  Title  : How Flipboard's new Surf app lets you merge social feeds, YouTube, and RSS to escape the algorithm - finally
  Source : ZDNet
  Date   : 2026-04-03 14:24
  URL    : https://www.zdnet.com/article/how-flipboard-surf-merges-social-feeds-y...
  Length : 4,106 chars

  First 500 chars of raw_text:
  --------------------------------------------------
  Elyse Betters Picaro / ZDNET

  Follow ZDNET: Add us as a preferred source on Google.

  ZDNET's key takeaways

  Can a new social network make it? Flipboard Surf has a shot.

  Surf combines social networks with text, video, and audio feeds.

  Think of Surf as the anti-algorithm, anti-AI-slop social network.

  I'll give Flipboard, the once-popular tablet news aggregator site, credit for chutzpah.

  Also: A Meta-powered investment scam is spreading across 25 countries - how to spot (and avoid) it

  After a
  ... [3,606 more chars]

  ── Article 13 ────────────────────────────────────────────
  Title  : Meta is selling refurbished Ray-Bans for as low as $197 right now - but they're going fast
  Source : ZDNet
  Date   : 2026-04-14 14:18
  URL    : https://www.zdnet.com/article/meta-ray-ban-refurbished-smart-glasses-s...
  Length : 1,401 chars

  First 500 chars of raw_text:
  --------------------------------------------------
  'ZDNET Recommends': What exactly does it mean?

  ZDNET's recommendations are based on many hours of testing, research, and comparison shopping. We gather data from the best available sources, including vendor and retailer listings as well as other relevant and independent reviews sites. And we pore over customer reviews to find out what matters to real people who already own and use the products and services we’re assessing.

  When you click through from our site to a retailer and buy a product or
  ... [901 more chars]


============================================================
  DROPPED — REASON BREAKDOWN
============================================================
  not_subject                              : 17 articles
  scrape_error: Article `download          : 9 articles
  boilerplate                              : 2 articles


  df_final : 13 rows × 8 cols
  df_debug : 28 rows × 6 cols

  df_final preview:
   company                                                                                                         title                 source              published_at  char_count  priority

In [45]:
news_final = df_final

In [46]:
news_final = df_final

In [47]:
news_final # final news into a dataframe

,company,title,source,published_at,url,raw_text,char_count,priority
0,Meta,David’s Bridal exec has a warning for every CE...,Fortune,2026-04-22 19:10:30+00:00,https://fortune.com/2026/04/22/davids-bridal-e...,After years working in marketing positions at ...,4031,8
1,Meta,Meta is tracking employee keystrokes on Google...,CNBC,2026-04-23 00:18:18+00:00,https://www.cnbc.com/2026/04/22/meta-tracks-em...,"Mark Zuckerberg, chief executive officer of Me...",3853,9
2,Meta,"Kenyan firm sacks more than 1,000 workers afte...",The Guardian Business,2026-04-17 16:59:04+00:00,https://www.theguardian.com/technology/2026/ap...,"More than 1,000 low-paid workers in Kenya have...",2686,7
3,Meta,Meta will start tracking employees’ screens an...,Fortune,2026-04-21 18:53:46+00:00,https://fortune.com/2026/04/21/meta-will-start...,Meta is installing tracking software on U.S. e...,2311,8
4,Meta,New Gas-Powered Data Centers Could Emit More G...,Wired,2026-04-22 10:30:00+00:00,https://www.wired.com/story/new-gas-powered-da...,New gas projects linked to just 11 data center...,3297,6
5,Meta,Greenhouse gases from data center boom could o...,Ars Technica,2026-04-23 14:51:16+00:00,https://arstechnica.com/ai/2026/04/greenhouse-...,New gas projects linked to just 11 data center...,14909,6
6,Meta,Meta’s New AI Asked for My Raw Health Data—and...,Wired,2026-04-10 09:30:00+00:00,https://www.wired.com/story/metas-new-ai-asked...,Meta’s Superintelligence Labs launched its fir...,2976,6
7,Meta,Meta Is Warned That Facial Recognition Glasses...,Wired,2026-04-13 16:01:30+00:00,https://www.wired.com/story/meta-ray-ban-oakle...,"More than 70 civil liberties, domestic violenc...",4366,6
8,Meta,"Best Meta Glasses (2026): Ray-Ban, Oakley, AR",Wired,2026-04-19 11:00:00+00:00,https://www.wired.com/story/best-meta-glasses/,Every time I’ve written about Meta’s AI-enable...,2817,6
9,Meta,"Meta says it will cut 8,000 jobs as AI spendin...",BBC Business,2026-04-23 22:56:00+00:00,https://www.bbc.com/news/articles/crm1y89vek8o...,A key reason for the layoffs is Meta's increas...,289,3
10,Meta,Get a free pair of Meta Ray-Bans with this Ver...,ZDNet,2026-04-17 00:30:37+00:00,https://www.zdnet.com/home-and-office/networki...,'ZDNET Recommends': What exactly does it mean?...,1401,5
11,Meta,How Flipboard's new Surf app lets you merge so...,ZDNet,2026-04-03 14:24:01+00:00,https://www.zdnet.com/article/how-flipboard-su...,Elyse Betters Picaro / ZDNET\n\nFollow ZDNET: ...,4106,5
12,Meta,Meta is selling refurbished Ray-Bans for as lo...,ZDNet,2026-04-14 14:18:12+00:00,https://www.zdnet.com/article/meta-ray-ban-ref...,'ZDNET Recommends': What exactly does it mean?...,1401,5

#For Getting past 4 quarters of earning report:
#please change the company_name and ticker to extract past 4 earning reports. 
#please also change the set_identity email to your email. this is just guideline from SEC that they want to know which email is retrieving the data. s

In [11]:
import pandas as pd
from edgar import Company, set_identity

# ── Set identity (required by SEC) ───────────────────────────────
set_identity("spso771522@gmail.com")

# ============================================================
# ★  CONFIG
# ============================================================
TICKER       = "AAPL"       # stock ticker
COMPANY_NAME = "Apple"  # company name
MAX_EARNINGS = 4            # number of quarters to pull
MAX_SCAN     = 30           # max 8-K filings to scan through
# ============================================================

# ─── 1. Extract text from filing object ──────────────────────────
def extract_text_from_filing(filing_obj) -> str:
    """Try multiple methods to get text from a filing object."""

    # method 1 — press release text (best for 8-K earnings)
    try:
        prs = filing_obj.press_releases
        if prs and len(prs) > 0:
            pr = prs[0]
            for attr in ["text", "markdown", "content", "html"]:
                if hasattr(pr, attr):
                    val = getattr(pr, attr)
                    if callable(val):
                        try:
                            result = val()
                            if isinstance(result, str) and len(result) > 200:
                                return result[:50000]
                        except Exception:
                            pass
                    elif isinstance(val, str) and len(val) > 200:
                        return val[:50000]
    except Exception:
        pass

    # method 2 — filing .text() method
    try:
        text = filing_obj.text()
        if isinstance(text, str) and len(text) > 200:
            return text[:50000]
    except Exception:
        pass

    # method 3 — filing .markdown() method
    try:
        text = filing_obj.markdown()
        if isinstance(text, str) and len(text) > 200:
            return text[:50000]
    except Exception:
        pass

    # method 4 — str conversion fallback
    try:
        text = str(filing_obj)
        if len(text) > 200:
            return text[:50000]
    except Exception:
        pass

    return ""

# ─── 2. Check if 8-K is an earnings filing ───────────────────────
def is_earnings_filing(filing_obj) -> bool:
    """Check if this 8-K contains earnings results (Item 2.02)."""

    # check items list
    try:
        items = filing_obj.items
        if any("2.02" in str(item) for item in items):
            return True
    except Exception:
        pass

    # check string representation
    try:
        filing_str = str(filing_obj).lower()
        if any(kw in filing_str for kw in [
            "2.02", "results of operations",
            "quarterly results", "financial results",
            "earnings per share", "revenue was"
        ]):
            return True
    except Exception:
        pass

    return False

# ─── 3. Pull 4 quarters of earnings 8-K ──────────────────────────
def get_earnings_filings(ticker: str) -> pd.DataFrame:
    """
    Pull last MAX_EARNINGS earnings 8-K press releases.
    Takes full press release text for proper chunking.
    Returns df_edgar DataFrame.
    """
    print(f"\n{'='*60}")
    print(f"  EDGAR EARNINGS COLLECTION — {ticker}")
    print(f"  Target: last {MAX_EARNINGS} earnings quarters")
    print(f"{'='*60}")

    # get company
    print(f"\n  Loading {ticker}...")
    company = Company(ticker)
    print(f"  ✓ Found: {company.name}")

    # get 8-K filings
    print(f"\n  Fetching 8-K filings (scanning up to {MAX_SCAN})...")
    filings = company.get_filings(form="8-K").head(MAX_SCAN)

    results = []

    for filing in filings:
        try:
            filing_date = str(filing.filing_date)
            obj         = filing.obj()

            # check if earnings
            if not is_earnings_filing(obj):
                continue

            # get full text
            text = extract_text_from_filing(obj)

            if not text or len(text.strip()) < 200:
                print(f"  ✗ No text found  : {filing_date}")
                continue

            results.append({
                "ticker":       ticker.upper(),
                "company":      COMPANY_NAME,
                "section_type": "8-K earnings",
                "filing_type":  "8-K",
                "filing_date":  filing_date,
                "text":         text.strip(),
            })

            print(f"  ✓ {filing_date} : {len(text):,} chars")

            if len(results) >= MAX_EARNINGS:
                print(f"\n  ✓ Collected {MAX_EARNINGS} quarters")
                break

        except Exception as e:
            print(f"  Skipping {filing.filing_date}: {e}")

    # ── Summary ───────────────────────────────────────────────────
    if not results:
        print(f"\n  ✗ No earnings 8-K found for {ticker}")
        return pd.DataFrame()

    df_edgar = pd.DataFrame(results)

    print(f"\n{'='*60}")
    print(f"  EARNINGS COLLECTION SUMMARY")
    print(f"{'='*60}")
    print(f"  Quarters collected : {len(df_edgar)}")
    print(f"\n  By filing date:")
    for _, row in df_edgar.iterrows():
        print(f"    {row['filing_date']} : {len(row['text']):,} chars")
    print(f"{'='*60}\n")

    return df_edgar

# ============================================================
# ★  RUN
# ============================================================

df_edgar = get_earnings_filings(TICKER)

if len(df_edgar) > 0:
    print(f"✓ df_edgar ready : {len(df_edgar)} earnings quarters")
    print(f"\n  Preview:")
    print(df_edgar[["ticker", "company", "filing_date",
                    "filing_type"]].to_string())
    print(f"\n  Text lengths:")
    for _, row in df_edgar.iterrows():
        print(f"    {row['filing_date']} : {len(row['text']):,} chars")
    print(f"\n  NEXT STEP: run chunking cell")
else:
    print(f"✗ No earnings data collected for {TICKER}")

21:52:35  INFO      Identity of the Edgar REST client set to [spso771522@gmail.com]

============================================================
  EDGAR EARNINGS COLLECTION — AAPL
  Target: last 4 earnings quarters
============================================================

  Loading AAPL...
  ✓ Found: Apple Inc.

  Fetching 8-K filings (scanning up to 30)...

21:52:35  INFO      Pattern detection successful: 1 sections found
21:52:35  INFO      Pattern detection successful: 2 sections found
21:52:36  INFO      Pattern detection successful: 2 sections found

  ✓ 2026-01-29 : 24,031 chars

21:52:36  INFO      Pattern detection successful: 1 sections found
21:52:36  INFO      Pattern detection successful: 1 sections found
21:52:37  INFO      Pattern detection successful: 2 sections found
21:52:37  INFO      Pattern detection successful: 2 sections found

  ✓ 2025-10-30 : 31,524 chars
  ✓ 2025-07-31 : 25,826 chars

21:52:38  INFO      Pattern detection successful: 1 sections found
21:52:38  INFO      Pattern detection successful: 1 sections found
21:52:38  INFO      Pattern detection successful: 2 sections found
21:52:39  INFO      Pattern detection successful: 2 sections found

  ✓ 2025-05-01 : 26,119 chars

  ✓ Collected 4 quarters

============================================================
  EARNINGS COLLECTION SUMMARY
============================================================
  Quarters collected : 4

  By filing date:
    2026-01-29 : 24,023 chars
    2025-10-30 : 31,521 chars
    2025-07-31 : 25,820 chars
    2025-05-01 : 26,112 chars
============================================================

✓ df_edgar ready : 4 earnings quarters

  Preview:
  ticker company filing_date filing_type
0   AAPL   Apple  2026-01-29         8-K
1   AAPL   Apple  2025-10-30         8-K
2   AAPL   Apple  2025-07-31         8-K
3   AAPL   Apple  2025-05-01         8-K

  Text lengths:
    2026-01-29 : 24,023 chars
    2025-10-30 : 31,521 chars
    2025-07-31 : 25,820 chars
    2025-05-01 : 26,112 chars

  NEXT STEP: run chunking cell

In [12]:
#four elements as inputs. to be combined. 
df_edgar

,ticker,company,section_type,filing_type,filing_date,text
0,AAPL,Apple,8-K earnings,8-K,2026-01-29,Document\n\nExhibit 99.1\nApple reports first ...
1,AAPL,Apple,8-K earnings,8-K,2025-10-30,Document\n\nExhibit 99.1\nApple reports fourth...
2,AAPL,Apple,8-K earnings,8-K,2025-07-31,Document\n\nExhibit 99.1\nApple reports third ...
3,AAPL,Apple,8-K earnings,8-K,2025-05-01,Document\n\nExhibit 99.1\nApple reports second...

In [13]:
#lets take out the risk for now? 
mda_text

NameError: name 'mda_text' is not defined

In [14]:
tenk.risk_factors

NameError: name 'tenk' is not defined

In [15]:
news_final

,company,title,source,published_at,url,raw_text,char_count,priority
0,Apple,Steve Jobs called Tim Cook ‘not a product pers...,Fortune,2026-04-22 13:42:03+00:00,https://fortune.com/2026/04/22/tim-cook-retiri...,Tim Cook and Steve Jobs couldn’t have been mor...,3723,8
1,Apple,"Here’s what Warren Buffett, Sam Altman, Donald...",Fortune,2026-04-21 16:35:02+00:00,https://fortune.com/2026/04/21/warren-buffett-...,Apple is entering a new era. The company annou...,4296,8
2,Apple,Tim Cook is exceptional at this leadership ski...,CNBC,2026-04-22 12:55:32+00:00,https://www.cnbc.com/2026/04/22/tim-cook-is-ex...,"Apple CEO Tim Cook speaks during Apple's ""Awe-...",6087,9
3,Apple,"John Ternus, the man stepping into Tim Cook an...",Fortune,2026-04-21 16:26:54+00:00,https://fortune.com/2026/04/21/who-is-john-ter...,Apple’s next CEO John Ternus is a company vete...,4633,8
4,Apple,Apple is slipping on Tim Cook’s exit. Wall Str...,Fortune,2026-04-21 15:57:16+00:00,https://fortune.com/2026/04/21/apple-stock-sli...,Tim Cook is handing Apple to its hardware chie...,3140,8
5,Apple,New Apple CEO John Ternus doubted himself when...,CNBC,2026-04-21 16:12:31+00:00,https://www.cnbc.com/2026/04/21/john-ternus-ap...,Apple is adding a new CEO to its ranks and con...,1477,9
6,Apple,Tim Cook turned Apple into a $4 trillion jugge...,CNBC,2026-04-21 15:14:19+00:00,https://www.cnbc.com/2026/04/21/tim-cook-apple...,In this article AAPL Follow your favorite stoc...,8996,9
7,Apple,Apple just named its next CEO—and Tim Cook is ...,Fortune,2026-04-21 15:14:13+00:00,https://fortune.com/2026/04/21/apple-next-ceo-...,"Apple just named its next CEO, who will be tak...",4651,8
8,Apple,A new generation is reviving the iPod for dist...,Associated Press,2026-04-13 07:05:46+00:00,https://apnews.com/article/ipod-music-streamin...,Add AP News as your preferred source to see mo...,7525,10
9,Apple,"Who is John Ternus, Apple’s next CEO?",The Guardian Tech,2026-04-21 01:48:37+00:00,https://www.theguardian.com/technology/2026/ap...,Apple has announced longtime company veteran J...,3142,7
10,Apple,"Trump recounts Tim Cook call to 'kiss my ass,'...",CNBC,2026-04-21 21:04:19+00:00,https://www.cnbc.com/2026/04/21/trump-tim-cook...,In this article AAPL Follow your favorite stoc...,9973,9
11,Apple,Apple’s Tim Cook leaves behind complicated leg...,The Guardian Tech,2026-04-21 23:31:42+00:00,https://www.theguardian.com/technology/2026/ap...,"In his 15 years as Apple’s top executive, Tim ...",7060,7
12,Apple,Four key takeaways from Apple’s change of lead...,The Guardian Business,2026-04-21 18:24:49+00:00,https://www.theguardian.com/global/2026/apr/21...,1. Fix the AI strategy Artificial intelligence...,3488,7
13,Apple,Jim Cramer says Tim Cook accomplished somethin...,CNBC,2026-04-21 23:00:01+00:00,https://www.cnbc.com/2026/04/21/cramer-tim-coo...,CNBC's Jim Cramer on Tuesday reflected on the ...,2343,9
14,Apple,Apple incoming CEO John Ternus faces a definin...,CNBC,2026-04-21 05:09:27+00:00,https://www.cnbc.com/2026/04/20/apple-new-ceo-...,Apple has maintained its dominance in consumer...,2425,9
15,Apple,Apple's elevation of silicon head Johny Srouji...,CNBC,2026-04-21 22:08:12+00:00,https://www.cnbc.com/2026/04/21/apple-promotes...,In this article AAPL Follow your favorite stoc...,7761,9
16,Apple,"Fifteen years after Steve Jobs, Tim Cook leave...",The Guardian Tech,2026-04-21 01:29:36+00:00,https://www.theguardian.com/technology/2026/ap...,"After 15 years, Tim Cook is stepping down as A...",5500,7
17,Apple,MacBook Air M5 review: Apple’s best consumer l...,The Guardian Tech,2026-04-15 06:00:01+00:00,https://www.theguardian.com/technology/2026/ap...,Apple’s latest MacBook Air is its most powerfu...,5504,7
18,Apple,"Apple’s Next Chapter, SpaceX and Cursor Strike...",Wired Business,2026-04-23 19:26:11+00:00,https://www.wired.com/story/uncanny-valley-pod...,Brian Barrett: In terms of making things happe...,4096,6
19,Apple,Apple’s Cal AI crackdown signals it’s still po...,TechCrunch,2026-04-21 19:09:12+00:00,https://techcrunch.com/2026/04/21/apples-cal-a...,Apple’s recent crackdown on the MyFitnessPal-o...,3774,6
20,Apple,Apple fixes bug that cops used to extract dele...,TechCrunch,2026-04-22 19:13:02+00:00,https://techcrunch.com/2026/04/22/apple-fixes-...,Apple released a software update on Wednesday ...,2418,6
21,Apple,"Who is John Ternus, the incoming Apple CEO?",TechCrunch,2026-04-21 01:02:04+00:00,https://techcrunch.com/2026/04/20/who-is-john-...,"After 15 years, Tim Cook will hand off the App...",5732,6
22,Apple,Tim Cook is stepping down as CEO of Apple. Her...,TechCrunch,2026-04-21 21:09:09+00:00,https://techcrunch.com/2026/04/21/apple-tim-co...,"After 15 years at the helm, Tim Cook is steppi...",6518,6
23,Apple,Tim Cook's Legacy Is Turning Apple Into a Subs...,Wired,2026-04-21 17:35:12+00:00,https://www.wired.com/story/apple-tim-cook-sub...,"Tim Cook’s tenure as CEO at Apple, which is co...",4078,6
24,Apple,Apple CEO Tim Cook Is Stepping Down,Wired,2026-04-20 21:02:18+00:00,https://www.wired.com/story/tim-cook-stepping-...,Tim Cook is stepping down as the CEO of Apple ...,3768,6
25,Apple,Apple stops weirdly storing data that let cops...,Ars Technica,2026-04-23 16:37:23+00:00,https://arstechnica.com/tech-policy/2026/04/ap...,Apple fixed a security bug that made it possib...,1968,6
26,Apple,Our Favorite Apple Watch Has Never Been Less E...,Wired,2026-04-19 09:39:00+00:00,https://www.wired.com/story/apple-watch-series...,The Apple Watch Series 11 is a smartwatch wort...,1847,6
27,Apple,"The App Store is booming again, and AI may be why",TechCrunch,2026-04-18 13:00:00+00:00,https://techcrunch.com/2026/04/18/the-app-stor...,"Everyone said AI would kill apps. Instead, new...",4538,6
28,Apple,A look at Tim Cook’s 15-year legacy as CEO of ...,TechCrunch,2026-04-21 17:40:20+00:00,https://techcrunch.com/2026/04/21/apple-tim-co...,"After 15 years at the helm, Tim Cook is steppi...",6518,6
29,Apple,Why Amazon Is Buying Globalstar—and What It Me...,Wired,2026-04-15 16:19:40+00:00,https://www.wired.com/story/why-amazon-is-buyi...,"On Tuesday, Amazon announced it would be acqui...",4988,6
30,Apple,How vibe coding app Anything is rebuilding aft...,TechCrunch,2026-04-14 14:22:44+00:00,https://techcrunch.com/2026/04/14/how-vibe-cod...,Apple is taking a tough stance on vibe-coding ...,3753,6
31,Apple,5 Apple products explain my optimism for John ...,ZDNet,2026-04-21 17:30:40+00:00,https://www.zdnet.com/article/5-apple-products...,Bloomberg/Getty Images\n\nFollow ZDNET: Add us...,6364,5
32,Apple,This free app makes journaling so easy that I'...,ZDNet,2026-04-21 16:17:00+00:00,https://www.zdnet.com/article/diarly-journalin...,Jack Wallen/ZDNET\n\nFollow ZDNET: Add us as a...,5097,5
33,Apple,There's a right way to wear your Apple Watch -...,ZDNet,2026-04-20 16:28:00+00:00,https://www.zdnet.com/article/why-you-should-w...,Nina Raemont/ZDNET\n\nFollow ZDNET: Add us as ...,2627,5

In [16]:
mda_text

NameError: name 'mda_text' is not defined

In [ ]:
#getting risk data

In [17]:
import os
from edgar import set_identity, Company

# Set identity (still required!)
set_identity("Sang Park spso771522@gmail.com")
# Get company financials
financials = Company("MSFT").get_financials()
#First version of NLP:
#getting the risk factors from 10-K April 18th
from edgar import Company
company = Company("MSFT")            # or any ticker
filing = company.get_filings(form="10-K").latest()
tenk = filing.obj()
risk_text = tenk.risk_factors
print(risk_text)
risk_text
#First step: getting the second risk factor (Item 1)
from edgar import Company
company = Company("MSFT")
filings = company.get_filings(form="10-K").head(3)
for filing in filings:
    tenk = filing.obj()
    print("=" * 80)
    print(f"{filing.company} | {filing.filing_date} | {filing.form}")
    print(tenk.risk_factors[:3000])   # first 3000 chars
#the U.S. Securities and Exchange Commission (SEC), specifically:
#Form 10-K → annual report (most comprehensive filing)

21:53:02  INFO      Identity of the Edgar REST client set to [Sang Park spso771522@gmail.com]
21:53:11  INFO      TOC detection found 23 sections
21:53:11  INFO      TOC detection successful: 23 sections found

ITEM 1A. RISK FACTORS

Our operations and financial results are subject to various risks and uncertainties, including those described below, that could adversely affect our business, operations, financial condition, results of operations, liquidity, and the trading price of our common stock.

STRATEGIC AND COMPETITIVE RISKS

We face intense competition across all markets for our products and services, which could adversely affect our results of operations.

Competition in the technology sector

Our competitors range in size from diversified global companies with significant research and development resources to small, specialized firms whose narrower product lines may let them be more effective in deploying technical, marketing, and financial resources. Barriers to entry in many of our businesses are low and many of the areas in which we compete evolve rapidly with changing and disruptive technologies, shifting user needs, and frequent introductions of new products and services. If we do not continue to innovate and provide products, devices, and services that appeal to businesses and consumers, we may not remain competitive, which could adversely affect our business, financial condition, and results of operations.

Competition among platform-based ecosystems

An important element of our business model has been to create platform-based ecosystems on which many participants can build diverse solutions. A well-established ecosystem creates beneficial network effects among users, application developers, and the platform provider that can accelerate growth. Establishing significant scale in the marketplace is necessary to meet consumer demand and to achieve and maintain attractive margins. We face significant competition from firms that provide competing platforms.

•A competing vertically-integrated model, in which a single firm controls the hardware and software elements of a product and related services, has succeeded with some consumer products such as PCs, tablets, smartphones, gaming consoles, wearables, and other endpoint devices. Competitors pursuing this model also earn revenue from services integrated with the hardware and software platform, including applications and content sold through their integrated marketplaces. They may also be able to claim security and performance benefits from their vertically-integrated offer. We also offer some vertically-integrated hardware and software products and services. Shifting a portion of our business to a vertically-integrated model may increase our cost of revenue and reduce our operating margins.

•We derive substantial revenue from licenses of Windows operating systems on PCs. We face significant competition from competing platforms developed for new devices and form factors such as smartphones and tablets. These devices compete on multiple bases including price and the perceived utility of the device and its platform. Users continue to turn to these devices to perform functions that in the past were performed by PCs. Even if many users view these devices as complementary to a PC, the prevalence of these devices may make it more difficult to attract application developers to our PC operating system platforms. Competing with operating systems licensed at low or no cost may decrease our PC operating system margins. Popular products or services offered on competing platforms could increase their competitive strength. In addition, some of our devices compete with products made by our OEM partners, which may affect their commitment to our platform.

•Competing platforms have content and application marketplaces with scale and significant installed bases. The variety and utility of content and applications available on a platform are important to device purchasing decisions. Users may incur costs to move data and buy new content and applications when switching platforms. To compete, we must successfully enlist developers to write applications for our platform and ensure that these applications have high quality, security, customer appeal, and value. Efforts to compete with competitors’ content and application marketplaces may increase our cost of revenue and lower our operating margins. Competitors’ rules governing their content and applications marketplaces may restrict our ability to distribute products and services through them in accordance with our technical and business model objectives.

For all of these reasons, we may not be able to compete successfully against our current and future competitors, which could adversely affect our business, operations, financial condition, and results of operations.

  Business model competition

Companies compete with us based on a growing variety of business models.

•A material part of our business involves cloud-based services available across the spectrum of computing devices. We and our competitors continue to devote significant resources to developing and deploying cloud-based strategies and services for consumers and business customers, and pricing and delivery models are evolving.

•We are investing in artificial intelligence (“AI”) across the entire company and infusing generative AI capabilities into our consumer and commercial offerings. AI technology and services are a highly competitive and rapidly evolving market, and new competitors continue to enter the market. We will bear significant development and operational costs to build and support the AI models, services, platforms, and infrastructure necessary to meet the needs of our customers. To compete effectively we must also be responsive to technological change, new and potential regulatory developments, and public scrutiny.

•Even as we transition more of our business to infrastructure-, platform-, and software-as-a-service business models, the license-based proprietary software model generates a substantial portion of our software revenue. We bear the costs of converting original ideas into software products through investments in research and development, offsetting these costs with the revenue received from licensing our products. Many of our competitors also develop and sell software to businesses and consumers under this model.

•Other competitors develop and offer free applications, online services, and content, and make money by selling third-party advertising. Advertising revenue funds development of products and services these competitors provide to users at little or no cost, competing directly with our revenue-generating products.

•Some companies compete with us by modifying and then distributing open source software at little or no cost to end users, developing, making available, or using AI models that are open, and earning revenue on advertising or integrated products and services. These firms do not bear the full costs of research and development for the open source products. Some open source products mimic the features and functionality of our products.

The competitive pressures described above may cause decreased sales volumes, price reductions, and/or increased operating costs, such as for research and development, marketing, and sales incentives, which could adversely affect our financial condition and results of operations.

Our focus on cloud-based and AI services presents execution and competitive risks. We are incurring significant costs to build and maintain infrastructure to support cloud-based and AI services, reducing operating margins. Whether we succeed in cloud-based and AI services depends on our execution in several areas, including:

•Continuing to bring to market compelling cloud-based and AI services and products that generate increasing traffic and market share.

•Maintaining the utility, compatibility, and performance of our cloud-based and AI services on the growing array of computing devices, including PCs, smartphones, tablets, gaming consoles, and other devices.

•Continuing to enhance the attractiveness of our cloud platforms to third-party developers.

•Ensuring our cloud-based services meet the reliability expectations and specific requirements of our customers and maintain the security of their data as well as help them meet their own compliance needs.

•Making our suite of cloud-based services platform-agnostic, available on a wide range of devices and ecosystems, including those of our competitors.

It is uncertain whether our strategies will continue to attract users or generate the revenue required to succeed. If we are not effective in executing organizational and technical changes to increase efficiency and accelerate innovation, or if we fail to generate sufficient usage of our new products and services, we may not grow revenue in line with the infrastructure and development investments described above. This could adversely affect our operations, financial condition, and results of operations.

  Our AI systems offer users powerful tools and capabilities. However, there may be instances where these systems are used in ways that are unintended or inappropriate. In addition, some users may also engage in fraudulent or abusive activities through our cloud-based and AI services, such as unauthorized account access, payment fraud, or terms of service violations including cryptocurrency mining or launching cyberattacks. While we are committed to detecting and controlling such misuse of our cloud-based and AI services, our efforts may not be effective, and we may incur reputational damage or experience adverse impacts to our business and results of operations.

RISKS RELATING TO THE EVOLUTION OF OUR BUSINESS

We make significant investments in products and services that may not achieve expected returns. We will continue to make significant investments in research, development, and marketing for existing products, services, and technologies, including AI-based products and services. We also invest in the development and acquisition of a variety of hardware for productivity, communication, and entertainment, including PCs, tablets, and gaming devices. Investments in new technology are speculative. Commercial success depends on many factors, including innovation, developer support, and effective distribution and marketing. If customers do not perceive our latest offerings as providing significant new functionality or other value, they may reduce their purchases of new software and hardware products or upgrades, unfavorably affecting revenue. We may not achieve significant revenue from new product, service, and distribution channel investments for several years, if at all. New products and services may not be profitable or may not achieve operating margins as high as we have experienced historically. We may not get engagement in certain features that drive post-sale monetization opportunities. Our data-handling practices across our products and services will continue to be under scrutiny. Perceptions of mismanagement, driven by regulatory activity or negative public reaction to our practices or product experiences, could negatively impact product and feature adoption. Developing new technologies is complex. It can require long development and testing periods. We could experience significant delays in new releases or significant problems in creating new products or services. These factors could adversely affect our business, financial condition, and results of operations.

Acquisitions, joint ventures, and strategic alliances could have an adverse effect on our business. We expect to continue making acquisitions and entering into joint ventures and strategic alliances as part of our long-term business strategy. For example, in October 2023 we completed our acquisition of Activision Blizzard, Inc. (“Activision Blizzard”). In January 2023 we announced the third phase of our OpenAI strategic partnership. Acquisitions and other transactions and arrangements involve significant challenges and risks, including that they do not advance our business strategy, that we get an unsatisfactory return on our investment, that they raise new compliance-related obligations and challenges, that we have difficulty integrating and retaining new employees, business systems, and technology, that they distract management from our other businesses, or that announced transactions may not be completed. If an arrangement fails to adequately anticipate changing circumstances and interests of a party, it may result in early termination or renegotiation of the arrangement. We also have limited ability to control or influence third parties with whom we have arrangements, which may impact our ability to realize the anticipated benefits. The success of these transactions and arrangements depend in part on our ability to leverage them to enhance our existing products and services or develop compelling new ones, as well as the acquired companies’ ability to meet our policies and processes in areas such as data governance, privacy, digital safety, responsible AI, and cybersecurity. It may take longer than expected to realize the full economic benefits from these transactions and arrangements, such as increased revenue or enhanced efficiencies, or the benefits may ultimately be smaller than we expected, which could cause an impairment of goodwill or intangibles. We have recorded, and may in the future be required to record, a significant charge in our consolidated financial statements during the period in which any impairment of our goodwill or amortizable intangible assets is determined, negatively affecting our results of operations. In addition, an acquisition may be subject to challenge even after it has been completed. These events could adversely affect our business, operations, financial condition, and results of operations.

  CYBERSECURITY, DATA PRIVACY, AND PLATFORM ABUSE RISKS

Cyberattacks and security vulnerabilities could lead to reduced revenue, increased costs, liability claims, or harm to our reputation or competitive position.

Security of our information technology

Threats to security can take a variety of forms. Threat actors, including individual and groups of hackers and sophisticated organizations, including nation-states, state-sponsored organizations, or cybercriminal groups, continuously undertake attacks that pose threats to our customers and our internal infrastructure, and we have experienced cybersecurity incidents in which such actors have gained unauthorized access to our systems and data, including customer systems and data. These actors use a wide variety of methods, which include developing and deploying malicious software; exploiting known and potential vulnerabilities or intentionally designed processes in our or third-party hardware, software, or other infrastructure to attack our products and services or gain access to our networks and datacenters; using social engineering techniques to induce our employees, users, partners, or customers to disclose sensitive information, such as passwords, or take other actions to gain access to our data or our users’ or customers’ data; or acting in a coordinated manner or conducting coordinated attacks. For example, as previously disclosed in our Form 8-K filed with the Securities and Exchange Commission on January 19, 2024 and amended on March 8, 2024, beginning in late November 2023, a nation-state associated threat actor used a password spray attack to compromise a legacy test account and, in turn, gain access to Microsoft email accounts. The threat actor used information it obtained to gain unauthorized access to some of our source code repositories and internal systems, and the threat actor could continue to utilize this and other information to attempt to gain access to our systems or otherwise adversely affect our business and results of operations. This incident has and may continue to result in harm to our reputation and customer relationships. Nation-state and state-sponsored actors can sustain malicious activities for extended periods and deploy significant resources to plan and carry out attacks. Nation-state attacks against us, our customers, or our partners have and may continue to intensify due to our transparency to our customers, other stakeholders, and the public about cyberattacks, and during elections or periods of intense diplomatic or armed conflict. Challenges or failures in applying security patches to all hardware and devices connected to our systems, including end-of-life and end-of-support equipment, have and may continue to result in unauthorized access to our systems and data in the future. Cyber incidents and attacks, individually or in the aggregate, could adversely affect our financial condition, results of operations, competitive position, and reputation, or expose us to legal or regulatory risk.

Inadequate account security or organizational security practices, including those of companies we have acquired or those of the third parties we utilize, have resulted and may result in unauthorized access to our systems and data, including customer systems and data. For example, passwords may not be rotated and employee access may not be updated or removed on a timely basis. Employees or third parties may intentionally compromise our or our users’ security or systems or reveal confidential information, and laws in foreign jurisdictions may compel actions by such parties against our interests and could limit our recourse. Malicious actors may employ the supply chain to introduce malware through software updates or compromised supplier accounts or hardware.

Cyberthreats are constantly evolving and becoming increasingly sophisticated and complex, increasing the difficulty of detecting and successfully defending against them. Threat actors may also utilize emerging technologies, such as AI and machine learning. Our current capabilities may not detect certain vulnerabilities or new attack methods, which may allow them to persist in the environment over long periods of time. It may be difficult to determine the best way to investigate, mitigate, contain, and remediate the harm caused by a cyber incident. Such efforts may not be successful, and we may make errors or fail to take necessary actions. It is possible that threat actors may gain undetected access to other networks and systems after establishing a foothold on an internal system. Cyber incidents and attacks can have cascading impacts that unfold with increasing speed across our internal networks and systems, as well as those of our partners and customers. In addition, it may take considerable time for us to investigate and evaluate the full impact of incidents, particularly for sophisticated attacks. As a result of these and other factors, we may not be able to provide prompt, full, and reliable information about the incident to our customers, partners, regulators, and the public. Breaches of our facilities, network, or data security can disrupt the security of our systems and business applications, impair our ability to provide services to our customers and protect the privacy of their data, result in product development delays, compromise confidential or technical business information, result in theft or misuse of our intellectual property or other assets, subject us to ransomware attacks, require us to allocate more resources to improve technologies or remediate the impacts of attacks, or otherwise adversely affect our business. In addition, actions taken to remediate an incident could result in outages, data losses, and disruptions of our services.


21:53:20  INFO      TOC detection found 23 sections
21:53:20  INFO      TOC detection successful: 23 sections found

ITEM 1A. RISK FACTORS

Our operations and financial results are subject to various risks and uncertainties, including those described below, that could adversely affect our business, operations, financial condition, results of operations, liquidity, and the trading price of our common stock.

STRATEGIC AND COMPETITIVE RISKS

We face intense competition across all markets for our products and services, which could adversely affect our results of operations.

Competition in the technology sector

Our competitors range in size from diversified global companies with significant research and development resources to small, specialized firms whose narrower product lines may let them be more effective in deploying technical, marketing, and financial resources. Barriers to entry in many of our businesses are low and many of the areas in which we compete evolve rapidly with changing and disruptive technologies, shifting user needs, and frequent introductions of new products and services. If we do not continue to innovate and provide products, devices, and services that appeal to businesses and consumers, we may not remain competitive, which could adversely affect our business, financial condition, and results of operations.

Competition among platform-based ecosystems

An important element of our business model has been to create platform-based ecosystems on which many participants can build diverse solutions. A well-established ecosystem creates beneficial network effects among users, application developers, and the platform provider that can accelerate growth. Establishing significant scale in the marketplace is necessary to meet consumer demand and to achieve and maintain attractive margins. We face significant competition from firms that provide competing platforms.

•A competing vertically-integrated model, in which a single firm controls the hardware and software elements of a product and related services, has succeeded with some consumer products such as PCs, tablets, smartphones, gaming consoles, wearables, and other endpoint devices. Competitors pursuing this model also earn revenue from services integrated with the hardware and software platform, including applications and content sold through their integrated marketplaces. They may also be able to claim security and performance benefits from their vertically-integrated offer. We also offer some vertically-integrated hardware and software products and services. Shifting a portion of our business to a vertically-integrated model may increase our cost of revenue and reduce our operating margins.

•We derive substantial revenue from licenses of Windows operating systems on PCs. We face significant competition from competing platforms developed for new devices and form factors such as smartphones and tablets. These devices compete on multiple bases including price and the perceived utility of the device and its platform. Users continue to turn to these devices to perform functions that in the past w
================================================================================
MICROSOFT CORP | 2024-07-30 | 10-K

21:53:28  INFO      TOC detection found 23 sections
21:53:28  INFO      TOC detection successful: 23 sections found

ITEM 1A. RISK FACTORS

  Our operations and financial results are subject to various risks and uncertainties, including those described below, that could adversely affect our business, operations, financial condition, results of operations, liquidity, and the trading price of our common stock.

  STRATEGIC AND COMPETITIVE RISKS

  We face intense competition across all markets for our products and services, which may adversely affect our results of operations.

  Competition in the technology sector

  Our competitors range in size from diversified global companies with significant research and development resources to small, specialized firms whose narrower product lines may let them be more effective in deploying technical, marketing, and financial resources. Barriers to entry in many of our businesses are low and many of the areas in which we compete evolve rapidly with changing and disruptive technologies, shifting user needs, and frequent introductions of new products and services. If we do not continue to innovate and provide products, devices, and services that appeal to businesses and consumers, we may not remain competitive, which may adversely affect our business, financial condition, and results of operations.

  Competition among platform-based ecosystems

  An important element of our business model has been to create platform-based ecosystems on which many participants can build diverse solutions. A well-established ecosystem creates beneficial network effects among users, application developers, and the platform provider that can accelerate growth. Establishing significant scale in the marketplace is necessary to achieve and maintain attractive margins. We face significant competition from firms that provide competing platforms.

  •A competing vertically-integrated model, in which a single firm controls the software and hardware elements of a product and related services, has succeeded with some consumer products such as PCs, tablets, smartphones, gaming consoles, wearables, and other endpoint devices. Competitors pursuing this model also earn revenue from services integrated with the hardware and software platform, including applications and content sold through their integrated marketplaces. They may also be able to claim security and performance benefits from their vertically integrated offer. We also offer some vertically-integrated hardware and software products and services. Shifting a portion of our business to a vertically integrated model may increase our cost of revenue and reduce our operating margins.

  •We derive substantial revenue from licenses of Windows operating systems on PCs. We face significant competition from competing platforms developed for new devices and form factors such as smartphones and tablets. These devices compete on multiple bases including price and the perceived utility of the device and its platform. Users continue to turn to these devices to perform functions that in the past were performed
================================================================================
MICROSOFT CORP | 2023-07-27 | 10-K

21:53:37  INFO      TOC detection found 22 sections
21:53:37  INFO      TOC detection successful: 22 sections found

ITEM 1A. RISK FACTORS

  Our operations and financial results are subject to various risks and uncertainties, including those described below, that could adversely affect our business, financial condition, results of operations, cash flows, and the trading price of our common stock.

  STRATEGIC AND COMPETITIVE RISKS

  We face intense competition across all markets for our products and services, which may lead to lower revenue or operating margins.

  Competition in the technology sector

  Our competitors range in size from diversified global companies with significant research and development resources to small, specialized firms whose narrower product lines may let them be more effective in deploying technical, marketing, and financial resources. Barriers to entry in many of our businesses are low and many of the areas in which we compete evolve rapidly with changing and disruptive technologies, shifting user needs, and frequent introductions of new products and services. Our ability to remain competitive depends on our success in making innovative products, devices, and services that appeal to businesses and consumers.

  Competition among platform-based ecosystems

  An important element of our business model has been to create platform-based ecosystems on which many participants can build diverse solutions. A well-established ecosystem creates beneficial network effects among users, application developers, and the platform provider that can accelerate growth. Establishing significant scale in the marketplace is necessary to achieve and maintain attractive margins. We face significant competition from firms that provide competing platforms.

  •A competing vertically-integrated model, in which a single firm controls the software and hardware elements of a product and related services, has succeeded with some consumer products such as personal computers, tablets, phones, gaming consoles, wearables, and other endpoint devices. Competitors pursuing this model also earn revenue from services integrated with the hardware and software platform, including applications and content sold through their integrated marketplaces. They may also be able to claim security and performance benefits from their vertically integrated offer. We also offer some vertically-integrated hardware and software products and services. To the extent we shift a portion of our business to a vertically integrated model we increase our cost of revenue and reduce our operating margins.

  •We derive substantial revenue from licenses of Windows operating systems on PCs. We face significant competition from competing platforms developed for new devices and form factors such as smartphones and tablet computers. These devices compete on multiple bases including price and the perceived utility of the device and its platform. Users are increasingly turning to these devices to perform functions that in the past were performed by personal computers. Even if many users view these device

In [ ]:
# MDA text

In [18]:
#Item 7: MDA doc.
from edgar import Company, set_identity
import re
set_identity("sup2107@columbia.com")
filing = Company("MSFT").get_filings(form="10-K")[0]
text = filing.text()
pattern = re.compile(
    r'(item\s*7\.?\s*management.*?discussion.*?analysis.*?)(item\s*7a\.|item\s*8\.)',
    re.IGNORECASE | re.DOTALL
)
candidates = []
for m in pattern.finditer(text):
    section = m.group(1).strip()
    if len(section) > 2000:   # skip tiny TOC-style matches
        candidates.append(section)
if candidates:
    mda_text = max(candidates, key=len)
    print(mda_text[:5000])
else:
    print("MD&A section not found")

21:53:37  INFO      Identity of the Edgar REST client set to [sup2107@columbia.com]

ITEM 7. MANAGEMENT’S DISCUSSION AND ANALYSIS OF FINANCIAL CONDITION AND RESULTS OF OPERATIONS

The following Management’s Discussion and Analysis of Financial Condition and Results of Operations (“MD&A”) is intended to help the reader understand the results of operations and financial condition of Microsoft Corporation. MD&A is provided as a supplement to, and should be read in conjunction with, our consolidated financial statements and the accompanying Notes to Financial Statements (Part II, Item 8 of this Form 10-K). This section generally discusses the results of our operations for the
year ended June 30, 2025 compared to the year ended June 30, 2024. For a discussion of the year ended June 30, 2024 compared to the year ended June 30, 2023, please refer to Part II, Item 7, “Management’s Discussion and Analysis of Financial Condition and Results of Operations” in our Annual Report on Form 10-K for the year ended June 30, 2024 and our Form 8-K filed on December 3, 2024.

OVERVIEW

Microsoft is a technology company committed to making digital technology and artificial intelligence (“AI”) available broadly and doing so responsibly, with a mission to empower every person and every organization on the planet to achieve more. We create platforms and tools, powered by AI, that deliver innovative solutions that meet the evolving needs of our customers.

We generate revenue by offering a wide range of cloud-based solutions, content, and other services to people and businesses; licensing and supporting an array of software products; delivering relevant online advertising to a global audience; and designing and selling devices. Our most significant expenses are related to compensating employees; supporting and investing in our cloud-based services, including datacenter operations; designing, manufacturing, marketing, and selling our other products
and services; and income taxes.

Highlights from fiscal year 2025 compared with fiscal year 2024 included:

• Microsoft Cloud revenue increased 23% to $168.9 billion.

• Microsoft 365 Commercial products and cloud services revenue increased 14% driven by Microsoft 365 Commercial cloud revenue growth of 15%.

• Microsoft 365 Consumer products and cloud services revenue increased 11% driven by Microsoft 365 Consumer cloud revenue growth of 11%.

• LinkedIn revenue increased 9%.

• Dynamics products and cloud services revenue increased 15% driven by Dynamics 365 revenue growth of 19%.

• Server products and cloud services revenue increased 23% driven by Azure and other cloud services revenue growth of 34%.

• Windows OEM and Devices revenue increased 3%.

• Xbox content and services revenue increased 16%.

• Search and news advertising revenue excluding traffic acquisition costs increased 20%.

Industry Trends and Opportunities

Our industry is dynamic and highly competitive, with frequent changes in both technologies and business models. Each industry shift is an opportunity to conceive new products, new technologies, or new ideas that can further transform the industry and our business. At Microsoft, we push the boundaries of what is possible through a broad range of research and development activities that seek to identify and address the changing demands of customers and users, industry trends, and competitive
forces.

Microsoft and OpenAI maintain a long-term strategic partnership originally established in 2019. Microsoft is a major investor in OpenAI, and the companies have reciprocal revenue-sharing arrangements. We hold rights to OpenAI’s intellectual property, including models and infrastructure, for integration into our products. The OpenAI API is exclusive to Azure, runs on Azure, and is available through the Azure OpenAI Service. We also have a right of first refusal on OpenAI's new capacity needs.

PART II

Item 7

Economic Conditions, Challenges, and Risks

The markets for software, devices, and cloud-based services are dynamic and highly competitive. Our competitors are developing new software and devices, while also deploying competing cloud-based services for consumers and businesses. The devices and form factors customers prefer evolve rapidly, influencing how users access services in the cloud and, in some cases, the user’s choice of which suite of cloud-based services to use. Aggregate demand for our software, services, and devices is also
correlated to global macroeconomic and geopolitical factors, which remain dynamic. We must continue to evolve and adapt over an extended time in pace with this changing environment.

The investments we are making in cloud and AI infrastructure and devices will continue to increase our operating costs and may decrease our operating margins. We continue to identify and evaluate opportunities to expand our datacenter locations and increase our server capacity to meet the evolving needs of our customers, particularly given the growing demand for AI services. Our datacenters depend on the availability of permitted and build

In [19]:
mda_final =mda_text

In [ ]:
#build function for chunking.

In [20]:

from nltk.tokenize import sent_tokenize   # import directly — avoids module clash
import re
import nltk
import pandas as pd
from dataclasses import dataclass, field

nltk.download('punkt',     quiet=True)
nltk.download('punkt_tab', quiet=True)

# ── Chunking config ──────────────────────────────────────────────
MAX_TOKENS          = 400
OVERLAP_SENTENCES   = 1
MIN_CHUNK_CHARS     = 100
AVG_CHARS_PER_TOKEN = 4

# ── Earnings boilerplate to strip ────────────────────────────────
STRIP_PATTERNS_EARNINGS = [
    r"(?i)forward.looking statements.{0,2000}",
    r"(?i)safe harbor.{0,1000}",
    r"(?i)private securities litigation.{0,500}",
    r"(?i)(investor relations|media contact|for more information).{0,300}",
    r"(?i)^(document|exhibit\s*\d+\.\d+)\s*$",
]

# ─── data model ─────────────────────────────────────────────────
@dataclass
class Chunk:
    text:         str
    company:      str
    ticker:       str
    source:       str
    source_type:  str
    published_at: str
    url:          str
    chunk_index:  int
    chunk_total:  int
    char_count:   int = field(init=False)
    token_count:  int = field(init=False)

    def __post_init__(self):
        self.char_count  = len(self.text)
        self.token_count = len(self.text) // AVG_CHARS_PER_TOKEN

# ─── 1. Text cleaner ────────────────────────────────────────────
def clean_text(text: str, source_type: str = "news") -> str:
    if not text:
        return ""

    # strip HTML
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"&[a-z]+;", " ", text)

    if source_type == "earnings":
        # strip legal boilerplate
        for pattern in STRIP_PATTERNS_EARNINGS:
            text = re.sub(pattern, "", text, flags=re.DOTALL | re.MULTILINE)
        # strip lines that are mostly numbers (financial table rows)
        # threshold raised to 40% alphabetic
        lines       = text.split('\n')
        clean_lines = []
        for line in lines:
            stripped    = line.strip()
            alpha_chars = sum(1 for c in stripped if c.isalpha())
            total_chars = len(stripped)
            if total_chars == 0 or alpha_chars / total_chars >= 0.4:
                clean_lines.append(line)
        text = '\n'.join(clean_lines)

    # normalise whitespace
    text = re.sub(r'\n{3,}', '\n\n', text)
    text = re.sub(r'[ \t]{2,}', ' ', text)
    return text.strip()

# ─── 2. Semantic chunker ────────────────────────────────────────
def semantic_chunk(text: str, max_tokens: int = MAX_TOKENS,
                   overlap: int = OVERLAP_SENTENCES) -> list:
    try:
        sentences = sent_tokenize(text)   # using directly imported function
    except Exception:
        sentences = re.split(r'(?<=[.!?])\s+', text)

    if not sentences:
        return []

    chunks     = []
    current    = []
    cur_tokens = 0

    for sent in sentences:
        sent_tokens = len(sent) // AVG_CHARS_PER_TOKEN
        if cur_tokens + sent_tokens > max_tokens and current:
            chunks.append(' '.join(current))
            current    = current[-overlap:] if overlap > 0 else []
            cur_tokens = sum(len(s) // AVG_CHARS_PER_TOKEN for s in current)
        current.append(sent)
        cur_tokens += sent_tokens

    if current:
        chunks.append(' '.join(current))

    return chunks

# ─── 3. Fixed chunker (fallback) ────────────────────────────────
def fixed_chunk(text: str, max_tokens: int = MAX_TOKENS,
                overlap_chars: int = 50) -> list:
    max_chars = max_tokens * AVG_CHARS_PER_TOKEN
    chunks    = []
    start     = 0
    while start < len(text):
        end = start + max_chars
        chunks.append(text[start:end].strip())
        start = end - overlap_chars
    return [c for c in chunks if c]

# ─── 4. Hybrid chunker ──────────────────────────────────────────
def hybrid_chunk(text: str, max_tokens: int = MAX_TOKENS,
                 source_type: str = "news") -> list:
    text = clean_text(text, source_type)
    if not text:
        return []

    chunks       = semantic_chunk(text, max_tokens)
    final_chunks = []

    for chunk in chunks:
        if len(chunk) // AVG_CHARS_PER_TOKEN > max_tokens:
            final_chunks.extend(fixed_chunk(chunk, max_tokens))
        else:
            final_chunks.append(chunk)

    return [
        c.strip() for c in final_chunks
        if len(c.strip()) >= MIN_CHUNK_CHARS
    ]

# ─── 5. Chunk a single article ──────────────────────────────────
def chunk_article(raw_text, company, ticker, source,
                  source_type, published_at, url,
                  max_tokens=MAX_TOKENS) -> list:
    texts = hybrid_chunk(str(raw_text), max_tokens, source_type)
    if not texts:
        return []
    chunks = []
    for i, chunk_text in enumerate(texts):
        chunks.append(Chunk(
            text         = chunk_text,
            company      = company,
            ticker       = ticker.upper(),
            source       = source,
            source_type  = source_type,
            published_at = str(published_at)[:10],
            url          = str(url),
            chunk_index  = i,
            chunk_total  = len(texts),
        ))
    return chunks

# ─── 6. Chunk news df_final ─────────────────────────────────────
def chunk_news_dataframe(df, ticker, max_tokens=MAX_TOKENS) -> list:
    all_chunks = []
    for _, row in df.iterrows():
        chunks = chunk_article(
            raw_text     = row.get("raw_text", ""),
            company      = row.get("company", ""),
            ticker       = ticker,
            source       = row.get("source", ""),
            source_type  = "news",
            published_at = row.get("published_at", ""),
            url          = row.get("url", ""),
            max_tokens   = max_tokens,
        )
        all_chunks.extend(chunks)
    print(f"News chunking    : {len(df)} articles → {len(all_chunks)} chunks")
    return all_chunks

# ─── 7. Chunk earnings report ───────────────────────────────────
def chunk_earnings_report(raw_text, company, ticker,
                           published_at, max_tokens=MAX_TOKENS) -> list:
    chunks = chunk_article(
        raw_text     = raw_text,
        company      = company,
        ticker       = ticker,
        source       = "SEC EDGAR 8-K",
        source_type  = "earnings",
        published_at = published_at,
        url          = f"https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK={ticker}",
        max_tokens   = max_tokens,
    )
    print(f"Earnings chunking: 1 report → {len(chunks)} chunks")
    return chunks

# ─── 8. Convert to dataframe ────────────────────────────────────
def chunks_to_dataframe(chunks: list) -> pd.DataFrame:
    if not chunks:
        return pd.DataFrame()
    return pd.DataFrame([{
        "company":              c.company,
        "ticker":               c.ticker,
        "source":               c.source,
        "source_type":          c.source_type,
        "published_at":         c.published_at,
        "url":                  c.url,
        "chunk_index":          c.chunk_index,
        "chunk_total":          c.chunk_total,
        "text":                 c.text,
        "char_count":           c.char_count,
        "token_count":          c.token_count,
        "sentiment_label":      None,
        "sentiment_confidence": None,
        "embedding":            None,
    } for c in chunks])

# ─── 9. Verify chunks ───────────────────────────────────────────
def verify_chunks(df_chunks: pd.DataFrame):
    print(f"\n{'='*60}")
    print(f"  CHUNK VERIFICATION")
    print(f"{'='*60}")
    print(f"  Total chunks     : {len(df_chunks)}")
    if len(df_chunks) == 0:
        print("  No chunks to verify.")
        return
    print(f"  Avg token count  : {df_chunks['token_count'].mean():.0f}")
    print(f"  Max token count  : {df_chunks['token_count'].max()}")
    print(f"  Min token count  : {df_chunks['token_count'].min()}")

    print(f"\n  By source type:")
    for stype, grp in df_chunks.groupby("source_type"):
        print(f"    {stype:<15} : {len(grp)} chunks")

    print(f"\n  By source:")
    for src, grp in df_chunks.groupby("source"):
        print(f"    {src:<35} : {len(grp)} chunks")

    print(f"\n  Sample chunks:")
    for i, row in df_chunks.head(3).iterrows():
        print(f"\n  ── Chunk {row['chunk_index']+1}/{row['chunk_total']} "
              f"[{row['source_type']}] [{row['source']}]")
        print(f"  Company : {row['company']} ({row['ticker']})")
        print(f"  Date    : {row['published_at']}")
        print(f"  Tokens  : ~{row['token_count']}")
        print(f"  Text    : {row['text'][:300]}...")
    print(f"{'='*60}\n")

# ============================================================
# ★  RUN
# ============================================================

print("=" * 60)
print("  STAGE B — HYBRID CHUNKING")
print("=" * 60)

# ── Step 1: chunk news articles (only if df_final is a valid DataFrame)
news_chunks = []
try:
    if isinstance(df_final, pd.DataFrame) and len(df_final) > 0:
        print(f"\n✓ df_final found : {len(df_final)} articles")
        # get company_name safely
        try:
            _ticker = company_name
        except NameError:
            _ticker = "UNKNOWN"
        print("Chunking news articles...")
        news_chunks = chunk_news_dataframe(
            df     = df_final,
            ticker = _ticker,
        )
    else:
        print("\n✗ df_final is empty or not a DataFrame — skipping news chunking")
except NameError:
    print("\n✗ df_final not in memory — skipping news chunking")
    print("  Run the v8 pipeline cell first to collect news articles")

# ── Step 2: chunk earnings report from text variable ─────────────
earnings_chunks = []

# ★ UPDATE THESE THREE LINES to match your company
EARNINGS_TICKER  = "MSFT"        # e.g. "META", "GOOGL", "MSFT"
EARNINGS_DATE    = "2026-01-29"  # actual filing date
EARNINGS_COMPANY = "Microsoft"       # actual company name

try:
    if text and isinstance(text, str) and len(text) > 100:
        print(f"\n✓ earnings text found : {len(text):,} chars")
        print("Chunking earnings report...")
        earnings_chunks = chunk_earnings_report(
            raw_text     = text,
            company      = EARNINGS_COMPANY,
            ticker       = EARNINGS_TICKER,
            published_at = EARNINGS_DATE,
        )
    else:
        print("\n✗ earnings text not available — skipping earnings chunking")
except NameError:
    print("\n✗ text not in memory — skipping earnings chunking")
    print("  Run get_latest_earnings_8k_text() first")

# ── Step 3: combine ──────────────────────────────────────────────
all_chunks = news_chunks + earnings_chunks
df_chunks  = chunks_to_dataframe(all_chunks)

print(f"\n{'='*60}")
print(f"  CHUNKING SUMMARY")
print(f"{'='*60}")
print(f"  News chunks      : {len(news_chunks)}")
print(f"  Earnings chunks  : {len(earnings_chunks)}")
print(f"  Total df_chunks  : {len(df_chunks)}")
print(f"{'='*60}")

# ── Step 4: verify + preview ─────────────────────────────────────
if len(df_chunks) > 0:
    verify_chunks(df_chunks)
    print("  df_chunks preview:")
    print(df_chunks[[
        "company", "ticker", "source_type", "source",
        "published_at", "chunk_index", "chunk_total",
        "token_count", "text"
    ]].head(10).to_string())
else:
    print("\n  No chunks produced.")
    print("  Make sure at least one of the following is in memory:")
    print("  1. df_final  — run v8 pipeline cell")
    print("  2. text      — run get_latest_earnings_8k_text()")

============================================================
  STAGE B — HYBRID CHUNKING
============================================================

✓ df_final found : 34 articles
Chunking news articles...
News chunking    : 34 articles → 126 chunks

✓ earnings text found : 349,181 chars
Chunking earnings report...
Earnings chunking: 1 report → 244 chunks

============================================================
  CHUNKING SUMMARY
============================================================
  News chunks      : 126
  Earnings chunks  : 244
  Total df_chunks  : 370
============================================================

============================================================
  CHUNK VERIFICATION
============================================================
  Total chunks     : 370
  Avg token count  : 352
  Max token count  : 400
  Min token count  : 27

  By source type:
    earnings        : 244 chunks
    news            : 126 chunks

  By source:
    Ars Technica                        : 2 chunks
    Associated Press                    : 6 chunks
    CNBC                                : 31 chunks
    Fortune                             : 16 chunks
    SEC EDGAR 8-K                       : 244 chunks
    TechCrunch                          : 25 chunks
    The Guardian Business               : 3 chunks
    The Guardian Tech                   : 17 chunks
    Wired                               : 12 chunks
    Wired Business                      : 3 chunks
    ZDNet                               : 11 chunks

  Sample chunks:

  ── Chunk 1/3 [news] [Fortune]
  Company : Apple (APPLE)
  Date    : 2026-04-22
  Tokens  : ~378
  Text    : Tim Cook and Steve Jobs couldn’t have been more different, according to the Apple cofounder’s biographer Walter Isaacson. Jobs was a creative genius who spearheaded the development of Apple’s signature products including the Mac, iPhone, and iPod. But he was also a hothead, known for pushing people ...

  ── Chunk 2/3 [news] [Fortune]
  Company : Apple (APPLE)
  Date    : 2026-04-22
  Tokens  : ~395
  Text    : His supply-chain mastery helped save the company huge sums of money by selling products quickly and eliminating a backlog of unsold devices. And his decision to sideline Intel’s chips in favor of the company’s own M1 processors in the Mac lineup made the company’s products faster and added battery l...

  ── Chunk 3/3 [news] [Fortune]
  Company : Apple (APPLE)
  Date    : 2026-04-22
  Tokens  : ~212
  Text    : He also closed warehouses to cut down on inventory stockpiles that were costing the company money. In contrast to Jobs’ volatility, Cook always operated with a calm demeanor. He was known for a strong work ethic, rising daily at 4:30 a.m. to go to the gym before arriving at the office by 6 a.m. He a...
============================================================

  df_chunks preview:
  company ticker source_type   source published_at  chunk_index  chunk_total  token_count                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text
0   Apple  APPLE        news  Fortune   2026-04-22            0            3          378                                                                                     Tim Cook and Steve Jobs couldn’t have been more different, according to the Apple cofounder’s biographer Walter Isaacson. Jobs was a creative genius who spearheaded the development of Apple’s signature products including the Mac, iPhone, and iPod. But he was also a hothead, known for pushing people to their limits and sometimes creating conflict on purpose in meetings to see if it would yield a better outcome, according to Isaacson. By contrast, Cook, who announced he was retiring as Apple CEO this week, was levelheaded and serious. An engineer with a business degree from Duke, he had worked for 12 years at IBM, Jobs’ sworn enemy, before joining Apple. Yet Cook and Jobs got along great. “He had the same vision I did, and we could interact at a high strategic level, and I could just forget about a lot of things unless he came and pinged me,” Jobs said of Cook, according to Isaacson’s biography of the Apple cofounder. Jobs had only one criticism of Cook: He was “not a product person, per se.”\n\nDespite this, Cook has cemented his legacy as one of Apple’s most successful CEOs as he steps down in September. Tim Cook’s CEO strategy\n\nUnder his tenure, Apple’s market cap has skyrocketed from about $350 billion when he took over to $4 trillion today. It’s now the third most valuable company in the world by market cap. Much of that is because of Cook’s strategy. His supply-chain mastery helped save the company huge sums of money by selling products quickly and eliminating a backlog of unsold devices.
1   Apple  APPLE        news  Fortune   2026-04-22            1            3          395                     His supply-chain mastery helped save the company huge sums of money by selling products quickly and eliminating a backlog of unsold devices. And his decision to sideline Intel’s chips in favor of the company’s own M1 processors in the Mac lineup made the company’s products faster and added battery life while also cutting costs. While many of Apple’s bestselling products under Cook were developed during the Jobs era, including the iPhone, the Mac, and the iPad, Cook oversaw Apple’s expansion into wearables with the Apple Watch and AirPods, launched in 2014 and 2016, respectively. The wearable category was a $35 billion business for Apple as of 2025 and made up about 8.5% of the company’s revenue. Cook vs. Jobs\n\nDespite their differences, Cook was immediately taken with Jobs’ charisma when he met him in 1998, and said within five minutes he wanted to throw caution to the wind and leave his safe job at Compaq to join Apple, according to the biography of Jobs. “My intuition told me that joining Apple would be a once-in-a-lifetime opportunity to work for a creative genius,” Cook told Isaacson. But he was also filling a gap for Jobs. The Apple CEO had been running operations at the company for nearly a year because his previous head of operations had quit owing to the pressure, according to Isaacson. Cook made his own mark early on in his role as operations leader by cutting Apple’s key suppliers from 100 to 24, and negotiating to get better deals for the company. He also closed warehouses to cut down on inventory stockpiles that were costing the company money.
2   Apple  APPLE        news  Fortune   2026-04-22            2            3          212                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 He also closed warehouses to cut down on inventory stockpiles that were costing the company money. In contrast to Jobs’ volatility, Cook always operated with a calm demeanor. He was known for a strong work ethic, rising daily at 4:30 a.m. to go to the gym before arriving at the office by 6 a.m. He also had a penchant for setting up Sunday meetings to prepare for the week ahead. Thanks to the trust Jobs had in him to execute his vision, he designated Cook to run Apple while he took several medical leaves after having been diagnosed with a rare form of pancreatic cancer in 2004. In the end, Jobs suggested Cook succeed him as CEO during a board meeting just before he died in October 2011 at the age of 56. It was a final act of confidence by the Apple cofounder in the man who would go on to make his company one of the most valuable in history.
3   Apple  APPLE        news  Fortune   2026-04-21            0            3          364                                                                                                                                                  Apple is entering a new era. The company announced on Monday that CEO Tim Cook will be stepping down and John Ternus, Apple’s current senior vice president of hardware engineering, will succeed him. Cook has led the company for almost 15 years, assuming the role shortly before founder Steve Jobs’ death in 2011. Under his leadership, Apple’s market capitalization has grown from $350 billion to $4 trillion and the company has launched products such as iCloud, Apple Pay, AirPods, and the Apple Watch, redefining the brand as more than just a phone and computer company. Cook will step down as CEO on Sept. 1, but will remain as Apple’s executive chairman. The 65-year-old boasts one of the longest tenures in Big Tech as a non-founding CEO. He has navigated geopolitical conflicts, shielding Apple from tariffs, and landed huge partnerships with other big tech companies. His legacy has earned him praise from fellow business leaders following the announcement. “Tim Cook is a legend,” OpenAI CEO Sam Altman wrote on X. “I am very thankful for everything he has done, and I am very thankful for Apple.” In 2024, Apple agreed to integrate OpenAI’s ChatGPT chatbot into iPhone, iPad and Mac products, providing access to the company’s more than 1 billion users. Warren Buffett, chairman of Berkshire Hathaway, told CNBC: “Apple would not be the Apple of today without Tim Cook. “What he has done with Apple could not be done by anybody I’ve known,” he noted.
4   Apple  APPLE        news  Fortune   2026-04-21            1            3          359                                                                                                                                                                      “What he has done with Apple could not be done by anybody I’ve known,” he noted. “Covering the world and getting along with countries with all kinds of histories and doing right by the customer, people who worked for him, certainly the shareholders, which we were lucky enough to be one of … He’s one of a kind,” Buffett said. Apple is Berkshire Hathaway’s largest holding, and Buffett has long praised Cook for his consumer-forward approach and bringing large returns for shareholders. Palmer Luckey, founder of defense company Anduril, wrote in an X post: “RIP Tim Apple,” a reference to President Donald Trump mistakenly calling the CEO “Tim Apple” in 2019. Since then, the president has used it as a pet name for Cook. Luckey previously praised Apple’s Vision Pro virtual reality headset, a product hardware chief Ternus was deeply involved in. A shout-out from the president\n\nThe president once again evoked his pet name for the CEO in a social media post congratulating Cook on Tuesday morning and noting a phone call he’d had with Cook during his first term. “When I got the call I said, wow, it’s Tim Apple (Cook!) calling, how big is that?” Trump wrote on Truth Social. “I was very impressed with myself to have the head of Apple calling to ‘kiss my ass’ … That was the beginning of a long and very nice relationship. During my five years as President, Tim would call me, but never too much, and I would help him where I could.
5   Apple  APPLE        news  Fortune   2026-04-21            2            3          395                        During my five years as President, Tim would call me, but never too much, and I would help him where I could. “I have always been a big fan of Tim Cook, and likewise, Steve Jobs, but if Steve was not taken from the Planet Earth so young, and ran the company instead of Tim, the company would have done well, but nowhere near as well as it has under Tim,” the president added. Big Tech made a reversal during Trump’s second term, and began courting the White House, with Apple chief among them, earning Cook his position as “the Trump whisperer.” In line with Trump’s “America First” manufacturing agenda, Apple committed to accelerating domestic manufacturing by spending $100 billion, bringing the company’s total investment in domestic production to $600 billion over the next four years. At a ceremony announcing the commitment in August, Cook gifted Trump a customized glass plaque mounted on a 24-karat gold stand. “Anyway, Tim Cook had an AMAZING career, almost incomparable, and will go on and continue to do great work for Apple, and whatever else he chooses to work on. Quite simply, Tim Cook is an incredible guy!! !” Trump wrote. Cook’s schmoozing with the Republican president is not without consequence. He came under fire with Apple employees in January after he attended a White House screening of a documentary about first lady Melania Trump, hours after a Border Patrol agent killed Alex Pretti, a 37-year-old ICU nurse and American citizen, in Minneapolis. Days later, he told employees that he’d spoken with Trump about de-escalating ICE operations in the city.
6   Apple  APPLE        news     CNBC   2026-04-22            0            5          378                                                                                        Apple CEO Tim Cook speaks during Apple's "Awe-Dropping" event at the Steve Jobs Theater on the Apple Park campus in Cupertino, California, on September 9, 2025. Tim Cook will step down as Apple's CEO on Sept. 1 after 15 years leading one of the most valuable companies in the world. There'll be no shortage of retrospectives about his operational genius, his supply chain mastery, and his steady stewardship through the post-Jobs era. But there's one thing I keep coming back to: Cook is one of the best listeners I've ever encountered. As a CEO coach and the author of "Radical Candor: Be a Kick-Ass Boss Without Losing Your Humanity," I know that in a world where leaders are increasingly rewarded for being loud, confident, and quick, his approach is worth studying. Jony Ive, Apple's former chief design officer, once said at a class at Apple University, where I was a faculty member, that a manager's most important role is to "give the quiet ones a voice." I love this. Former Google CEO Eric Schmidt took the opposite approach, urging people to "Be loud!" I love this, too. The two leaders took different approaches to listen and ensure that everyone was heard. Great leaders find a way to listen that fits their personal style, and then create a culture where everyone listens to each other. Here's how Cook did it. Meeting the master of silence\n\nBefore I interviewed at Apple, a friend warned me that Cook tended to allow long silences and that I shouldn't let it unnerve me or feel the need to fill them.
7   Apple  APPLE        news     CNBC   2026-04-22            1            5          391                                   Meeting the master of silence\n\nBefore I interviewed at Apple, a friend warned me that Cook tended to allow long silences and that I shouldn't let it unnerve me or feel the need to fill them. Despite this warning, in our first interview I reacted to a silence by anxiously talking nonstop, inadvertently telling him far more about a mistake I'd made than I intended. Just when I realized, panic-stricken, that I was about to reveal something that might well cost me the job, the room began to shake. I was relieved to be saved by an actual earthquake. Following in Cook's footsteps, one of my students in the "Managing at Apple" class said that he tried to make sure to spend at least 10 minutes in every one-on-one meeting listening silently, keeping his facial expression and body language neutral. "If I gave any reaction at all, people would often tell me what they thought I wanted to hear," he said. "I found that they were much more likely to say what they really thought — even if it wasn't what I was hoping to hear — when I was careful not to show what I thought." But quiet listening can have a downside: When you're the boss and people don't know what you think, they waste a lot of time trying to guess. And plenty of people are made very uncomfortable by silence. Some even feel a quiet listener is setting a trap: waiting for others to say the wrong thing so they can pounce. If you're a quiet listener, you need to take steps to reassure people. Don't be pointlessly inscrutable. To get others to say what they think, say what you think sometimes, too.
8   Apple  APPLE        news     CNBC   2026-04-22            2            5          400  To get others to say what they think, say what you think sometimes, too. The manager in my class was expressionless for only 10 minutes of his 1:1s, not the full hour. Otherwise, it would've been hard for people to trust him or to relate to him. Cook wasn't always silent either, of course. But because he was generally so quiet, people leaned forward to listen to what he said. And when he spoke, albeit very quietly, his thinking was always crystal clear. Finding another way listen\n\nQuiet listening works for many managers, but I can't pull it off. Luckily, there's another model. If quiet listening involves being silent to give people room to talk, loud listening is about saying things intended to get a reaction out of them. Steve Jobs, for example, would put a strong point of view on the table and insist on a response. Obviously this approach works only when people feel confident enough to rise to the challenge. How do you deal with people who can't stand up to an aggressive boss or whose position doesn't allow them to feel secure, even if the larger culture welcomes this behavior? What about someone who's just started at the company? They might know a good reason why you're wrong, but they won't speak up. If you have a loud listening style, you need to go to some lengths to build people's confidence and let them realize it's safe to challenge the boss. Ive said that Jobs would often come to him and say, "Jony, here's a dopey idea." He was inviting Ive to challenge his idea by calling it dopey. Paul Saffo, an engineering professor at Stanford University, describes a technique

Getting risk data

getting risk data

#combine all the texts into combined dataframe.

In [21]:
all_chunks = []
# ── 1. Chunk Risk Factors ─────────────────────────────────────────
risk_chunks = chunk_article(
    raw_text     = tenk.risk_factors,
    company      = "Microsoft",
    ticker       = "MSFT",
    source       = "SEC EDGAR 10-K",
    source_type  = "risk",
    published_at = "2026-01-28",
    url          = "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=MSFT",
)
all_chunks.extend(risk_chunks)
print(f"✓ Risk Factors : {len(risk_chunks)} chunks")

# ── 2. Chunk MD&A ────────────────────────────────────────────────
mda_chunks = chunk_article(
    raw_text     = mda_text,
    company      = "Microsoft",
    ticker       = "MSFT",
    source       = "SEC EDGAR 10-K",
    source_type  = "mda",
    published_at = "2026-01-28",
    url          = "https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=MSFT",
)
all_chunks.extend(mda_chunks)
print(f"✓ MD&A         : {len(mda_chunks)} chunks")

# ── 3. Chunk 4 quarters earnings ─────────────────────────────────
for _, row in df_edgar.iterrows():
    chunks = chunk_earnings_report(
        raw_text     = row["text"],
        company      = row["company"],
        ticker       = row["ticker"],
        published_at = row["filing_date"],
    )
    all_chunks.extend(chunks)
    print(f"✓ Earnings {row['filing_date']} : {len(chunks)} chunks")

# ── 4. Chunk news articles ───────────────────────────────────────
news_chunks = chunk_news_dataframe(
    df     = news_final,
    ticker = "MSFT",
)
all_chunks.extend(news_chunks)

# ── 5. Convert to dataframe ──────────────────────────────────────
df_chunks = chunks_to_dataframe(all_chunks)

# ── 6. Add section metadata ──────────────────────────────────────
df_chunks["section_type"] = df_chunks["source_type"].map({
    "risk":     "Risk Factors",
    "mda":      "MD&A",
    "earning":  "8-K earnings",
    "earnings": "8-K earnings",
    "news":     "news",
}).fillna("news")

df_chunks["section_weight"] = df_chunks["section_type"].map({
    "MD&A":          1.5,
    "Risk Factors":  1.3,
    "8-K earnings":  1.0,
    "news":          0.8,
}).fillna(1.0)

df_chunks["filing_date"] = df_chunks["published_at"]

# ── 7. Summary ───────────────────────────────────────────────────
print(f"\nFinal df_chunks : {len(df_chunks)} chunks")
print(df_chunks["section_type"].value_counts())

✓ Risk Factors : 52 chunks
✓ MD&A         : 40 chunks
Earnings chunking: 1 report → 4 chunks
✓ Earnings 2026-01-29 : 4 chunks
Earnings chunking: 1 report → 8 chunks
✓ Earnings 2025-10-30 : 8 chunks
Earnings chunking: 1 report → 4 chunks
✓ Earnings 2025-07-31 : 4 chunks
Earnings chunking: 1 report → 4 chunks
✓ Earnings 2025-05-01 : 4 chunks
News chunking    : 34 articles → 126 chunks

Final df_chunks : 238 chunks
section_type
news            126
Risk Factors     52
MD&A             40
8-K earnings     20
Name: count, dtype: int64

In [22]:
df_final = df_chunks

In [23]:
df_final

,company,ticker,source,source_type,published_at,url,chunk_index,chunk_total,text,char_count,token_count,sentiment_label,sentiment_confidence,embedding,section_type,section_weight,filing_date
0,Microsoft,MSFT,SEC EDGAR 10-K,risk,2026-01-28,https://www.sec.gov/cgi-bin/browse-edgar?actio...,0,52,ITEM 1A. RISK FACTORS\n\n Our operations and f...,1584,396,None,None,None,Risk Factors,1.3,2026-01-28
1,Microsoft,MSFT,SEC EDGAR 10-K,risk,2026-01-28,https://www.sec.gov/cgi-bin/browse-edgar?actio...,1,52,Establishing significant scale in the marketpl...,1466,366,None,None,None,Risk Factors,1.3,2026-01-28
2,Microsoft,MSFT,SEC EDGAR 10-K,risk,2026-01-28,https://www.sec.gov/cgi-bin/browse-edgar?actio...,2,52,Users are increasingly turning to these device...,1570,392,None,None,None,Risk Factors,1.3,2026-01-28
3,Microsoft,MSFT,SEC EDGAR 10-K,risk,2026-01-28,https://www.sec.gov/cgi-bin/browse-edgar?actio...,3,52,Competitors’ rules governing their content and...,1522,380,None,None,None,Risk Factors,1.3,2026-01-28
4,Microsoft,MSFT,SEC EDGAR 10-K,risk,2026-01-28,https://www.sec.gov/cgi-bin/browse-edgar?actio...,4,52,•Other competitors develop and offer free appl...,1562,390,None,None,None,Risk Factors,1.3,2026-01-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,Apple,MSFT,ZDNet,news,2026-04-21,https://www.zdnet.com/article/diarly-journalin...,1,4,"In fact, I've been using the free version of D...",1595,398,None,None,None,news,0.8,2026-04-21
234,Apple,MSFT,ZDNet,news,2026-04-21,https://www.zdnet.com/article/diarly-journalin...,2,4,Both Moods and Tags make it easier for you to ...,1533,383,None,None,None,news,0.8,2026-04-21
235,Apple,MSFT,ZDNet,news,2026-04-21,https://www.zdnet.com/article/diarly-journalin...,3,4,Any important entry gets a target icon. Screen...,569,142,None,None,None,news,0.8,2026-04-21
236,Apple,MSFT,ZDNet,news,2026-04-20,https://www.zdnet.com/article/why-you-should-w...,0,2,Nina Raemont/ZDNET\n\nFollow ZDNET: Add us as ...,1600,400,None,None,None,news,0.8,2026-04-20
237,Apple,MSFT,ZDNet,news,2026-04-20,https://www.zdnet.com/article/why-you-should-w...,1,2,Also: The best Apple Watch of 2026: Expert tes...,1189,297,None,None,None,news,0.8,2026-04-20

In [24]:
df_final = df_chunks[['ticker', 'source','section_type','text','char_count','filing_date']]
df_chunks['source_type'].value_counts()

source_type
news        126
risk         52
mda          40
earnings     20
Name: count, dtype: int64

In [25]:
df_final['text'][2]

'Users are increasingly turning to these devices to perform functions that in the past were performed by personal computers. Even if many users view these devices as complementary to a personal computer, the prevalence of these devices may make it more difficult to attract application developers to our PC operating system platforms. Competing with operating systems licensed at low or no cost may decrease our PC operating system margins. Popular products or services offered on competing platforms could increase their competitive strength. In addition, some of our devices compete with products made by our original equipment manufacturer (“OEM”) partners, which may affect their commitment to our platform. •Competing platforms have content and application marketplaces with scale and significant installed bases. The variety and utility of content and applications available on a platform are important to device purchasing decisions. Users may incur costs to move data and buy new content and applications when switching platforms. To compete, we must successfully enlist developers to write applications for our platform and ensure that these applications have high quality, security, customer appeal, and value. Efforts to compete with competitors’ content and application marketplaces may increase our cost of revenue and lower our operating margins. Competitors’ rules governing their content and applications marketplaces may restrict our ability to distribute products and services through them in accordance with our technical and business model objectives.'

In [26]:
df_chunks = df_final

In [27]:
df_chunks

,ticker,source,section_type,text,char_count,filing_date
0,MSFT,SEC EDGAR 10-K,Risk Factors,ITEM 1A. RISK FACTORS\n\n Our operations and f...,1584,2026-01-28
1,MSFT,SEC EDGAR 10-K,Risk Factors,Establishing significant scale in the marketpl...,1466,2026-01-28
2,MSFT,SEC EDGAR 10-K,Risk Factors,Users are increasingly turning to these device...,1570,2026-01-28
3,MSFT,SEC EDGAR 10-K,Risk Factors,Competitors’ rules governing their content and...,1522,2026-01-28
4,MSFT,SEC EDGAR 10-K,Risk Factors,•Other competitors develop and offer free appl...,1562,2026-01-28
...,...,...,...,...,...,...
233,MSFT,ZDNet,news,"In fact, I've been using the free version of D...",1595,2026-04-21
234,MSFT,ZDNet,news,Both Moods and Tags make it easier for you to ...,1533,2026-04-21
235,MSFT,ZDNet,news,Any important entry gets a target icon. Screen...,569,2026-04-21
236,MSFT,ZDNet,news,Nina Raemont/ZDNET\n\nFollow ZDNET: Add us as ...,1600,2026-04-20
237,MSFT,ZDNet,news,Also: The best Apple Watch of 2026: Expert tes...,1189,2026-04-20

In [28]:
# RAG process

In [29]:
print(df_final.columns.tolist())

['ticker', 'source', 'section_type', 'text', 'char_count', 'filing_date']

#need anthropic api for claude ai

In [ ]:
# ============================================================
# RAG Pipeline — fixed for df_final columns
# columns: ticker, source, section_type, text, char_count, filing_date
# ============================================================

import os
os.environ["ANTHROPIC_API_KEY"] = 

import anthropic
import chromadb
import pandas as pd
from sentence_transformers import SentenceTransformer, CrossEncoder

# ── CONFIG ───────────────────────────────────────────────────────
EMBED_MODEL  = "all-MiniLM-L6-v2"
RERANK_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"
CHROMA_PATH  = "./chroma_db"
COLLECTION   = "msft_financial"
TOP_K        = 20
TOP_N        = 5

# ── 1. Load models ───────────────────────────────────────────────
print("Loading embedding model...")
embedder = SentenceTransformer(EMBED_MODEL)
print("Loading reranking model...")
reranker = CrossEncoder(RERANK_MODEL)
print("✓ Models loaded")

# ── 2. Setup ChromaDB ────────────────────────────────────────────
chroma_client = chromadb.PersistentClient(path=CHROMA_PATH)
collection    = chroma_client.get_or_create_collection(
    name     = COLLECTION,
    metadata = {"hnsw:space": "cosine"}
)

# ── 3. Index df_final ────────────────────────────────────────────
def index_chunks(df: pd.DataFrame):
    print(f"\nIndexing {len(df)} chunks...")

    texts      = df['text'].tolist()
    embeddings = embedder.encode(texts, show_progress_bar=True)

    collection.upsert(
        ids        = [str(i) for i in df.index],
        embeddings = embeddings.tolist(),
        documents  = texts,
        metadatas  = [
            {
                "section_type": str(row.get('section_type', '')),
                "filing_date":  str(row.get('filing_date', '')),
                "source":       str(row.get('source', '')),
                "ticker":       str(row.get('ticker', 'MSFT')),
                "company":      "Microsoft",
            }
            for _, row in df.iterrows()
        ]
    )
    print(f"✓ {collection.count()} chunks indexed in ChromaDB")

# ── 4. Retrieve ──────────────────────────────────────────────────
def retrieve(query: str, top_k: int = TOP_K) -> list:
    query_vector = embedder.encode([query]).tolist()
    results      = collection.query(
        query_embeddings = query_vector,
        n_results        = top_k,
        include          = ["documents", "metadatas", "distances"]
    )
    candidates = []
    for doc, meta, dist in zip(
        results['documents'][0],
        results['metadatas'][0],
        results['distances'][0]
    ):
        candidates.append({
            "text":     doc,
            "metadata": meta,
            "distance": dist
        })
    return candidates

# ── 5. Rerank ────────────────────────────────────────────────────
def rerank(query: str, candidates: list, top_n: int = TOP_N) -> list:
    pairs  = [(query, c['text']) for c in candidates]
    scores = reranker.predict(pairs)
    for i, score in enumerate(scores):
        candidates[i]['rerank_score'] = float(score)
    reranked = sorted(candidates, key=lambda x: x['rerank_score'], reverse=True)
    return reranked[:top_n]

# ── 6. Generate with Claude ──────────────────────────────────────
def generate(query: str, top_chunks: list) -> str:
    context_parts = []
    for i, chunk in enumerate(top_chunks, 1):
        meta = chunk['metadata']
        context_parts.append(
            f"[Source {i} — {meta.get('section_type', 'unknown')} "
            f"from {meta.get('source', 'unknown')} "
            f"dated {meta.get('filing_date', 'unknown')}]\n"
            f"{chunk['text']}"
        )
    context = "\n\n".join(context_parts)

    prompt = f"""You are a financial analyst assistant for Microsoft (MSFT).
Answer the question based ONLY on the provided context from SEC filings and news.
If context does not contain enough information, say so clearly.
Be concise, factual, and cite specific numbers where available.

Context:
{context}

Question: {query}

Answer:"""

    claude   = anthropic.Anthropic()
    response = claude.messages.create(
        model      = "claude-sonnet-4-6",
        max_tokens = 512,
        messages   = [{"role": "user", "content": prompt}]
    )
    return response.content[0].text

# ── 7. Full RAG pipeline ─────────────────────────────────────────
def rag_query(query: str) -> dict:
    print(f"\n{'='*60}")
    print(f"  Query: {query}")
    print(f"{'='*60}")

    candidates = retrieve(query, top_k=TOP_K)
    print(f"  Retrieved : {len(candidates)} candidates")

    top_chunks = rerank(query, candidates, top_n=TOP_N)
    print(f"  Reranked  : top {len(top_chunks)} chunks")
    print(f"\n  Top chunks used:")
    for i, c in enumerate(top_chunks, 1):
        meta = c['metadata']
        print(f"    {i}. [{meta.get('section_type','?')}] "
              f"{meta.get('source','?')} "
              f"({meta.get('filing_date','?')[:10]}) "
              f"score={c['rerank_score']:.3f}")

    answer = generate(query, top_chunks)
    print(f"\n  Answer:")
    print(f"  {answer}")
    print(f"{'='*60}")

    return {
        "query":      query,
        "answer":     answer,
        "top_chunks": top_chunks
    }

# ── RUN ──────────────────────────────────────────────────────────
# Step 1 — index (run once)
index_chunks(df_final)

# Step 2 — test queries
rag_query("What drove Microsoft revenue growth this quarter?")
rag_query("What risks did Microsoft highlight in their filings?")
rag_query("What is happening with Microsoft AI recently?")

#model loaded fine.

21:53:56  INFO      No device provided, using mps

Loading embedding model...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
21:53:57  WARNING   Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
21:53:57  INFO      Loading SentenceTransformer model from sentence-transformers/all-MiniLM-L6-v2.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
21:53:59  INFO      No device provided, using mps
21:53:59  INFO      No modules.json found for cross-encoder/ms-marco-MiniLM-L-6-v2, initializing a new CrossEncoder model.

Loading reranking model...

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-6-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

✓ Models loaded

Indexing 238 chunks...

Batches:   0%|          | 0/8 [00:00<?, ?it/s]

✓ 238 chunks indexed in ChromaDB

============================================================
  Query: What drove Microsoft revenue growth this quarter?
============================================================

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Retrieved : 20 candidates

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Reranked  : top 5 chunks

  Top chunks used:
    1. [MD&A] SEC EDGAR 10-K (2026-01-28) score=3.497
    2. [MD&A] SEC EDGAR 10-K (2026-01-28) score=0.969
    3. [MD&A] SEC EDGAR 10-K (2026-01-28) score=0.868
    4. [MD&A] SEC EDGAR 10-K (2026-01-28) score=0.784
    5. [8-K earnings] SEC EDGAR 8-K (2025-05-01) score=-0.170

  Answer:
  ## Microsoft Revenue Growth Drivers (Fiscal Year 2025)

Based on the SEC 10-K filing, Microsoft's total revenue grew **15% to $281.7 billion** (up $36.6 billion from $245.1 billion in FY2024), driven by growth across **all three segments**:

### Key Growth Drivers:

| Segment/Product | Growth |
|---|---|
| **Microsoft Cloud** (total) | +23% to $168.9B |
| **Azure & other cloud services** | +34% |
| **Server products & cloud services** | +23% |
| **Microsoft 365 Commercial cloud** | +15% |
| **Dynamics 365** | +19% |
| **Xbox content & services** | +16% |
| **Search & news advertising (ex-TAC)** | +20% |
| **LinkedIn** | +9% |

### Segment-Level Summary:
- **Intelligent Cloud**: Driven primarily by **Azure** growth (+34%)
- **Productivity & Business Processes**: Driven by **Microsoft 365 Commercial cloud**
- **More Personal Computing**: Driven by **Gaming and Search/news advertising**

### Notable Profitability Note:
While revenue grew strongly, **Microsoft Cloud gross margin declined to 69%**, reflecting the cost of **scaling AI infrastructure**, partially offset by efficiency gains in Azure.

> *Note: Source 5 (Apple earnings) is not relevant to this question and was disregarded.*
============================================================

============================================================
  Query: What risks did Microsoft highlight in their filings?
============================================================

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Retrieved : 20 candidates

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Reranked  : top 5 chunks

  Top chunks used:
    1. [Risk Factors] SEC EDGAR 10-K (2026-01-28) score=-3.539
    2. [Risk Factors] SEC EDGAR 10-K (2026-01-28) score=-4.298
    3. [Risk Factors] SEC EDGAR 10-K (2026-01-28) score=-4.514
    4. [Risk Factors] SEC EDGAR 10-K (2026-01-28) score=-4.714
    5. [MD&A] SEC EDGAR 10-K (2026-01-28) score=-7.638

  Answer:
  ## Microsoft's Key Risk Factors (10-K Filing, January 2026)

Based on the SEC 10-K filing, Microsoft highlighted the following risk categories:

---

### 1. 🔒 Fraud & Abuse in Cloud Services
Microsoft flagged risks from **unauthorized account use, stolen credentials, stolen credit cards, cryptocurrency mining, and cyberattacks** conducted through its cloud platforms, which could adversely impact revenue and reputation.

---

### 2. 💡 Investment Risk in New Products & AI
Microsoft acknowledges that **significant investments** in products like Azure, Microsoft 365, Windows, Bing, Xbox, LinkedIn, and **new AI platform services** may not achieve expected returns, as commercial success depends on innovativeness, developer support, and effective marketing.

---

### 3. ⚖️ Legal & Regulatory / Competition Risk
- Government agencies in the **EU, U.S., and China** actively scrutinize Microsoft under competition laws
- Flagship products like **Windows** face significant EU regulatory scrutiny
- Growing first-party device portfolio creates tension with OEM partners regarding competition compliance

---

### 4. 🤖 AI-Specific Risks
- Flawed algorithms, biased datasets, and harmful AI-generated content
- Risk of **regulatory action, legal liability**, and reputational harm
- New legislation (particularly in the **EU**) could impose additional compliance burdens

---

### 5. 🌐 Data Privacy & Regulatory Compliance
- Evolving **data sovereignty, localization, and privacy regulations** globally could increase costs, reduce efficiency, and limit innovation
- Non-compliance could result in **significant penalties** and operational disruptions

---

### 6. 🏭 Supply Chain Risk
Hardware including **Xbox consoles, Surface devices, and datacenter servers** are assembled in Asia, creating vulnerability to **supply chain disruptions** affecting revenue and operating margins.
============================================================

============================================================
  Query: What is happening with Microsoft AI recently?
============================================================

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Retrieved : 20 candidates

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Reranked  : top 5 chunks

  Top chunks used:
    1. [news] The Guardian Business (2026-04-21) score=-0.526
    2. [Risk Factors] SEC EDGAR 10-K (2026-01-28) score=-0.691
    3. [news] TechCrunch (2026-04-18) score=-2.702
    4. [news] CNBC (2026-04-21) score=-3.086
    5. [MD&A] SEC EDGAR 10-K (2026-01-28) score=-3.301

  Answer:
  ## Microsoft AI: Recent Developments

Based on the available context from Microsoft's SEC filings, here is what is happening with Microsoft's AI strategy:

### Strong Financial Performance Driven by AI
Microsoft's AI investments are showing clear revenue results (FY2025 vs FY2024):
- **Microsoft Cloud revenue grew 23% to $168.9 billion**
- **Azure and other cloud services grew 34%**, the strongest growth metric reported
- **Dynamics 365 grew 19%**, also largely AI-driven
- **Search and news advertising** (benefiting from AI integration) grew **20%**

### Strategic Vision
Per the 10-K (filed January 28, 2026), Microsoft envisions *"a future in which AI operating in our devices, applications, and the cloud helps our customers be more productive in their work and personal lives."*

### Acknowledged Risks
Microsoft explicitly flags AI-related risks in its SEC filings, including:
- Flawed algorithms or biased datasets
- Potential regulatory action (notably **EU AI legislation**)
- Legal liability and reputational harm
- Ethical concerns around AI deployment

### Competitive Context
Microsoft is noted as one of the leaders among megacaps (alongside Google, Meta, and Amazon) that have **"poured hundreds of billions of dollars into AI development"**, contrasting with peers like Apple who have been slower to invest.

> **Bottom line:** Microsoft's AI strategy appears to be delivering strong financial results, particularly through Azure cloud growth, though the company openly acknowledges significant regulatory and operational risks ahead.
============================================================

{'query': 'What is happening with Microsoft AI recently?',
 'answer': '## Microsoft AI: Recent Developments\n\nBased on the available context from Microsoft\'s SEC filings, here is what is happening with Microsoft\'s AI strategy:\n\n### Strong Financial Performance Driven by AI\nMicrosoft\'s AI investments are showing clear revenue results (FY2025 vs FY2024):\n- **Microsoft Cloud revenue grew 23% to $168.9 billion**\n- **Azure and other cloud services grew 34%**, the strongest growth metric reported\n- **Dynamics 365 grew 19%**, also largely AI-driven\n- **Search and news advertising** (benefiting from AI integration) grew **20%**\n\n### Strategic Vision\nPer the 10-K (filed January 28, 2026), Microsoft envisions *"a future in which AI operating in our devices, applications, and the cloud helps our customers be more productive in their work and personal lives."*\n\n### Acknowledged Risks\nMicrosoft explicitly flags AI-related risks in its SEC filings, including:\n- Flawed algorithms or biased datasets\n- Potential regulatory action (notably **EU AI legislation**)\n- Legal liability and reputational harm\n- Ethical concerns around AI deployment\n\n### Competitive Context\nMicrosoft is noted as one of the leaders among megacaps (alongside Google, Meta, and Amazon) that have **"poured hundreds of billions of dollars into AI development"**, contrasting with peers like Apple who have been slower to invest.\n\n> **Bottom line:** Microsoft\'s AI strategy appears to be delivering strong financial results, particularly through Azure cloud growth, though the company openly acknowledges significant regulatory and operational risks ahead.',
 'top_chunks': [{'text': '1. Fix the AI strategy Artificial intelligence has been a surprising weakness for Apple, at least in the eyes of some investors. It has stood on the sidelines as Microsoft, Google, Meta and Amazon have poured hundreds of billions of dollars into AI development. Instead, Apple has preferred partnerships and announced in January that its AI tech will be based on Google’s Gemini, including in a revamped version of its voice assistant, Siri. Dan Ives, an analyst at the US financial services firm Wedbush Securities, said: “We can’t say it enough but Apple cannot watch the AI era from the sidelines as this 4th industrial revolution takes hold. In essence, Apple is a toll collector on the consumer AI highway and Ternus needs to finally get the AI strategy right.” View image in fullscreen Jony Ive (left) and Tim Cook at an iPhone launch day in 2018. The iPhone brings in half of Apple’s revenue. Photograph: Qi Heng/VCG/Getty Images\n\n2. Diversify away from the iPhone This is something of a counterintuitive challenge for an executive who has received plaudits internally and externally for overseeing recent iPhone model launches. It is also not a new quandary. The iPhone, one of the signature consumer products of the 21st century, represented just over 50% of Apple’s $416bn in sales last year and has 1.5 billion active users worldwide. Nonetheless, the market is saturated and highly competitive. “They need to diversify away from the iPhone and make sure it no longer represents 50% of their revenue,” said Thomas Husson, an analyst at Forrester Research.',
   'metadata': {'ticker': 'MSFT',
    'company': 'Microsoft',
    'filing_date': '2026-04-21',
    'section_type': 'news',
    'source': 'The Guardian Business'},
   'distance': 0.47791415452957153,
   'rerank_score': -0.5256929397583008},
  {'text': 'We envision a future in which AI operating in our devices, applications, and the cloud helps our customers be more productive in their work and personal lives. As with many innovations, AI presents risks and challenges that could affect its adoption, and therefore our business. AI algorithms or training methodologies may be flawed. Datasets may be overbroad, insufficient, or contain biased information. Content generated by AI systems may be offensive, illegal, or otherwise harmful. Ineffective or inadequate AI development or deployment practices by Microsoft or others could result in incidents that impair the acceptance of AI solutions or cause harm to individuals, customers, or society, or result in our products and services not working as intended. Human review of certain outputs may be required. As a result of these and other challenges associated with innovative technologies, our implementation of AI systems could subject us to competitive harm, regulatory action, legal liability, including under new proposed legislation regulating AI in jurisdictions such as the European Union (“EU”), new applications of existing data protection, privacy, intellectual property, and other laws, and brand or reputational harm. Some AI scenarios present ethical issues or may have broad impacts on society.',
   'metadata': {'source': 'SEC EDGAR 10-K',
    'filing_date': '2026-01-28',
    'section_type': 'Risk Factors',
    'company': 'Microsoft',
    'ticker': 'MSFT'},
   'distance': 0.45712488889694214,
   'rerank_score': -0.6905502080917358},
  {'text': 'Everyone said AI would kill apps. Instead, new app launches are soaring. According to a new analysis from market intelligence provider Appfigures, worldwide app releases in the first quarter of 2026 were up 60% year-over-year across both Apple’s App Store and Google Play. That percentage was an even higher 80% when looking at the iOS App Store alone. In April 2026 so far, the total number of app releases is up 104% across both stores compared to the same time last year, and up 89% on iOS. As Apple’s Senior Vice President of Worldwide Marketing, Greg “Joz” Joswiak, quipped In a recent interview: rumors of the App Store’s death in the AI age “may have been greatly exaggerated.”\n\nImage Credits:Appfigures\n\nThese findings come amid concerns that the rise of AI chatbots and agents would ultimately see users turning away from apps — a theory that’s already being floated by those in the industry, like Nothing CEO Carl Pei, who is focused on building a smartphone for the AI era. The New York Times also reported last year on the potential for new computing platforms to eclipse the smartphone, like smart glasses, ambient computing devices, or reimagined smartwatches with AI features. OpenAI is even working on an AI hardware device with famed Apple designer Jony Ive. But there’s another possibility, too: AI will make it easier for anyone to create apps, driving a rebirth of the App Store. The new app gold rush could be led by creators who have ideas but not the technical skills to design mobile software. Appfigures’ data indicates that certain categories of apps are seeing more new rel',
   'metadata': {'section_type': 'news',
    'company': 'Microsoft',
    'ticker': 'MSFT',
    'filing_date': '2026-04-18',
    'source': 'TechCrunch'},
   'distance': 0.48264080286026,
   'rerank_score': -2.7019686698913574},
  {'text': 'Srouji said he\'ll organize hardware into five teams: hardware engineering, silicon, advanced technologies, platform architecture and project management. Tim Millet, who was tapped to lead platform architecture, told CNBC in an interview in September that in-house chips are "where the magic is." "When we have control, we are able to do things beyond what we can do by buying a merchant silicon part," he said. For Apple, the changes at the top come as Wall Street questions the company\'s AI strategy and whether it\'s made the right bet in focusing on the device and not the cloud. The company\'s stock price is down 2% this year, trailing all of its megacap peers other than Microsoft and Tesla. CNBC\'s interview with Ternus and Srouji took place in December of 2023, about a year after OpenAI released ChatGPT, kicking off the generative AI boom. When asked by CNBC at the time to respond to concerns that Apple appeared to be falling behind in AI, Srouji said, "I don\'t believe we are." Ternus added, with a laugh, that he was, "not too worried." WATCH: Apple told us all about its new iPhone chips and on-device AI plans\n\nwatch now',
   'metadata': {'filing_date': '2026-04-21',
    'source': 'CNBC',
    'company': 'Microsoft',
    'section_type': 'news',
    'ticker': 'MSFT'},
   'distance': 0.5730645656585693,
   'rerank_score': -3.0856311321258545},
  {'text': 'We create platforms and tools, powered by AI, that deliver innovative solutions that meet the evolving needs of our customers. We generate revenue by offering a wide range of cloud-based solutions, content, and other services to people and businesses; licensing and supporting an array of software products; delivering relevant online advertising to a global audience; and designing and selling devices. Our most significant expenses are related to compensating employees; supporting and investing in our cloud-based services, including datacenter operations; designing, manufacturing, marketing, and selling our other products\nand services; and income taxes. Highlights from fiscal year 2025 compared with fiscal year 2024 included:\n\n• Microsoft Cloud revenue increased 23% to $168.9 billion. • Microsoft 365 Commercial products and cloud services revenue increased 14% driven by Microsoft 365 Commercial cloud revenue growth of 15%. • Microsoft 365 Consumer products and cloud services revenue increased 11% driven by Microsoft 365 Consumer cloud revenue growth of 11%. • LinkedIn revenue increased 9%. • Dynamics products and cloud services revenue increased 15% driven by Dynamics 365 revenue growth of 19%. • Server products and cloud services revenue increased 23% driven by Azure and other cloud services revenue growth of 34%. • Windows OEM and Devices revenue increased 3%. • Xbox content and services revenue increased 16%. • Search and news advertising revenue excluding traffic acquisition costs increased 20%.',
   'metadata': {'company': 'Microsoft',
    'ticker': 'MSFT',
    'filing_date': '2026-01-28',
    'source': 'SEC EDGAR 10-K',
    'section_type': 'MD&A'},
   'distance': 0.6165370941162109,
   'rerank_score': -3.300689220428467}]}

In [32]:
# skip re-indexing — already done
# just run the queries

result1 = rag_query("What drove Apple revenue growth this quarter?")
print("\n")
result2 = rag_query("What risks did Apple highlight in their filings?")
print("\n")
result3 = rag_query("What is happening with Apple AI recently?")
result4 = rag_query("What is the latest news about Apple?")
result5 = rag_query("What did analysts say about Apple recently?")
result6 = rag_query("What Apple products were released recently?")
result7 = rag_query("What leadership changes happened at Apple?")
result8 = rag_query("What security issues did Apple have recently?")

============================================================
  Query: What drove Apple revenue growth this quarter?
============================================================

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Retrieved : 20 candidates

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Reranked  : top 5 chunks

  Top chunks used:
    1. [8-K earnings] SEC EDGAR 8-K (2025-05-01) score=5.898
    2. [8-K earnings] SEC EDGAR 8-K (2025-07-31) score=5.264
    3. [8-K earnings] SEC EDGAR 8-K (2026-01-29) score=4.679
    4. [8-K earnings] SEC EDGAR 8-K (2025-10-30) score=4.212
    5. [news] Wired (2026-04-21) score=1.089

  Answer:
  Based on the provided context, I need to flag an important issue: **this assistant is configured as a Microsoft (MSFT) financial analyst**, and all provided sources relate to **Apple (AAPL)**, not Microsoft.

That said, answering based solely on the provided context:

---

**Most Recent Quarter (Q1 FY2026, ended December 27, 2025):**

Apple's **16% year-over-year revenue growth to $143.8 billion** (an all-time record) was driven by:

- **iPhone**: Best-ever quarter with "unprecedented demand" and all-time records across every geographic segment
- **Services**: All-time revenue record of **~$30 billion**, up **14% year-over-year**, surpassing Mac, iPad, Apple Watch, and accessories combined
- **Strong margins**: Contributed to **19% EPS growth** to $2.84 (also an all-time record)
- **Geographic breadth**: Record performance across all geographic segments

Additionally, Apple's installed base surpassed **2.5 billion active devices**, reflecting strong customer retention and loyalty.

---

> ⚠️ **Note:** No Microsoft financial data was present in the provided context. If you intended to ask about Microsoft's revenue drivers, please provide the relevant MSFT SEC filings or earnings data.
============================================================



============================================================
  Query: What risks did Apple highlight in their filings?
============================================================

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Retrieved : 20 candidates

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Reranked  : top 5 chunks

  Top chunks used:
    1. [news] TechCrunch (2026-04-18) score=-3.780
    2. [8-K earnings] SEC EDGAR 8-K (2026-01-29) score=-7.314
    3. [8-K earnings] SEC EDGAR 8-K (2025-07-31) score=-7.435
    4. [8-K earnings] SEC EDGAR 8-K (2025-05-01) score=-7.581
    5. [8-K earnings] SEC EDGAR 8-K (2025-10-30) score=-7.602

  Answer:
  Based on the provided context from SEC filings and news sources, the documents do not contain sufficient information to answer this question adequately.

**Key limitation:** The SEC filing excerpts provided (8-K earnings releases from 2025-2026) are **incomplete** — they appear to be truncated and contain primarily financial statement headers, balance sheet line items, and cash flow figures, but **do not include any risk factor disclosures** or management discussion of risks.

**What the context does tangentially reference** (from the TechCrunch news article, not Apple's own filings):
- App Store security challenges, including fraudulent and malicious apps
- A malicious cryptocurrency app clone (Ledger Live) that drained **$9.5 million** from victims
- Bait-and-switch violations (**17,000+ apps removed/rejected in 2024**)
- Spam/misleading app submissions (**320,000+ rejected in 2024**)
- Potentially fraudulent apps (**37,000+ blocked in 2024**)

However, these are from a **TechCrunch article**, not Apple's official risk disclosures.

To get a comprehensive view of risks Apple has formally highlighted, I would recommend reviewing Apple's **10-K annual filing** or **10-Q quarterly filings**, which contain dedicated "Risk Factors" sections not included in the provided context.
============================================================



============================================================
  Query: What is happening with Apple AI recently?
============================================================

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Retrieved : 20 candidates

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Reranked  : top 5 chunks

  Top chunks used:
    1. [news] CNBC (2026-04-21) score=3.377
    2. [news] The Guardian Business (2026-04-21) score=3.261
    3. [news] CNBC (2026-04-21) score=2.834
    4. [news] Fortune (2026-04-21) score=2.673
    5. [news] TechCrunch (2026-04-18) score=2.261

  Answer:
  ## Apple's AI Strategy: Recent Developments

Based on the provided sources (primarily from April 2026), here is a summary of Apple's recent AI situation:

### Current Challenges
Apple has been widely criticized for **falling behind in the AI race**. As noted by Forrester Research analyst Thomas Husson, *"The challenge for the new CEO is really to make sure Apple is able to crack AI as the new user interface."* Dan Ives of Wedbush Securities stated bluntly: *"Apple cannot watch the AI era from the sidelines as this 4th industrial revolution takes hold."*

### Key Strategic Moves
- **Partnership over development**: Rather than building its own foundational AI model, Apple announced in **January 2026** that it would rely on **Google's Gemini** to power a revamped Siri and other AI features
- Apple previously integrated **OpenAI's ChatGPT** into its devices via Apple Intelligence (launched 2024), with mixed consumer response
- Apple is potentially partnering with **Broadcom on a server/data center chip** as soon as 2026

### Hardware Strength
Apple maintains a hardware advantage, with its **A19 and M5 chips** (unveiled 2025) featuring built-in neural accelerators, and a chip team of **thousands of engineers** globally.

### Key Open Question
A major strategic uncertainty remains: **how much Apple will invest in building its own AI platform versus relying on third-party models.**
============================================================

============================================================
  Query: What is the latest news about Apple?
============================================================

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Retrieved : 20 candidates

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Reranked  : top 5 chunks

  Top chunks used:
    1. [news] CNBC (2026-04-21) score=-0.657
    2. [8-K earnings] SEC EDGAR 8-K (2026-01-29) score=-1.119
    3. [8-K earnings] SEC EDGAR 8-K (2025-05-01) score=-1.455
    4. [8-K earnings] SEC EDGAR 8-K (2025-07-31) score=-1.493
    5. [8-K earnings] SEC EDGAR 8-K (2026-01-29) score=-1.581

  Answer:
  ## Latest News About Apple

**Note:** The provided context pertains to **Apple (AAPL)**, not Microsoft (MSFT). As a Microsoft financial analyst assistant, this falls outside my primary scope, but I can summarize what the context contains.

---

### Most Recent Developments (as of early 2026):

1. **CEO Transition** *(CNBC, April 21, 2026)*
 - Tim Cook is reportedly **stepping down as CEO** of Apple.

2. **U.S. Manufacturing Investment** *(CNBC, April 21, 2026)*
 - Apple plans to invest **$400 million through 2030** in new U.S.-based manufacturing programs for essential materials and components used in Apple products worldwide.

3. **Record Q1 FY2026 Results** *(SEC 8-K, January 29, 2026)*
 - Quarterly revenue of **$143.8 billion**, up **16% year-over-year**
 - Diluted EPS of **$2.84**, up **19% YoY** — an all-time record
 - Operating cash flow of **~$54 billion**
 - Installed base exceeded **2.5 billion active devices**
 - Cash dividend of **$0.26 per share** declared

---

*All information is sourced exclusively from the provided SEC filings and CNBC news context.*
============================================================

============================================================
  Query: What did analysts say about Apple recently?
============================================================

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Retrieved : 20 candidates

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Reranked  : top 5 chunks

  Top chunks used:
    1. [news] The Guardian Business (2026-04-21) score=2.837
    2. [8-K earnings] SEC EDGAR 8-K (2025-05-01) score=-0.294
    3. [8-K earnings] SEC EDGAR 8-K (2025-07-31) score=-0.438
    4. [8-K earnings] SEC EDGAR 8-K (2025-10-30) score=-0.612
    5. [8-K earnings] SEC EDGAR 8-K (2026-01-29) score=-0.727

  Answer:
  ## Analyst Commentary on Apple

Based on the provided context, two analysts were recently quoted regarding Apple's strategic challenges:

### 1. Dan Ives, Wedbush Securities
Ives was critical of Apple's **AI strategy**, stating:
> *"We can't say it enough but Apple cannot watch the AI era from the sidelines as this 4th industrial revolution takes hold. In essence, Apple is a toll collector on the consumer AI highway and Ternus needs to finally get the AI strategy right."*

He highlighted that Apple has lagged behind **Microsoft, Google, Meta, and Amazon**, which have poured hundreds of billions into AI development. Apple's approach has relied on partnerships, including a January announcement to base its AI on **Google's Gemini** for a revamped Siri.

### 2. Thomas Husson, Forrester Research
Husson flagged Apple's **over-reliance on the iPhone**, noting:
> *"They need to diversify away from the iPhone and make sure it no longer represents 50% of their revenue."*

This concern is notable given that the iPhone accounted for just over **50% of Apple's $416 billion in FY2025 sales**.

---

**Note:** These quotes are sourced from *The Guardian Business* (April 2026) and relate to **Apple (AAPL)**, not Microsoft (MSFT), which is outside the scope of this assistant's focus.
============================================================

============================================================
  Query: What Apple products were released recently?
============================================================

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Retrieved : 20 candidates

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Reranked  : top 5 chunks

  Top chunks used:
    1. [news] TechCrunch (2026-04-21) score=1.133
    2. [news] TechCrunch (2026-04-21) score=1.133
    3. [news] TechCrunch (2026-04-21) score=0.943
    4. [news] TechCrunch (2026-04-21) score=0.943
    5. [news] CNBC (2026-04-21) score=-0.049

  Answer:
  Based on the provided context, here are the notable Apple products mentioned, though I should note this context focuses on **Apple's history under Tim Cook** rather than strictly "recent" releases:

**Recent/Notable Product Launches:**
- **Apple Vision Pro** (2024) — Positioned as a spatial computing platform, priced at **$3,500**. However, it **failed to resonate with consumers** and has not become a consumer hit.

**Other Key Products Launched Under Cook's Tenure:**
- **Apple Watch** (2015) — Now includes blood oxygen tracking and ECG monitoring
- **AirPods** (2016) — Disrupted the wireless earphones market
- **Over-ear headphones** (2020)

**Important Caveat:** The context provided is primarily about **Apple (AAPL)**, not Microsoft (MSFT). As a Microsoft financial analyst assistant, I should flag that **this information is not relevant to MSFT's business or SEC filings**. If you have questions specifically about Microsoft's products, financials, or strategic initiatives, I'd be better positioned to assist with the appropriate context.
============================================================

============================================================
  Query: What leadership changes happened at Apple?
============================================================

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Retrieved : 20 candidates

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Reranked  : top 5 chunks

  Top chunks used:
    1. [news] Fortune (2026-04-21) score=2.467
    2. [news] Fortune (2026-04-21) score=0.822
    3. [news] The Guardian Tech (2026-04-21) score=0.198
    4. [news] TechCrunch (2026-04-21) score=-0.285
    5. [news] TechCrunch (2026-04-21) score=-0.285

  Answer:
  ## Apple Leadership Changes

Based on the provided sources, Apple announced a significant CEO transition:

**Key Changes:**
- **Tim Cook** will step down as CEO on **September 1, 2026** after nearly 15 years in the role, transitioning to the position of **Executive Chairman** of Apple's board of directors
- **John Ternus**, currently Senior Vice President of Hardware Engineering, will succeed Cook as **CEO effective September 1, 2026**

**About the Incoming CEO:**
- Ternus, age 50, joined Apple in 2001 and has spent almost his entire career there
- He became VP of Hardware Engineering in 2013 and head of the department in 2021
- He oversaw engineering for iPhone, iPad, Mac, Apple Watch, AirPods, and Apple Vision Pro

**About Tim Cook's Legacy:**
- Cook grew Apple's market cap **from ~$350 billion to $4 trillion** (a ~tenfold increase)
- Net income reached **$112 billion** for fiscal year ending September 2025 — an **eight times increase** from 2010
- Cook will remain through the summer to aid in the leadership transition

> ⚠️ **Note:** This question pertains to **Apple (AAPL)**, not Microsoft (MSFT). The provided context contains no information relevant to Microsoft's leadership or operations.
============================================================

============================================================
  Query: What security issues did Apple have recently?
============================================================

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Retrieved : 20 candidates

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Reranked  : top 5 chunks

  Top chunks used:
    1. [news] TechCrunch (2026-04-18) score=-0.228
    2. [news] The Guardian Tech (2026-04-21) score=-0.911
    3. [news] The Guardian Tech (2026-04-21) score=-1.504
    4. [news] CNBC (2026-04-21) score=-2.083
    5. [news] The Guardian Tech (2026-04-21) score=-3.058

  Answer:
  ## Recent Apple Security Issues

Based on the provided context, Apple has faced several notable security concerns:

### App Store Security Failures
- **Malicious crypto app**: A clone of **Ledger Live** slipped through App Store review and **drained $9.5 million in crypto** from victims' accounts *(TechCrunch, April 2026)*
- **Freecash rewards app**: Apple allowed this app to climb to the **top five in the App Store charts for months** before pulling it for rules violations — highlighting gaps in proactive monitoring *(TechCrunch, April 2026)*

### Law Enforcement & Privacy Tensions
- Despite Apple's strong public stance on privacy (e.g., refusing FBI access to the San Bernardino shooter's iPhone), critics note that **iCloud — turned on by default since 2015** — makes most users' data accessible to law enforcement via warrant or subpoena *(The Guardian, April 2026)*
- An **FBI document indicated it was easy to obtain iMessage data** via warrant or subpoena *(Rolling Stone, as cited in The Guardian)*

### Underlying Risk Factor
Analysts warn that the rise of **AI-assisted "vibe coding"** is flooding the App Store with new apps, increasing the risk of more malicious or fraudulent apps evading detection.

> *Note: This analysis is based solely on Apple (AAPL), not Microsoft (MSFT), as the provided context contains no MSFT-related security information.*
============================================================

In [ ]:


# print full text of each chunk without truncation
for i, chunk in enumerate(result['top_chunks'], 1):
    print(f"\n{'='*60}")
    print(f"CHUNK {i} FULL TEXT")
    print(f"{'='*60}")
    print(chunk['text'])
# ── retrieve by section ──────────────────────────────────────────
def retrieve_by_section(query: str, section_type: str, top_k: int = 10) -> list:
    query_vector = embedder.encode([query]).tolist()
    results = collection.query(
        query_embeddings = query_vector,
        n_results        = top_k,
        where            = {"section_type": section_type},
        include          = ["documents", "metadatas", "distances"]
    )
    candidates = []
    for doc, meta, dist in zip(
        results['documents'][0],
        results['metadatas'][0],
        results['distances'][0]
    ):
        candidates.append({
            "text":     doc,
            "metadata": meta,
            "distance": dist
        })
    return candidates

# ── hybrid RAG query ─────────────────────────────────────────────
def rag_query_hybrid(query: str) -> dict:
    print(f"\n{'='*60}")
    print(f"  Query (hybrid): {query}")
    print(f"{'='*60}")

    # retrieve from each section separately
    news_candidates     = retrieve_by_section(query, "news",         top_k=8)
    earnings_candidates = retrieve_by_section(query, "8-K earnings", top_k=6)
    risk_candidates     = retrieve_by_section(query, "Risk Factors", top_k=4)
    mda_candidates      = retrieve_by_section(query, "MD&A",         top_k=4)

    all_candidates = (news_candidates + earnings_candidates +
                     risk_candidates + mda_candidates)

    top_chunks = rerank(query, all_candidates, top_n=5)

    print(f"\n  Top chunks used:")
    for i, c in enumerate(top_chunks, 1):
        meta = c['metadata']
        print(f"\n  ── Chunk {i} ──────────────────────────────────")
        print(f"  Section : {meta.get('section_type','?')}")
        print(f"  Source  : {meta.get('source','?')}")
        print(f"  Date    : {meta.get('filing_date','?')[:10]}")
        print(f"  Score   : {c['rerank_score']:.3f}")
        print(f"  Text    : {c['text']}")

    answer = generate(query, top_chunks)
    print(f"\n  Answer:")
    print(f"  {answer}")

    return {
        "query":      query,
        "answer":     answer,
        "top_chunks": top_chunks
    }

# ── test ─────────────────────────────────────────────────────────

In [ ]:
rag_query_hybrid("What is Apple doing with employee monitoring?")
rag_query_hybrid("What leadership changes happened at Apple?")
rag_query_hybrid("What security issues did Apple have recently?")
rag_query_hybrid("What drove Apple revenue growth this quarter?")

============================================================
  Query (hybrid): What is Apple doing with employee monitoring?
============================================================

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Top chunks used:

  ── Chunk 1 ──────────────────────────────────
  Section : 8-K earnings
  Source  : SEC EDGAR 8-K
  Date    : 2025-07-31
  Score   : -3.983
  Text    : Apple will provide live streaming of its Q3 2025 financial results conference call beginning at 2:00 p.m. PT on July 31, 2025, at apple.com/investor/earnings-call. The webcast will be available for replay for approximately two weeks thereafter. Apple periodically provides information for investors on its corporate website, apple.com, and its re platforms — iOS, iPadOS, macOS, watchOS, visionOS, and tvOS — provide seamless experiences across all Apple devices and empower people with breakthrough services including the App Store, Apple Music, Apple Pay, iCloud, and Apple TV+. Apple’s more than 150,000 employees are dedicated to making the best products on earth and to leaving the world better than we found it. Press Contact:
Josh Rosenstock
Apple
jrosenstock@apple.com
f Apple. Other company and product names may be trademarks of their respective owners.

  ── Chunk 2 ──────────────────────────────────
  Section : news
  Source  : TechCrunch
  Date    : 2026-04-21
  Score   : -4.619
  Text    : Cook, who was formerly chief operations officer and credited as the brains behind Apple’s global supply chain under Steve Jobs, expanded Apple’s reach in China and added roughly 200 stores to the company’s global network during his tenure as CEO. New product categories

Image Credits:Justin Sullivan / Getty Images

Cook expanded Apple’s iPhone and computers ecosystem into a broader network of complementary devices that includes wearables and gadgets. Apple launched the Apple Watch in 2015 and has since turned it into a full-fledged health and fitness companion complete with blood oxygen tracking and ECG monitoring. Apple then disrupted the earphones market in 2016 with the launch of the first AirPods, changing the wireless headphones category. It then launched its first over-the-ear headphones in 2020. It’s also worth noting that Apple purchased Beats in 2014. The tech giant also released the Apple Vision Pro in 2024, positioning it not just as a VR headset, but as a spatial computing platform. The launch, however, failed to resonate with consumers who didn’t want to spend several thousand dollars to purchase the gadget. Techcrunch event Meet your next investor or portfolio startup at Disrupt

Your next round. Your next hire. Your next breakout opportunity. Find it at TechCrunch Disrupt 2026, where 10,000+ founders, investors, and tech leaders gather for three days of 250+ tactical sessions, powerful introductions, and market-defining innovation. Register now to save up to $410. Meet your next investor or portfolio startup at Disrupt

Your next round. Your next hire. Your n

  ── Chunk 3 ──────────────────────────────────
  Section : news
  Source  : TechCrunch
  Date    : 2026-04-21
  Score   : -4.619
  Text    : Cook, who was formerly chief operations officer and credited as the brains behind Apple’s global supply chain under Steve Jobs, expanded Apple’s reach in China and added roughly 200 stores to the company’s global network during his tenure as CEO. New product categories

Image Credits:Justin Sullivan / Getty Images

Cook expanded Apple’s iPhone and computers ecosystem into a broader network of complementary devices that includes wearables and gadgets. Apple launched the Apple Watch in 2015 and has since turned it into a full-fledged health and fitness companion complete with blood oxygen tracking and ECG monitoring. Apple then disrupted the earphones market in 2016 with the launch of the first AirPods, changing the wireless headphones category. It then launched its first over-the-ear headphones in 2020. It’s also worth noting that Apple purchased Beats in 2014. The tech giant also released the Apple Vision Pro in 2024, positioning it not just as a VR headset, but as a spatial computing platform. The launch, however, failed to resonate with consumers who didn’t want to spend several thousand dollars to purchase the gadget. Techcrunch event Meet your next investor or portfolio startup at Disrupt

Your next round. Your next hire. Your next breakout opportunity. Find it at TechCrunch Disrupt 2026, where 10,000+ founders, investors, and tech leaders gather for three days of 250+ tactical sessions, powerful introductions, and market-defining innovation. Register now to save up to $410. Meet your next investor or portfolio startup at Disrupt

Your next round. Your next hire. Your n

  ── Chunk 4 ──────────────────────────────────
  Section : 8-K earnings
  Source  : SEC EDGAR 8-K
  Date    : 2025-05-01
  Score   : -4.866
  Text    : The board of directors has also authorized an additional program to repurchase up to $100 billion of the Company’s common stock. Apple will provide live streaming of its Q2 2025 financial results conference call beginning at 2:00 p.m. PT on May 1, 2025 at apple.com/investor/earnings-call. The webcast will be available for replay for approximately two weeks thereafter. Apple periodically provides information for investors on its corporate website, apple.com, and its le Vision Pro. Apple’s six software platforms — iOS, iPadOS, macOS, watchOS, visionOS, and tvOS — provide seamless experiences across all Apple devices and empower people with breakthrough services including the App Store, Apple Music, Apple Pay, iCloud, and Apple TV+. Apple’s more than 150,000 employees are dedicated to making the best products on earth and to leaving the world better than we found it. Press Contact:
Josh Rosenstock
Apple
jrosenstock@apple.com
f Apple. Other company and product names may be trademarks of their respective owners.

  ── Chunk 5 ──────────────────────────────────
  Section : 8-K earnings
  Source  : SEC EDGAR 8-K
  Date    : 2026-01-29
  Score   : -5.022
  Text    : The dividend is payable on February 12, 2026, to shareholders of record as of the close of business on February 9, 2026. Apple will provide live streaming of its Q1 2026 financial results conference call beginning at 2:00 p.m. PT on January 29, 2026, at apple.com/investor/earnings-call. The webcast will be available for replay for approximately two weeks thereafter. Apple periodically provides information for investors on its corporate website, apple.com, and its six software platforms — iOS, iPadOS, macOS, watchOS, visionOS, and tvOS — provide seamless experiences across all Apple devices and empower people with breakthrough services including the App Store, Apple Music, Apple Pay, iCloud, and Apple TV. Apple’s more than 150,000 employees are dedicated to making the best products on earth and to leaving the world better than we found it. Press Contact:
Josh Rosenstock
Apple
jrosenstock@apple.com
f Apple. Other company and product names may be trademarks of their respective owners.

  Answer:
  Based on the provided context from SEC filings and news sources, **there is no information about Apple's employee monitoring practices or policies**.

The context covers topics such as Apple's earnings calls, product categories (Apple Watch, AirPods, Vision Pro), Tim Cook's tenure as CEO, and shareholder matters like stock repurchases and dividends — but does **not address employee monitoring** in any way.

To find accurate information on this topic, I would recommend consulting Apple's official HR policies, privacy reports, or relevant SEC disclosures directly.

============================================================
  Query (hybrid): What leadership changes happened at Apple?
============================================================

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Top chunks used:

  ── Chunk 1 ──────────────────────────────────
  Section : news
  Source  : Fortune
  Date    : 2026-04-21
  Score   : 0.822
  Text    : Apple is entering a new era. The company announced on Monday that CEO Tim Cook will be stepping down and John Ternus, Apple’s current senior vice president of hardware engineering, will succeed him. Cook has led the company for almost 15 years, assuming the role shortly before founder Steve Jobs’ death in 2011. Under his leadership, Apple’s market capitalization has grown from $350 billion to $4 trillion and the company has launched products such as iCloud, Apple Pay, AirPods, and the Apple Watch, redefining the brand as more than just a phone and computer company. Cook will step down as CEO on Sept. 1, but will remain as Apple’s executive chairman. The 65-year-old boasts one of the longest tenures in Big Tech as a non-founding CEO. He has navigated geopolitical conflicts, shielding Apple from tariffs, and landed huge partnerships with other big tech companies. His legacy has earned him praise from fellow business leaders following the announcement. “Tim Cook is a legend,” OpenAI CEO Sam Altman wrote on X. “I am very thankful for everything he has done, and I am very thankful for Apple.” In 2024, Apple agreed to integrate OpenAI’s ChatGPT chatbot into iPhone, iPad and Mac products, providing access to the company’s more than 1 billion users. Warren Buffett, chairman of Berkshire Hathaway, told CNBC: “Apple would not be the Apple of today without Tim Cook. “What he has done with Apple could not be done by anybody I’ve known,” he noted.

  ── Chunk 2 ──────────────────────────────────
  Section : news
  Source  : The Guardian Tech
  Date    : 2026-04-21
  Score   : 0.198
  Text    : Apple has announced longtime company veteran John Ternus as the next CEO of the company, succeeding the current CEO, Tim Cook, who is set to transition to executive chair of Apple’s board of directors later this year. Ternus’s term as CEO will begin on 1 September. The hardware engineering executive is a longtime Apple insider, indicating the company will stay the course that has led to record profits under Cook’s leadership. Apple’s yearly profit now tops $100bn, and in January it announced record revenue from its iPhones, boosted by renewed demand in China. “I am profoundly grateful for this opportunity to carry Apple’s mission forward,” Ternus said in a company press release. “Having spent almost my entire career at Apple, I have been lucky to have worked under Steve Jobs and to have had Tim Cook as my mentor. It has been a privilege to help shape the products and experiences that have changed so much of how we interact with the world and with one another.”

Cook will remain as Apple CEO through the summer to aid in the leadership transition. He praised his successor as having “the mind of an engineer, the soul of an innovator, and the heart to lead with integrity and with honor”. Ternus started at Apple in 2001 and assumed the role of vice-president of hardware engineering in 2013, then head of the department in 2021, responsible for the physical components that make up Apple products.

  ── Chunk 3 ──────────────────────────────────
  Section : news
  Source  : CNBC
  Date    : 2026-04-21
  Score   : -0.891
  Text    : Apple has maintained its dominance in consumer devices and built up a $4 trillion market cap despite largely sitting on the sidelines of the artificial intelligence boom. But investors won't remain patient forever, and they'll be looking to new CEO John Ternus for a clearer strategy when it comes to playing in the hottest market on the planet. Tim Cook's 15-year tenure as Apple CEO comes to an end on Sept. 1, the company announced on Monday. Ternus, Apple's longtime hardware boss, is taking over, becoming just the second leader since Steve Jobs departed in 2011, less than two months before he died from cancer. As Cook exits, Apple faces numerous challenges, including an intricate supply chain that's complicated by geopolitical tensions and soaring prices for memory due to unprecedented demand from the AI buildout. But for Ternus, perhaps the most critical aspect of his new job will be pushing the company deeper into AI, where it's lagged many of its megacap peers. So far, Apple's AI strategy has involved avoiding hefty capital expenditures while Microsoft , Google , Amazon and Meta commit to hundreds of billions of dollars a year in combined capex to fund new data centers and fill them with pricey AI chips. When it comes to developing a foundational AI model, Apple has punted there as well, and is instead counting on Google's Gemini to power its AI features, including a major Siri upgrade expected later this year following a delay.

  ── Chunk 4 ──────────────────────────────────
  Section : news
  Source  : Fortune
  Date    : 2026-04-21
  Score   : -1.877
  Text    : Tim Cook is handing Apple to its hardware chief, John Ternus. Wall Street is fine with it; Main Street, less so. The stock fell nearly 1% to around $270 after Tuesday’s open on news Ternus would succeed Cook on Sept. 1, with Cook transitioning to executive chairman after 15 years as CEO. Wedbush, Evercore, Citi, and BofA all kept buy ratings with price targets between $315 and $350. Some of the wariness tracked with Bloomberg Intelligence analyst Anurag Rana’s read that the move signaled “continuity rather than strategic change,” an awkward message at a moment when Apple needs to make a real pivot into AI. Wedbush Securities’ Dan Ives called the transition a “shocker,” noting investors had expected more clarity on a forward outlook before any handoff. “This will put even more pressure on Apple to produce success and its product road map at WWDC with AI front and center,” he wrote, referring to the Worldwide Developers Conference Apple hosts in June. Still, Ives kept his outperform rating and $350 target. Wall Street has been here before. When Steve Jobs handed the company to Cook in August 2011, Apple stock dragged for months before ripping 57% over the following year, according to a Morgan Stanley note from analyst Erik Woodring. Woodring, who rates Apple overweight with a $315 target, argues it’s a similar setup now. “Apple’s CEO change is unlikely to alter Apple’s core strategy/vision across hardware, software, capital returns, or vertical integration,” he wrote, but a CEO transition can unlock renewed optimism and a potential shift in the overarching Apple narrative. Co

  ── Chunk 5 ──────────────────────────────────
  Section : news
  Source  : The Guardian Tech
  Date    : 2026-04-21
  Score   : -2.219
  Text    : Ternus started at Apple in 2001 and assumed the role of vice-president of hardware engineering in 2013, then head of the department in 2021, responsible for the physical components that make up Apple products. Among his notable achievements was the development and launch of Apple’s proprietary silicon chips for its Mac line of computers, which saw sales soar after swapping out Intel chips in 2020, according to the Wall Street Journal. New products that debuted under his leadership of the hardware division include the Apple Watch and the AirPods line of headphones, both of which grew into major lines of business for Apple, and the Vision Pro headset, which did not. The Journal described Ternus as “an affable mechanical engineer” with a management style closer to the calm Cook than to the inspiring but volatile Steve Jobs. His replacement will be Johny Srouji, who previously worked as Apple’s senior vice-president of hardware. Cook, who joined Apple in 1998 and succeeded Jobs as CEO in 2011, had been engaged in planning his succession for the better part of a year, the New York Times reported in January, after Cook told the company’s board and senior leaders that he wanted to work less. Ternus had been a favorite for replacing Cook, the newspaper reported. Ternus, a California native, received his bachelor’s degree in mechanical engineering from the University of Pennsylvania, where he joined the varsity swim team in college and won several races. After graduating in 1997, he briefly worked at Virtual Research Systems, a virtual reality startup.

  Answer:
  ## Apple Leadership Changes (Announced April 21, 2026)

### Key Transition
- **Tim Cook** will step down as CEO on **September 1, 2026**, after nearly **15 years** in the role (assumed CEO position in 2011 following Steve Jobs' death).
- Cook will transition to **Executive Chairman** of Apple's board of directors.

### New CEO
- **John Ternus**, Apple's current Senior Vice President of Hardware Engineering, will become CEO effective **September 1, 2026**.
- Ternus joined Apple in **2001**, became VP of Hardware Engineering in **2013**, and became head of the department in **2021**.
- Notable achievements under his hardware leadership include Apple's proprietary **M-series silicon chips**, **AirPods**, **Apple Watch**, and the **Vision Pro** headset.

### Additional Personnel Change
- **Johny Srouji** will replace Ternus as Senior Vice President of Hardware Engineering.

### Market Reaction
- Apple stock fell **nearly 1%** to around **$270** following the announcement.
- Major analysts (Wedbush, Evercore, Citi, BofA) **maintained buy ratings** with price targets ranging from **$315 to $350**.

---
*Note: This context is entirely related to Apple (AAPL), not Microsoft (MSFT). No Microsoft-specific information was provided in these sources.*

============================================================
  Query (hybrid): What security issues did Apple have recently?
============================================================

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Top chunks used:

  ── Chunk 1 ──────────────────────────────────
  Section : news
  Source  : TechCrunch
  Date    : 2026-04-18
  Score   : -0.228
  Text    : It also seems possible that we’re hitting some sort of tipping point in terms of AI usability, where it’s easy enough for people to leverage these tools to build their own desired mobile apps more quickly — or even build their first apps ever. The explosion of new apps for Apple to review could also be behind some of the tech giant’s recent missteps. This week, Apple pulled the rewards app Freecash from the App Store for rules violations, after letting the app climb the store’s Top Charts and sit in the top five for months. Apple was also caught off guard by a malicious cryptocurrency app, a clone of Ledger Live, that drained $9.5 million in crypto from victims’ accounts. While high-profile problems like this can generate bad PR for the App Store, the company still does a lot of heavy lifting in terms of blocking and rejecting dangerous or spammy apps. Apple’s most recent analysis from 2024 said the company had removed or rejected more than 17,000 apps for bait-and-switch violations that year; rejected more than 320,000 app submissions that were found to be spam, copying other apps, or misleading; and took action to prevent more than 37,000 potentially fraudulent apps from reaching users on the App Store. Still, Apple pundits like John Gruber have long argued that the App Store needs a “bunco squad” of sorts that watches for scammy or fraudulent apps that are gaining in popularity or high-grossing. If AI-assisted vibe coding turns out to be behind the recent surge of app releases, that need will only grow as more new apps flood the marketplace, not all of which will be benign.

  ── Chunk 2 ──────────────────────────────────
  Section : news
  Source  : The Guardian Tech
  Date    : 2026-04-21
  Score   : -1.504
  Text    : Cook had more to say, so he wrote an open letter to Apple’s customers, explaining his decision. The ability to encrypt phones is essential, and while he was outraged by the San Bernardino murders and willing to comply with valid subpoenas and search warrants, Apple drew the line at enabling “a back door to the iPhone”. “The US government has asked us for something we simply do not have, and something we consider too dangerous to create,” he wrote. “The FBI may use different words to describe this tool, but make no mistake: building a version of iOS that bypasses security in this way would undeniably create a back door. And while the government may argue that its use would be limited to this case, there is no way to guarantee such control.”

The FBI ultimately withdrew its case, explaining that it no longer needed Apple’s help to access the phone. On the domestic front, Apple has still faced criticism for the ways it cooperates with law enforcement. In September 2015, a few months before the San Bernardino shooting and well into Cook’s term as CEO, Apple turned on iCloud by default for iPhone users, which largely remains the case today. The Tech Transparency Project points out that turning on iCloud allows most users’ data to be accessible to law enforcement without the need for a passcode. Rolling Stone reported in 2021 on an FBI document that indicated it was easy to get iMessage data via warrant or subpoena.

  ── Chunk 3 ──────────────────────────────────
  Section : news
  Source  : The Guardian Tech
  Date    : 2026-04-21
  Score   : -3.058
  Text    : Apple has been slow to invest in generative artificial intelligence and integrate the technology into its products, something shareholders have been clamoring for. And there have been hardware misses, including the lackluster $3,500 Vision Pro mixed reality headset, a possibly delayed folding smartphone that could have a “crease” problem, and a scuttled self-driving car project that cost the company about $10bn. For the most part, however, Cook has continued to do what he started under Jobs – methodically building up the company’s market share and profitability and working to safeguard it from volatility. In that sense, he’s overseen Apple go from a disruptive and innovative Silicon Valley startup to a financially secure heavyweight that habitually delivers what an ever-growing number of consumers worldwide expect. “While Cook has kept Apple’s growth trajectory moving at a steady clip, he has not overseen a step-change innovation that would reset Apple’s competitive position for the next two decades, as Jobs did with the iPhone,” Chatterjee said. “Cook’s legacy will be defined by steady, disciplined operational stewardship–proof that a company can be more than just exciting and visionary; it can also be immensely valuable to all its stakeholders.”

  ── Chunk 4 ──────────────────────────────────
  Section : news
  Source  : The Guardian Tech
  Date    : 2026-04-21
  Score   : -3.398
  Text    : In his 15 years as Apple’s top executive, Tim Cook has projected an image of the company as a champion of privacy rights. As he prepares to leave that role in September, that legacy has come back into focus. Cook trumpeted the iPhone maker’s commitment to privacy at home in the US and the EU, calling privacy “a fundamental right” but his acquiescence to government demands abroad call his dedication to protecting users into question. Cook cemented Apple’s pro-privacy reputation in 2015 when he resisted the FBI’s demands to unlock the iPhone of a mass shooter in San Bernardino, California. The company played up that public image in 2019 with playful ads that read, “Privacy. That’s iPhone”, positioning Apple as the obvious choice for people who cared about privacy. In 2021, Apple added a feature, App Tracking Transparency, that allowed iPhone owners to limit an app’s ability to track their mobile activity. Apps that tracked users without permission would be removed, Cook said. The company even sued Israeli spyware firm NSO group that same year, accusing it of surveilling iPhone users. Throughout his tenure, Cook spoke about privacy as a “fundamental human right” – and criticized Silicon Valley competitors Meta and Google for their expansive collection of user data. “This is surveillance,” he said at an EU privacy conference in 2018. Unlike Apple, Google’s search engine, as well as Meta’s Facebook and Instagram, are not available in China. But Apple’s international concessions, particularly in China, its second-largest and fastest-growing market, complicate Cook’s privacy legacy.

  ── Chunk 5 ──────────────────────────────────
  Section : news
  Source  : TechCrunch
  Date    : 2026-04-21
  Score   : -6.225
  Text    : In 2019, Apple launched Apple Arcade and has since built it out with a portfolio of premium games. Although Jobs first announced iCloud in 2011, the storage service has since grown vastly under Cook, including the launch of iCloud+ in 2021. Additionally, Cook oversaw the evolution of the App Store and repeatedly defended its 30% commission structure. Apple’s services business generated $109.16 billion in revenue during the fiscal year ending in September 2025. The segment accounted for a significant portion of the company’s total $416.16 billion revenue for the year. Shift to in-house processors

Image Credits:Harun Ozalp/Anadolu / Getty Images

Under Cook’s leadership, Apple began transitioning from Intel processors to its own Apple Silicon chips in 2020 and completed the shift across its Mac lineup by 2023. The result was longer battery life, higher performance, greater power efficiency, and more. AI era

Image Credits:Hakan Nural/Anadolu / Getty Images

Apple entered its AI era in 2024 with the launch of Apple Intelligence. Since then, however, the company hasn’t had any major breakthroughs and has faced significant delays in launching its anticipated revamped AI-powered Siri (it’s expected to roll out sometime this year). The tech giant remained largely absent from the broader tech industry’s generative AI race that kicked off when OpenAI’s ChatGPT launched in 2022. Earlier this year, Apple and Google announced that Google’s Gemini would power its next-generation AI tools.

  Answer:
  Based on the provided context, Apple has faced several recent security issues:

1. **Malicious Cryptocurrency App**: A clone of **Ledger Live** made it through App Store review and **drained $9.5 million in crypto** from victims' accounts — a significant failure in Apple's app vetting process.

2. **Fraudulent/Scammy Apps**: Apple's own 2024 analysis revealed the scale of the problem, reporting that the company:
   - Removed or rejected **17,000+ apps** for bait-and-switch violations
   - Rejected **320,000+ app submissions** for spam, copying, or misleading content
   - Prevented **37,000+ potentially fraudulent apps** from reaching users

3. **Rewards App Oversight**: Apple allowed the app **Freecash** to climb to the **top five in App Store charts** for months before pulling it for rules violations — highlighting gaps in proactive monitoring.

These issues are potentially being **compounded by AI-assisted "vibe coding,"** which is driving a surge in new app submissions, making thorough review increasingly difficult.

> *Note: These findings are sourced from TechCrunch (2026-04-18) and relate specifically to App Store security concerns. No broader device or software security vulnerabilities are mentioned in the provided context.*

============================================================
  Query (hybrid): What drove Apple revenue growth this quarter?
============================================================

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

  Top chunks used:

  ── Chunk 1 ──────────────────────────────────
  Section : 8-K earnings
  Source  : SEC EDGAR 8-K
  Date    : 2025-05-01
  Score   : 5.898
  Text    : Apple reports second quarter results
Services revenue reaches new all-time high
EPS sets March quarter record
CUPERTINO, CALIFORNIA — Apple® today announced financial results for its fiscal 2025 second quarter ended March 29, 2025. The Company posted quarterly revenue of $95.4 billion, up 5 percent year over year, and quarterly diluted earnings per share of $1.65, up 8 percent year over year. “Today Apple is reporting strong quarterly results, including double-digit growth in Services,” said Tim Cook, Apple’s CEO. “We were happy to welcome iPhone 16e to our lineup, and to introduce powerful new Macs and iPads that take advantage of the extraordinary capabilities of Apple silicon. And we were proud to announce that we’ve cut our carbon emissions by 60 percent over the past decade.”
“Our March quarter business performance drove EPS growth of 8 percent and $24 billion in operating cash flow, allowing us to return $29 billion to shareholders,” said Kevan Parekh, Apple’s CFO. “And thanks to our high levels of customer loyalty and satisfaction, our installed base of active devices once again reached a new all-time high across all product categories and geographic segments.”
Apple’s board of directors has declared a cash dividend of $0.26 per share of the Company’s common stock, an increase of 4 percent. The dividend is payable on May 15, 2025 to shareholders of record as of the close of business on May 12, 2025. The board of directors has also authorized an additional program to repurchase up to $100 billion of the Company’s common stock.

  ── Chunk 2 ──────────────────────────────────
  Section : 8-K earnings
  Source  : SEC EDGAR 8-K
  Date    : 2025-07-31
  Score   : 5.264
  Text    : Apple reports third quarter results
June quarter records for total company revenue, iPhone revenue and EPS
Services revenue reaches new all-time high
CUPERTINO, CALIFORNIA — Apple® today announced financial results for its fiscal 2025 third quarter ended June 28, 2025. The Company posted quarterly revenue of $94.0 billion, up 10 percent year over year, and quarterly diluted earnings per share of $1.57, up 12 percent year over year. “Today Apple is proud to report a June quarter revenue record with double-digit growth in iPhone, Mac and Services and growth around the world, in every geographic segment,” said Tim Cook, Apple’s CEO. “At WWDC25, we were excited to introduce a beautiful new software design that extends across all of our platforms, and we announced even more great Apple Intelligence features.”
“We are very pleased with our record business performance for the June quarter, which generated EPS growth of 12 percent,” said Kevan Parekh, Apple’s CFO. “Our installed base of active devices also reached a new all-time high across all product categories and geographic segments, thanks to our very high levels of customer satisfaction and loyalty.”
Apple’s board of directors has declared a cash dividend of $0.26 per share of the Company’s common stock. The dividend is payable on August 14, 2025 to shareholders of record as of the close of business on August 11, 2025. Apple will provide live streaming of its Q3 2025 financial results conference call beginning at 2:00 p.m. PT on July 31, 2025, at apple.com/investor/earnings-call.

  ── Chunk 3 ──────────────────────────────────
  Section : 8-K earnings
  Source  : SEC EDGAR 8-K
  Date    : 2026-01-29
  Score   : 4.679
  Text    : Apple reports first quarter results
All-time records for total company revenue and EPS
iPhone and Services revenue reach new all-time highs
CUPERTINO, CALIFORNIA — Apple® today announced financial results for its fiscal 2026 first quarter ended December 27, 2025. The Company posted quarterly revenue of $143.8 billion, up 16 percent year over year. Diluted earnings per share was $2.84, up 19 percent year over year. “Today, Apple is proud to report a remarkable, record-breaking quarter, with revenue of $143.8 billion, up 16 percent from a year ago and well above our expectations,” said Tim Cook, Apple’s CEO. “iPhone had its best-ever quarter driven by unprecedented demand, with all-time records across every geographic segment, and Services also achieved an all-time revenue record, up 14 percent from a year ago. We are also excited to announce that our installed base now has more than 2.5 billion active devices, which is a testament to incredible customer satisfaction for the very best products and services in the world.”
“During the December quarter, our record business performance and strong margins led to EPS growth of 19 percent, setting a new all-time EPS record,” said Kevan Parekh, Apple’s CFO. “These exceptionally strong results generated nearly $54 billion in operating cash flow, allowing us to return almost $32 billion to shareholders.”
Apple’s board of directors has declared a cash dividend of $0.26 per share of the Company’s common stock. The dividend is payable on February 12, 2026, to shareholders of record as of the close of business on February 9, 2026.

  ── Chunk 4 ──────────────────────────────────
  Section : 8-K earnings
  Source  : SEC EDGAR 8-K
  Date    : 2025-10-30
  Score   : 4.212
  Text    : Apple reports fourth quarter results
September quarter records for total company revenue, iPhone revenue and EPS
Services revenue reaches new all-time high
CUPERTINO, CALIFORNIA — Apple® today announced financial results for its fiscal 2025 fourth quarter ended September 27, 2025. The Company posted quarterly revenue of $102.5 billion, up 8 percent year over year. Diluted earnings per share was $1.85, up 13 percent year over year on an adjusted basis.1
“Today, Apple is very proud to report a September quarter revenue record of $102.5 billion, including a September quarter revenue record for iPhone and an all-time revenue record for Services,” said Tim Cook, Apple’s CEO. “In September, we were thrilled to launch our best iPhone lineup ever, including iPhone 17, iPhone 17 Pro and Pro Max, and iPhone Air. In addition, we launched the fantastic AirPods Pro 3 and the all-new Apple Watch lineup. When combined with the recently announced MacBook Pro and iPad Pro with the powerhouse M5 chip, we are excited to be sharing our most extraordinary lineup of products as we head into the holiday season.”
“Our September quarter results capped off a record fiscal year, with revenue reaching $416 billion, as well as double-digit EPS growth,” said Kevan Parekh, Apple’s CFO. “And thanks to our very high levels of customer satisfaction and loyalty, our installed base of active devices also reached a new all-time high across all product categories and geographic segments.”
Apple’s board of directors has declared a cash dividend of $0.26 per share of the Company’s common stock.

  ── Chunk 5 ──────────────────────────────────
  Section : news
  Source  : Wired
  Date    : 2026-04-21
  Score   : 1.089
  Text    : Tim Cook’s tenure as CEO at Apple, which is coming to a close September 1, will likely be defined by operational efficiency and financial growth, ushering Apple into its trillion-dollar era. But his most significant achievement might be in doubling down on Apple’s services business, which includes iCloud, the App Store, Apple Music, Apple TV+, News+, and more. It’s the subscription layer on top of iOS, and almost all of the service apps are tightly integrated with Messages, the glue that keeps people stuck to their iPhones. During Apple’s most recent earnings report, for the quarter ending December 2025, its services business reached an all-time revenue record of $30 billion. This was a 14 percent jump from the same quarter the year prior; services was also a bigger money-making business than Mac, iPad, Apple Watch, Home, and other accessories combined. For the entirety of fiscal year 2025, Apple services generated more than $109 billion for Apple, again, up 14 percent from 2024. When Cook first took over as CEO in 2011, “services” weren’t even broken out into a separate revenue category, although, for proxy, iTunes was generating around $6 billion annually. As the analyst Ben Thompson points out, some of the foundation-laying work for Apple’s services predated Cook’s term as CEO. The App Store launched in 2008, the year after Steve Jobs unveiled the iPhone, and it was Jobs’ foresight to charge up to a 30 percent “tax” on paid apps and in-app purchases.

  Answer:
  ## Apple Revenue Growth Drivers — Q1 FY2026 (Quarter Ended December 27, 2025)

Based on the most recent quarterly earnings available (Source 3 — 8-K dated 2026-01-29), Apple posted **$143.8 billion in revenue, up 16% year over year**, driven by the following key factors:

### Primary Growth Drivers:
1. **iPhone** — Achieved its **best-ever quarter**, with all-time records across **every geographic segment**, driven by "unprecedented demand"
2. **Services** — Reached an **all-time revenue record**, up **14% year over year**, hitting approximately **$30 billion** (per Source 5)

### Additional Highlights:
- **EPS** of **$2.84**, up **19% YoY**, setting a new all-time EPS record
- **Operating cash flow** of nearly **$54 billion**, enabling ~$32 billion returned to shareholders
- **Installed base** surpassed **2.5 billion active devices**, reflecting strong customer loyalty

### Context:
CEO Tim Cook described the quarter as "remarkable" and "well above expectations," with the performance broadly driven by strong product demand and the continued scaling of the high-margin Services segment.

> ⚠️ **Note:** This analysis is based on **Apple (AAPL)** filings, not Microsoft (MSFT). The provided context contains no Microsoft-specific financial data.

{'query': 'What drove Apple revenue growth this quarter?',
 'answer': '## Apple Revenue Growth Drivers — Q1 FY2026 (Quarter Ended December 27, 2025)\n\nBased on the most recent quarterly earnings available (Source 3 — 8-K dated 2026-01-29), Apple posted **$143.8 billion in revenue, up 16% year over year**, driven by the following key factors:\n\n### Primary Growth Drivers:\n1. **iPhone** — Achieved its **best-ever quarter**, with all-time records across **every geographic segment**, driven by "unprecedented demand"\n2. **Services** — Reached an **all-time revenue record**, up **14% year over year**, hitting approximately **$30 billion** (per Source 5)\n\n### Additional Highlights:\n- **EPS** of **$2.84**, up **19% YoY**, setting a new all-time EPS record\n- **Operating cash flow** of nearly **$54 billion**, enabling ~$32 billion returned to shareholders\n- **Installed base** surpassed **2.5 billion active devices**, reflecting strong customer loyalty\n\n### Context:\nCEO Tim Cook described the quarter as "remarkable" and "well above expectations," with the performance broadly driven by strong product demand and the continued scaling of the high-margin Services segment.\n\n> ⚠️ **Note:** This analysis is based on **Apple (AAPL)** filings, not Microsoft (MSFT). The provided context contains no Microsoft-specific financial data.',
 'top_chunks': [{'text': 'Apple reports second quarter results\nServices revenue reaches new all-time high\nEPS sets March quarter record\nCUPERTINO, CALIFORNIA — Apple® today announced financial results for its fiscal 2025 second quarter ended March 29, 2025. The Company posted quarterly revenue of $95.4 billion, up 5 percent year over year, and quarterly diluted earnings per share of $1.65, up 8 percent year over year. “Today Apple is reporting strong quarterly results, including double-digit growth in Services,” said Tim Cook, Apple’s CEO. “We were happy to welcome iPhone 16e to our lineup, and to introduce powerful new Macs and iPads that take advantage of the extraordinary capabilities of Apple silicon. And we were proud to announce that we’ve cut our carbon emissions by 60 percent over the past decade.”\n“Our March quarter business performance drove EPS growth of 8 percent and $24 billion in operating cash flow, allowing us to return $29 billion to shareholders,” said Kevan Parekh, Apple’s CFO. “And thanks to our high levels of customer loyalty and satisfaction, our installed base of active devices once again reached a new all-time high across all product categories and geographic segments.”\nApple’s board of directors has declared a cash dividend of $0.26 per share of the Company’s common stock, an increase of 4 percent. The dividend is payable on May 15, 2025 to shareholders of record as of the close of business on May 12, 2025. The board of directors has also authorized an additional program to repurchase up to $100 billion of the Company’s common stock.',
   'metadata': {'section_type': '8-K earnings',
    'source': 'SEC EDGAR 8-K',
    'ticker': 'AAPL',
    'filing_date': '2025-05-01',
    'company': 'Microsoft'},
   'distance': 0.23131102323532104,
   'rerank_score': 5.898166656494141},
  {'text': 'Apple reports third quarter results\nJune quarter records for total company revenue, iPhone revenue and EPS\nServices revenue reaches new all-time high\nCUPERTINO, CALIFORNIA — Apple® today announced financial results for its fiscal 2025 third quarter ended June 28, 2025. The Company posted quarterly revenue of $94.0 billion, up 10 percent year over year, and quarterly diluted earnings per share of $1.57, up 12 percent year over year. “Today Apple is proud to report a June quarter revenue record with double-digit growth in iPhone, Mac and Services and growth around the world, in every geographic segment,” said Tim Cook, Apple’s CEO. “At WWDC25, we were excited to introduce a beautiful new software design that extends across all of our platforms, and we announced even more great Apple Intelligence features.”\n“We are very pleased with our record business performance for the June quarter, which generated EPS growth of 12 percent,” said Kevan Parekh, Apple’s CFO. “Our installed base of active devices also reached a new all-time high across all product categories and geographic segments, thanks to our very high levels of customer satisfaction and loyalty.”\nApple’s board of directors has declared a cash dividend of $0.26 per share of the Company’s common stock. The dividend is payable on August 14, 2025 to shareholders of record as of the close of business on August 11, 2025. Apple will provide live streaming of its Q3 2025 financial results conference call beginning at 2:00 p.m. PT on July 31, 2025, at apple.com/investor/earnings-call.',
   'metadata': {'filing_date': '2025-07-31',
    'source': 'SEC EDGAR 8-K',
    'ticker': 'AAPL',
    'section_type': '8-K earnings',
    'company': 'Microsoft'},
   'distance': 0.22335553169250488,
   'rerank_score': 5.263728141784668},
  {'text': 'Apple reports first quarter results\nAll-time records for total company revenue and EPS\niPhone and Services revenue reach new all-time highs\nCUPERTINO, CALIFORNIA — Apple® today announced financial results for its fiscal 2026 first quarter ended December 27, 2025. The Company posted quarterly revenue of $143.8 billion, up 16 percent year over year. Diluted earnings per share was $2.84, up 19 percent year over year. “Today, Apple is proud to report a remarkable, record-breaking quarter, with revenue of $143.8 billion, up 16 percent from a year ago and well above our expectations,” said Tim Cook, Apple’s CEO. “iPhone had its best-ever quarter driven by unprecedented demand, with all-time records across every geographic segment, and Services also achieved an all-time revenue record, up 14 percent from a year ago. We are also excited to announce that our installed base now has more than 2.5 billion active devices, which is a testament to incredible customer satisfaction for the very best products and services in the world.”\n“During the December quarter, our record business performance and strong margins led to EPS growth of 19 percent, setting a new all-time EPS record,” said Kevan Parekh, Apple’s CFO. “These exceptionally strong results generated nearly $54 billion in operating cash flow, allowing us to return almost $32 billion to shareholders.”\nApple’s board of directors has declared a cash dividend of $0.26 per share of the Company’s common stock. The dividend is payable on February 12, 2026, to shareholders of record as of the close of business on February 9, 2026.',
   'metadata': {'company': 'Microsoft',
    'section_type': '8-K earnings',
    'source': 'SEC EDGAR 8-K',
    'filing_date': '2026-01-29',
    'ticker': 'AAPL'},
   'distance': 0.25602835416793823,
   'rerank_score': 4.678727149963379},
  {'text': 'Apple reports fourth quarter results\nSeptember quarter records for total company revenue, iPhone revenue and EPS\nServices revenue reaches new all-time high\nCUPERTINO, CALIFORNIA — Apple® today announced financial results for its fiscal 2025 fourth quarter ended September 27, 2025. The Company posted quarterly revenue of $102.5 billion, up 8 percent year over year. Diluted earnings per share was $1.85, up 13 percent year over year on an adjusted basis.1\n“Today, Apple is very proud to report a September quarter revenue record of $102.5 billion, including a September quarter revenue record for iPhone and an all-time revenue record for Services,” said Tim Cook, Apple’s CEO. “In September, we were thrilled to launch our best iPhone lineup ever, including iPhone 17, iPhone 17 Pro and Pro Max, and iPhone Air. In addition, we launched the fantastic AirPods Pro 3 and the all-new Apple Watch lineup. When combined with the recently announced MacBook Pro and iPad Pro with the powerhouse M5 chip, we are excited to be sharing our most extraordinary lineup of products as we head into the holiday season.”\n“Our September quarter results capped off a record fiscal year, with revenue reaching $416 billion, as well as double-digit EPS growth,” said Kevan Parekh, Apple’s CFO. “And thanks to our very high levels of customer satisfaction and loyalty, our installed base of active devices also reached a new all-time high across all product categories and geographic segments.”\nApple’s board of directors has declared a cash dividend of $0.26 per share of the Company’s common stock.',
   'metadata': {'source': 'SEC EDGAR 8-K',
    'ticker': 'AAPL',
    'section_type': '8-K earnings',
    'company': 'Microsoft',
    'filing_date': '2025-10-30'},
   'distance': 0.26677268743515015,
   'rerank_score': 4.2118635177612305},
  {'text': 'Tim Cook’s tenure as CEO at Apple, which is coming to a close September 1, will likely be defined by operational efficiency and financial growth, ushering Apple into its trillion-dollar era. But his most significant achievement might be in doubling down on Apple’s services business, which includes iCloud, the App Store, Apple Music, Apple TV+, News+, and more. It’s the subscription layer on top of iOS, and almost all of the service apps are tightly integrated with Messages, the glue that keeps people stuck to their iPhones. During Apple’s most recent earnings report, for the quarter ending December 2025, its services business reached an all-time revenue record of $30 billion. This was a 14 percent jump from the same quarter the year prior; services was also a bigger money-making business than Mac, iPad, Apple Watch, Home, and other accessories combined. For the entirety of fiscal year 2025, Apple services generated more than $109 billion for Apple, again, up 14 percent from 2024. When Cook first took over as CEO in 2011, “services” weren’t even broken out into a separate revenue category, although, for proxy, iTunes was generating around $6 billion annually. As the analyst Ben Thompson points out, some of the foundation-laying work for Apple’s services predated Cook’s term as CEO. The App Store launched in 2008, the year after Steve Jobs unveiled the iPhone, and it was Jobs’ foresight to charge up to a 30 percent “tax” on paid apps and in-app purchases.',
   'metadata': {'source': 'Wired',
    'ticker': 'MSFT',
    'filing_date': '2026-04-21',
    'company': 'Microsoft',
    'section_type': 'news'},
   'distance': 0.3095897436141968,
   'rerank_score': 1.088756799697876}]}